local colors = {
    fg = "#cad3f5", -- text
    bg = "#24273a", -- base
    black = "#1e2030", -- mantle
    skyblue = "#91d7e3", -- sky
    cyan = "#8aadf4", -- blue
    green = "#a6da95", -- green
    oceanblue = "#7dc4e4", -- sapphire
    magenta = "#f5bde6", -- pink
    orange = "#f0c6c6", -- flamingo
    red = "#ed8796", -- red
    violet = "#c6a0f6", -- mauve
    white = "#b8c0e0", -- subtext1
    yellow = "#eed49f" -- yellow
}

local hls = {
    ["WhichKeyGroup"] = { fg = "#8AADF4" },
    ["WhichKeyFloat"] = { bg = "#181926" },
    ["mkdCodeDelimiter"] = { bg = "#24273A", fg = "#CAD3F5" },
    ["WhichKeyDesc"] = { fg = "#F5BDE6" },
    ["htmlH1"] = { fg = "#F5BDE6" },
    ["Visual"] = { bg = "#494D64" },
    ["Underlined"] = { underline = true },
    ["Typedef"] = { fg = "#EED49F" },
    ["Todo"] = { bg = "#EED49F", fg = "#24273A" },
    ["CmpItemKindField"] = { fg = "#A6DA95" },
    ["CmpItemKindEvent"] = { fg = "#8AADF4" },
    ["CmpItemKindEnumMember"] = { fg = "#ED8796" },
    ["TelescopeSelectionCaret"] = { fg = "#F0C6C6" },
    ["TelescopeSelection"] = { bg = "#363A4F", fg = "#CAD3F5" },
    ["TelescopeMatching"] = { fg = "#8AADF4" },
    ["CmpItemKindConstant"] = { fg = "#F5A97F" },
    ["Tag"] = { link = "Special" },
    ["CmpItemKindClass"] = { fg = "#EED49F" },
    ["TabLine"] = { bg = "#1E2030", fg = "#494D64" },
    ["TSWarning"] = { bg = "#EED49F", fg = "#24273A" },
    ["TSVariableBuiltin"] = { fg = "#ED8796" },
    ["TSVariable"] = { fg = "#CAD3F5" },
    ["IndentBlanklineContextChar"] = { fg = "#CAD3F5" },
    ["TSURI"] = { fg = "#F4DBD6", underline = true },
    ["TSTypeBuiltin"] = { fg = "#EED49F" },
    ["TSTextReference"] = { fg = "#B7BDF8" },
    ["TSStringRegex"] = { fg = "#F5A97F" },
    ["WinBar"] = { fg = "#F4DBD6" },
    ["TSStringEscape"] = { fg = "#F5BDE6" },
    ["TSPunctSpecial"] = { fg = "#91D7E3" },
    ["TSPunctDelimiter"] = { fg = "#939AB7" },
    ["TSPunctBracket"] = { fg = "#939AB7" },
    ["TSProperty"] = { fg = "#8BD5CA" },
    ["TSField"] = { fg = "#8BD5CA" },
    ["TSOperator"] = { fg = "#91D7E3" },
    ["TSNote"] = { bg = "#8AADF4", fg = "#24273A" },
    ["TSNamespace"] = { fg = "#8AADF4" },
    ["TSKeywordOperator"] = { fg = "#C6A0F6" },
    ["TSKeywordFunction"] = { fg = "#C6A0F6" },
    ["TSFuncMacro"] = { fg = "#8BD5CA" },
    ["TSFuncBuiltin"] = { fg = "#F5A97F" },
    ["TSDanger"] = { bg = "#ED8796", fg = "#24273A" },
    ["TSConstructor"] = { fg = "#7DC4E4" },
    ["TSConstBuiltin"] = { fg = "#F5A97F" },
    ["Conceal"] = { fg = "#8087A2" },
    ["Substitute"] = { bg = "#494D64", fg = "#F5BDE6" },
    ["Structure"] = { fg = "#EED49F" },
    ["StorageClass"] = { fg = "#EED49F" },
    ["SpellRare"] = { sp = "#A6DA95", undercurl = true },
    ["SpellLocal"] = { sp = "#8AADF4", undercurl = true },
    ["SpellCap"] = { sp = "#EED49F", undercurl = true },
    ["SpellBad"] = { sp = "#ED8796", undercurl = true },
    ["SpecialKey"] = { fg = "#CAD3F5" },
    ["SpecialComment"] = { link = "Special" },
    ["SpecialChar"] = { link = "Special" },
    ["SignColumnSB"] = { bg = "#181926", fg = "#494D64" },
    ["Repeat"] = { fg = "#ED8796" },
    ["QuickFixLine"] = { bg = "#494D64" },
    ["Question"] = { fg = "#8AADF4" },
    ["MoreMsg"] = { fg = "#8AADF4" },
    ["PreCondit"] = { link = "PreProc" },
    ["NvimTreeFolderName"] = { fg = "#8AADF4" },
    ["LeapMatch"] = { fg = "#b2eaa0", nocombine = true, underline = true },
    ["PmenuThumb"] = { bg = "#6E738D" },
    ["LeapLabelPrimary"] = { bg = "#b2eaa0", fg = "#24273A", nocombine = true },
    ["LeapLabelSecondary"] = { bg = "#91D7E3", fg = "#24273A", nocombine = true },
    ["NvimTreeRootFolder"] = { fg = "#8AADF4" },
    ["NotifyWARNTitle"] = { fg = "#EED49F" },
    ["TSTagAttribute"] = { fg = "#8BD5CA" },
    ["NotifyWARNBorder"] = { fg = "#EED49F" },
    ["TSTag"] = { fg = "#C6A0F6" },
    ["NotifyTRACETitle"] = { fg = "#F4DBD6" },
    ["TSLiteral"] = { fg = "#8BD5CA" },
    ["TSTitle"] = { fg = "#8AADF4" },
    ["NotifyTRACEBorder"] = { fg = "#F4DBD6" },
    ["NotifyINFOTitle"] = { fg = "#8AADF4" },
    ["NotifyINFOIcon"] = { fg = "#8AADF4" },
    ["NotifyINFOBorder"] = { fg = "#8AADF4" },
    ["LspReferenceWrite"] = { bg = "#494D64" },
    ["LspReferenceRead"] = { bg = "#494D64" },
    ["LspReferenceText"] = { bg = "#494D64" },
    ["NotifyDEBUGTitle"] = { fg = "#F5A97F" },
    ["NotifyDEBUGIcon"] = { fg = "#F5A97F" },
    ["NotifyDEBUGBorder"] = { fg = "#F5A97F" },
    ["NvimTreeGitNew"] = { fg = "#8AADF4" },
    ["Delimiter"] = { link = "Special" },
    ["Debug"] = { link = "Special" },
    ["DashboardShortCut"] = { fg = "#F5BDE6" },
    ["DashboardHeader"] = { fg = "#8AADF4" },
    ["DashboardFooter"] = { fg = "#EED49F" },
    ["DashboardCenter"] = { fg = "#A6DA95" },
    ["PmenuSel"] = { bg = "#494D64", fg = "#CAD3F5" },
    ["NormalFloat"] = { bg = "#1E2030", fg = "#CAD3F5" },
    ["CursorIM"] = { bg = "#CAD3F5", fg = "#24273A" },
    ["CurSearch"] = { bg = "#ED8796", fg = "#1E2030" },
    ["ColorColumn"] = { bg = "#363A4F" },
    ["CmpItemKindVariable"] = { fg = "#F0C6C6" },
    ["CmpItemKindValue"] = { fg = "#F5A97F" },
    ["CmpItemKindUnit"] = { fg = "#A6DA95" },
    ["Macro"] = { link = "PreProc" },
    ["Operator"] = { fg = "#91D7E3" },
    ["LspTroubleNormal"] = { bg = "#181926", fg = "#CAD3F5" },
    ["Function"] = { fg = "#8AADF4" },
    ["Constant"] = { fg = "#F5A97F" },
    ["CmpItemKindOperator"] = { fg = "#8AADF4" },
    ["Type"] = { fg = "#8AADF4" },
    ["CmpItemKindMethod"] = { fg = "#8AADF4" },
    ["Boolean"] = { fg = "#F5A97F" },
    ["Number"] = { fg = "#F5A97F" },
    ["NvimTreeEmptyFolderName"] = { fg = "#8AADF4" },
    ["NvimTreeOpenedFolderName"] = { fg = "#8AADF4" },
    ["NvimTreeFolderIcon"] = { fg = "#8AADF4" },
    ["Label"] = { fg = "#F5A97F" },
    ["Italic"] = { italic = true },
    ["NvimTreeSymlink"] = { fg = "#F5BDE6" },
    ["NvimTreeOpenedFile"] = { fg = "#F5BDE6" },
    ["NvimTreeImageFile"] = { fg = "#CAD3F5" },
    ["GlyphPalette9"] = { fg = "#ED8796" },
    ["NvimTreeSpecialFile"] = { fg = "#F0C6C6" },
    ["CmpItemKind"] = { fg = "#8AADF4" },
    ["GlyphPalette7"] = { fg = "#CAD3F5" },
    ["CmpItemAbbrDeprecated"] = { fg = "#6E738D", strikethrough = true },
    ["GlyphPalette6"] = { fg = "#8BD5CA" },
    ["GlyphPalette4"] = { fg = "#8AADF4" },
    ["GlyphPalette3"] = { fg = "#EED49F" },
    ["GlyphPalette2"] = { fg = "#8BD5CA" },
    ["TSException"] = { fg = "#C6A0F6" },
    ["TSKeywordReturn"] = { fg = "#C6A0F6" },
    ["TSKeyword"] = { fg = "#C6A0F6" },
    ["luaTSConstructor"] = { fg = "#B7BDF8" },
    ["TSRepeat"] = { fg = "#C6A0F6" },
    ["TSConditional"] = { fg = "#C6A0F6" },
    ["Folded"] = { bg = "#494D64", fg = "#8AADF4" },
    ["FoldColumn"] = { fg = "#6E738D" },
    ["TSMethod"] = { fg = "#8AADF4" },
    ["FloatBorder"] = { fg = "#8AADF4" },
    ["TSParameter"] = { fg = "#EE99A0" },
    ["TSFunction"] = { fg = "#8AADF4" },
    ["TSFloat"] = { fg = "#F5A97F" },
    ["TSBoolean"] = { fg = "#F5A97F" },
    ["TSNumber"] = { fg = "#F5A97F" },
    ["MiniStarterFooter"] = { fg = "#EED49F" },
    ["MiniStarterHeader"] = { fg = "#8AADF4" },
    ["TSConstMacro"] = { fg = "#C6A0F6" },
    ["MiniStarterItem"] = { fg = "#CAD3F5" },
    ["MiniStarterSection"] = { fg = "#F0C6C6" },
    ["MiniStarterItemPrefix"] = { fg = "#F5BDE6" },
    ["MiniTrailspace"] = { bg = "#ED8796" },
    ["GitSignsAdd"] = { fg = "#A6DA95" },
    ["Bold"] = { bold = true },
    ["CmpItemAbbrMatch"] = { fg = "#CAD3F5" },
    ["CmpItemAbbrMatchFuzzy"] = { fg = "#CAD3F5" },
    ["MiniStarterInactive"] = { fg = "#5B6078" },
    ["MiniStarterQuery"] = { fg = "#A6DA95" },
    ["MiniStarterCurrent"] = {},
    ["DiagnosticVirtualTextError"] = { bg = "NONE", fg = "#ED8796" },
    ["LspSignatureActiveParameter"] = { fg = "#F5A97F" },
    ["Include"] = { fg = "#F5BDE6" },
    ["DiagnosticVirtualTextInfo"] = { bg = "NONE", fg = "#91D7E3" },
    ["DiagnosticUnderlineHint"] = { sp = "#8BD5CA", underline = true },
    ["DiagnosticUnderlineError"] = { sp = "#ED8796", underline = true },
    ["DiagnosticUnderlineWarn"] = { sp = "#EED49F", underline = true },
    ["DiagnosticUnderlineInfo"] = { sp = "#91D7E3", underline = true },
    ["Character"] = { fg = "#8BD5CA" },
    ["DiagnosticError"] = { bg = "NONE", fg = "#ED8796" },
    ["Comment"] = { fg = "#5B6078" },
    ["DiagnosticWarn"] = { bg = "NONE", fg = "#EED49F" },
    ["WarningMsg"] = { fg = "#EED49F" },
    ["DiagnosticInfo"] = { bg = "NONE", fg = "#91D7E3" },
    ["DiagnosticHint"] = { bg = "NONE", fg = "#8BD5CA" },
    ["MiniStatuslineModeCommand"] = { bg = "#F5A97F", fg = "#24273A" },
    ["MiniStatuslineInactive"] = { bg = "#1E2030", fg = "#8AADF4" },
    ["MiniStatuslineFilename"] = { bg = "#1E2030", fg = "#CAD3F5" },
    ["MiniStatuslineFileinfo"] = { bg = "#494D64", fg = "#B8C0E0" },
    ["MiniStatuslineDevinfo"] = { bg = "#494D64", fg = "#B8C0E0" },
    ["MiniJump2dSpot"] = { bg = "#24273A", fg = "#F5A97F", underline = true },
    ["MiniJump"] = { bg = "#F5BDE6", fg = "#939AB7" },
    ["MiniIndentscopePrefix"] = { nocombine = true },
    ["MiniIndentscopeSymbol"] = { fg = "#CAD3F5" },
    ["WhichKeyBorder"] = { fg = "#8AADF4" },
    ["MiniCursorword"] = { underline = true },
    ["MiniCompletionActiveParameter"] = { underline = true },
    ["SignColumn"] = { fg = "#494D64" },
    ["NvimTreeNormal"] = { bg = "NONE", fg = "#CAD3F5" },
    ["CursorLine"] = { bg = "NONE" },
    ["VertSplit"] = { fg = "NONE" },
    ["StatusLine"] = { bg = "#1E2030", fg = "#CAD3F5" },
    ["StatusLineNC"] = { bg = "#1E2030", fg = "#494D64" },
    ["CursorColumn"] = { bg = "#1E2030" },
    ["NormalNC"] = { bg = "NONE", fg = "#CAD3F5" },
    ["MiniTestPass"] = { fg = "#A6DA95" },
    ["NvimTreeStatuslineNc"] = { bg = "#1E2030", fg = "#1E2030" },
    ["MiniTestEmphasis"] = { bold = true },
    ["MiniTablineVisible"] = { bg = "#494D64", fg = "#B8C0E0" },
    ["MiniTablineTabpagesection"] = { bg = "#24273A", fg = "#494D64" },
    ["MiniTablineModifiedVisible"] = { bg = "#B8C0E0", fg = "#494D64" },
    ["MiniTablineModifiedHidden"] = { bg = "#CAD3F5", fg = "NONE" },
    ["MiniTablineModifiedCurrent"] = { bg = "#CAD3F5", fg = "#24273A" },
    ["MiniTablineHidden"] = { bg = "NONE", fg = "#CAD3F5" },
    ["MiniTablineFill"] = { bg = "NONE" },
    ["MiniTablineCurrent"] = { bg = "#24273A", fg = "#CAD3F5" },
    ["yamlTSField"] = { fg = "#8AADF4" },
    ["MiniStatuslineModeVisual"] = { bg = "#C6A0F6", fg = "#24273A" },
    ["MiniStatuslineModeReplace"] = { bg = "#ED8796", fg = "#24273A" },
    ["MiniStatuslineModeOther"] = { bg = "#8BD5CA", fg = "#24273A" },
    ["MiniStatuslineModeNormal"] = { bg = "#8AADF4", fg = "#1E2030" },
    ["MiniStatuslineModeInsert"] = { bg = "#A6DA95", fg = "#24273A" },
    ["tomlTSProperty"] = { fg = "#8AADF4" },
    ["diffRemoved"] = { fg = "#ED8796" },
    ["diffChanged"] = { fg = "#8AADF4" },
    ["diffAdded"] = { fg = "#A6DA95" },
    ["LspCodeLens"] = { fg = "#6E738D" },
    ["GitSignsChange"] = { fg = "#EED49F" },
    ["ModeMsg"] = { fg = "#CAD3F5" },
    ["Pmenu"] = { bg = "#363A4F", fg = "#939AB7" },
    ["GitSignsDelete"] = { fg = "#ED8796" },
    ["EndOfBuffer"] = { fg = "#24273A" },
    ["NonText"] = { fg = "#6E738D" },
    ["CmpItemKindStruct"] = { fg = "#8AADF4" },
    ["CmpItemKindReference"] = { fg = "#ED8796" },
    ["MsgArea"] = { fg = "#CAD3F5" },
    ["TabLineFill"] = {},
    ["Title"] = { fg = "#8AADF4" },
    ["VisualNOS"] = { bg = "#494D64" },
    ["Whitespace"] = { fg = "#494D64" },
    ["ErrorMsg"] = { fg = "#ED8796" },
    ["MsgSeparator"] = {},
    ["NormalSB"] = { bg = "#181926", fg = "#CAD3F5" },
    ["IncSearch"] = { bg = "#86C5D2", fg = "#1E2030" },
    ["illuminatedCurWord"] = { bg = "#494D64" },
    ["WildMenu"] = { bg = "#6E738D" },
    ["Special"] = { fg = "#F5BDE6" },
    ["Keyword"] = { fg = "#F5BDE6" },
    ["diffFile"] = { fg = "#8AADF4" },
    ["healthWarning"] = { fg = "#EED49F" },
    ["healthSuccess"] = { fg = "#8BD5CA" },
    ["MatchParen"] = { fg = "#F5A97F" },
    ["PmenuSbar"] = { bg = "#494D64" },
    ["debugPC"] = { bg = "#181926" },
    ["debugBreakpoint"] = { bg = "#24273A", fg = "#6E738D" },
    ["healthError"] = { fg = "#ED8796" },
    ["CursorLineNr"] = { fg = "#B7BDF8" },
    ["Directory"] = { fg = "#8AADF4" },
    ["String"] = { fg = "#A6DA95" },
    ["TSText"] = { fg = "#CAD3F5" },
    ["Normal"] = { bg = "NONE", fg = "#CAD3F5" },
    ["LineNr"] = { fg = "#494D64" },
    ["diffIndexLine"] = { fg = "#8BD5CA" },
    ["TabLineSel"] = { bg = "#494D64", fg = "#A6DA95" },
    ["diffLine"] = { fg = "#6E738D" },
    ["diffNewFile"] = { fg = "#F5A97F" },
    ["diffOldFile"] = { fg = "#EED49F" },
    ["Search"] = { bg = "#455C6D", fg = "#CAD3F5" },
    ["illuminatedWord"] = { bg = "#494D64" },
    ["PreProc"] = { fg = "#F5BDE6" },
    ["Define"] = { link = "PreProc" },
    ["IndentBlanklineContextStart"] = { sp = "#CAD3F5", underline = true },
    ["NvimTreeVertSplit"] = { bg = "NONE", fg = "#24273A" },
    ["DiffChange"] = { bg = "#2B3047" },
    ["DiffAdd"] = { bg = "#3B474A" },
    ["DiffDelete"] = { bg = "#48384B" },
    ["DiffText"] = { bg = "#363F5B" },
    ["Float"] = { fg = "#F5A97F" },
    ["GlyphPalette1"] = { fg = "#ED8796" },
    ["TelescopeBorder"] = { fg = "#8AADF4" },
    ["DiagnosticVirtualTextHint"] = { bg = "NONE", fg = "#8BD5CA" },
    ["WhichKeySeperator"] = { fg = "#6E738D" },
    ["WhichKeyValue"] = { fg = "#6E738D" },
    ["htmlH2"] = { fg = "#8AADF4" },
    ["mkdCodeStart"] = { fg = "#F0C6C6" },
    ["mkdCodeEnd"] = { fg = "#F0C6C6" },
    ["TSConstant"] = { fg = "#F5A97F" },
    ["Error"] = { fg = "#ED8796" },
    ["Conditional"] = { fg = "#ED8796" },
    ["NotifyERRORTitle"] = { fg = "#ED8796" },
    ["NotifyERRORIcon"] = { fg = "#ED8796" },
    ["Identifier"] = { fg = "#F0C6C6" },
    ["CmpItemKindConstructor"] = { fg = "#8AADF4" },
    ["Statement"] = { fg = "#C6A0F6" },
    ["TSEmphasis"] = { fg = "#EE99A0" },
    ["TSStrong"] = { fg = "#EE99A0" },
    ["MiniCursorwordCurrent"] = { underline = true },
    ["MiniSurround"] = { bg = "#F5BDE6", fg = "#494D64" },
    ["cppTSProperty"] = { fg = "#F4DBD6" },
    ["LspTroubleCount"] = { bg = "#494D64", fg = "#F5BDE6" },
    ["CmpItemKindProperty"] = { fg = "#A6DA95" },
    ["CmpItemKindModule"] = { fg = "#8AADF4" },
    ["CmpItemKindKeyword"] = { fg = "#ED8796" },
    ["CmpItemKindInterface"] = { fg = "#EED49F" },
    ["CmpItemKindFunction"] = { fg = "#8AADF4" },
    ["DiagnosticVirtualTextWarn"] = { bg = "NONE", fg = "#EED49F" },
    ["MiniStarterItemBullet"] = { fg = "#8AADF4" },
    ["NvimTreeGitDirty"] = { fg = "#EED49F" },
    ["CmpItemKindFile"] = { fg = "#8AADF4" },
    ["CmpItemMenu"] = { fg = "#CAD3F5" },
    ["NotifyTRACEIcon"] = { fg = "#F4DBD6" },
    ["NotifyWARNIcon"] = { fg = "#EED49F" },
    ["CmpItemKindCopilot"] = { fg = "#8BD5CA" },
    ["CmpItemKindFolder"] = { fg = "#8AADF4" },
    ["tsxTSTagAttribute"] = { fg = "#C6A0F6" },
    ["NvimTreeGitDeleted"] = { fg = "#ED8796" },
    ["CmpItemKindText"] = { fg = "#8BD5CA" },
    ["typescriptTSConstructor"] = { fg = "#B7BDF8" },
    ["tsxTSConstructor"] = { fg = "#B7BDF8" },
    ["CmpItemKindColor"] = { fg = "#ED8796" },
    ["TSTagDelimiter"] = { fg = "#91D7E3" },
    ["jsonTSLabel"] = { fg = "#8AADF4" },
    ["TSString"] = { fg = "#A6DA95" },
    ["MiniTestFail"] = { fg = "#ED8796" },
    ["CmpItemKindEnum"] = { fg = "#A6DA95" },
    ["NotifyERRORBorder"] = { fg = "#ED8796" },
    ["TSLabel"] = { fg = "#7DC4E4" },
    ["TSType"] = { fg = "#EED49F" },
    ["TSInclude"] = { fg = "#C6A0F6" },
    ["CmpItemAbbr"] = { fg = "#939AB7" },
    ["NvimTreeIndentMarker"] = { fg = "#6E738D" },
    ["markdownH6"] = { fg = "#8BD5CA" },
    ["markdownH5"] = { fg = "#F5BDE6" },
    ["markdownH4"] = { fg = "#EED49F" },
    ["markdownH3"] = { fg = "#A6DA95" },
    ["markdownH2"] = { fg = "#C6A0F6" },
    ["markdownH1"] = { fg = "#B7BDF8" },
    ["markdownLinkText"] = { fg = "#8AADF4", underline = true },
    ["markdownCodeBlock"] = { fg = "#F0C6C6" },
    ["markdownCode"] = { fg = "#F0C6C6" },
    ["markdownHeadingDelimiter"] = { fg = "#F5A97F" },
    ["CmpItemKindSnippet"] = { fg = "#C6A0F6" },
    ["WhichKey"] = { fg = "#F0C6C6" },
    ["LspTroubleText"] = { fg = "#A6DA95" },
    ["CmpItemKindTypeParameter"] = { fg = "#8AADF4" },
    ["IndentBlanklineChar"] = { fg = "#363A4F" },
    ["qfLineNr"] = { fg = "#EED49F" },
    ["qfFileName"] = { fg = "#8AADF4" },
    ["lCursor"] = { bg = "#CAD3F5", fg = "#24273A" },
    ["Cursor"] = { bg = "#CAD3F5", fg = "#24273A" },
    ["LspDiagnosticsUnderlineHint"] = { sp = "#8BD5CA", underline = true },
    ["LspDiagnosticsUnderlineInformation"] = { sp = "#91D7E3", underline = true },
    ["LspDiagnosticsUnderlineWarning"] = { sp = "#EED49F", underline = true },
    ["LspDiagnosticsUnderlineError"] = { sp = "#ED8796", underline = true },
    ["LspDiagnosticsVirtualTextHint"] = { fg = "#8BD5CA" },
    ["LspDiagnosticsVirtualTextInformation"] = { fg = "#91D7E3" },
    ["LspDiagnosticsVirtualTextWarning"] = { fg = "#EED49F" },
    ["LspDiagnosticsVirtualTextError"] = { fg = "#ED8796" },
    ["LspDiagnosticsHint"] = { fg = "#8BD5CA" },
    ["LspDiagnosticsInformation"] = { fg = "#91D7E3" },
    ["LspDiagnosticsWarning"] = { fg = "#EED49F" },
    ["LspDiagnosticsError"] = { fg = "#ED8796" },
    ["LspDiagnosticsDefaultHint"] = { fg = "#8BD5CA" },
    ["LspDiagnosticsDefaultInformation"] = { fg = "#91D7E3" },
    ["LspDiagnosticsDefaultWarning"] = { fg = "#EED49F" },
    ["LspDiagnosticsDefaultError"] = { fg = "#ED8796" },
}

return {
    colors = colors,
    hls = hls
}
