-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "tokyonight"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@annotation", { link = "PreProc" })
hi(0, "@attribute", { link = "PreProc" })
hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@comment.error", { fg = "#c53b53" })
hi(0, "@comment.hint", { fg = "#4fd6be" })
hi(0, "@comment.info", { fg = "#0db9d7" })
hi(0, "@comment.note", { fg = "#4fd6be" })
hi(0, "@comment.todo", { fg = "#82aaff" })
hi(0, "@comment.warning", { fg = "#ffc777" })
hi(0, "@constant.builtin", { link = "Special" })
hi(0, "@constant.macro", { link = "Define" })
hi(0, "@constructor", { fg = "#c099ff" })
hi(0, "@constructor.tsx", { fg = "#65bcff" })
hi(0, "@diff.delta", { link = "DiffChange" })
hi(0, "@diff.minus", { link = "DiffDelete" })
hi(0, "@diff.plus", { link = "DiffAdd" })
hi(0, "@function.builtin", { link = "Special" })
hi(0, "@function.call", { link = "@function" })
hi(0, "@function.macro", { link = "Macro" })
hi(0, "@function.method", { link = "Function" })
hi(0, "@function.method.call", { link = "@function.method" })
hi(0, "@keyword", { fg = "#fca7ea" })
hi(0, "@keyword.conditional", { link = "Conditional" })
hi(0, "@keyword.coroutine", { link = "@keyword" })
hi(0, "@keyword.debug", { link = "Debug" })
hi(0, "@keyword.directive", { link = "PreProc" })
hi(0, "@keyword.directive.define", { link = "Define" })
hi(0, "@keyword.exception", { link = "Exception" })
hi(0, "@keyword.function", { fg = "#c099ff" })
hi(0, "@keyword.import", { link = "Include" })
hi(0, "@keyword.operator", { link = "@operator" })
hi(0, "@keyword.repeat", { link = "Repeat" })
hi(0, "@keyword.return", { link = "@keyword" })
hi(0, "@keyword.storage", { link = "StorageClass" })
hi(0, "@label", { fg = "#82aaff" })
hi(0, "@lsp.type.boolean", { link = "@boolean" })
hi(0, "@lsp.type.builtinType", { link = "@type.builtin" })
hi(0, "@lsp.type.comment", { link = "@comment" })
hi(0, "@lsp.type.decorator", { link = "@attribute" })
hi(0, "@lsp.type.deriveHelper", { link = "@attribute" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.escapeSequence", { link = "@string.escape" })
hi(0, "@lsp.type.formatSpecifier", { link = "@markup.list" })
hi(0, "@lsp.type.generic", { link = "@variable" })
hi(0, "@lsp.type.interface", { fg = "#93d0ff" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.lifetime", { link = "@keyword.storage" })
hi(0, "@lsp.type.namespace", { link = "@module" })
hi(0, "@lsp.type.namespace.python", { link = "@variable" })
hi(0, "@lsp.type.number", { link = "@number" })
hi(0, "@lsp.type.operator", { link = "@operator" })
hi(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.selfKeyword", { link = "@variable.builtin" })
hi(0, "@lsp.type.selfTypeKeyword", { link = "@variable.builtin" })
hi(0, "@lsp.type.string", { link = "@string" })
hi(0, "@lsp.type.typeAlias", { link = "@type.definition" })
hi(0, "@lsp.type.unresolvedReference", { sp = "#c53b53", undercurl = true })
hi(0, "@lsp.type.variable", {})
hi(0, "@lsp.typemod.class.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.enum.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.enumMember.defaultLibrary", { link = "@constant.builtin" })
hi(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.keyword.async", { link = "@keyword.coroutine" })
hi(0, "@lsp.typemod.keyword.injected", { link = "@keyword" })
hi(0, "@lsp.typemod.macro.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.method.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.operator.injected", { link = "@operator" })
hi(0, "@lsp.typemod.string.injected", { link = "@string" })
hi(0, "@lsp.typemod.struct.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.type.defaultLibrary", { fg = "#589ed7" })
hi(0, "@lsp.typemod.typeAlias.defaultLibrary", { fg = "#589ed7" })
hi(0, "@lsp.typemod.variable.callable", { link = "@function" })
hi(0, "@lsp.typemod.variable.defaultLibrary", { link = "@variable.builtin" })
hi(0, "@lsp.typemod.variable.injected", { link = "@variable" })
hi(0, "@lsp.typemod.variable.static", { link = "@constant" })
hi(0, "@markup", { link = "@none" })
hi(0, "@markup.emphasis", { italic = true })
hi(0, "@markup.environment", { link = "Macro" })
hi(0, "@markup.environment.name", { link = "Type" })
hi(0, "@markup.heading", { link = "Title" })
hi(0, "@markup.heading.1.markdown", { bold = true, fg = "#82aaff" })
hi(0, "@markup.heading.2.markdown", { bold = true, fg = "#ffc777" })
hi(0, "@markup.heading.3.markdown", { bold = true, fg = "#c3e88d" })
hi(0, "@markup.heading.4.markdown", { bold = true, fg = "#4fd6be" })
hi(0, "@markup.heading.5.markdown", { bold = true, fg = "#c099ff" })
hi(0, "@markup.heading.6.markdown", { bold = true, fg = "#fca7ea" })
hi(0, "@markup.link", { fg = "#4fd6be" })
hi(0, "@markup.link.label", { link = "SpecialChar" })
hi(0, "@markup.link.label.symbol", { link = "Identifier" })
hi(0, "@markup.link.url", { link = "Underlined" })
hi(0, "@markup.list", { fg = "#89ddff" })
hi(0, "@markup.list.checked", { fg = "#4fd6be" })
hi(0, "@markup.list.markdown", { bold = true, fg = "#ff966c" })
hi(0, "@markup.list.unchecked", { fg = "#82aaff" })
hi(0, "@markup.math", { link = "Special" })
hi(0, "@markup.raw", { link = "String" })
hi(0, "@markup.raw.markdown_inline", { bg = "#444a73", fg = "#82aaff" })
hi(0, "@markup.strikethrough", { strikethrough = true })
hi(0, "@markup.strong", { bold = true })
hi(0, "@markup.underline", { underline = true })
hi(0, "@module", { link = "Include" })
hi(0, "@module.builtin", { fg = "#ff757f" })
hi(0, "@namespace.builtin", { link = "@variable.builtin" })
hi(0, "@number.float", { link = "Float" })
hi(0, "@operator", { fg = "#89ddff" })
hi(0, "@property", { fg = "#4fd6be" })
hi(0, "@punctuation.bracket", { fg = "#828bb8" })
hi(0, "@punctuation.delimiter", { fg = "#89ddff" })
hi(0, "@punctuation.special", { fg = "#89ddff" })
hi(0, "@string.documentation", { fg = "#ffc777" })
hi(0, "@string.escape", { fg = "#c099ff" })
hi(0, "@string.regexp", { fg = "#b4f9f8" })
hi(0, "@tag", { link = "Label" })
hi(0, "@tag.attribute", { link = "@property" })
hi(0, "@tag.delimiter", { link = "Delimiter" })
hi(0, "@tag.delimiter.tsx", { fg = "#6582c3" })
hi(0, "@tag.tsx", { fg = "#ff757f" })
hi(0, "@type.builtin", { fg = "#589ed7" })
hi(0, "@type.definition", { link = "Typedef" })
hi(0, "@type.qualifier", { link = "@keyword" })
hi(0, "@variable", { fg = "#c8d3f5" })
hi(0, "@variable.builtin", { fg = "#ff757f" })
hi(0, "@variable.member", { fg = "#4fd6be" })
hi(0, "@variable.parameter", { fg = "#ffc777" })
hi(0, "@variable.parameter.builtin", { fg = "#ffd292" })
hi(0, "ALEErrorSign", { fg = "#c53b53" })
hi(0, "ALEWarningSign", { fg = "#ffc777" })
hi(0, "AerialArrayIcon", { link = "LspKindArray" })
hi(0, "AerialBooleanIcon", { link = "LspKindBoolean" })
hi(0, "AerialClassIcon", { link = "LspKindClass" })
hi(0, "AerialColorIcon", { link = "LspKindColor" })
hi(0, "AerialConstantIcon", { link = "LspKindConstant" })
hi(0, "AerialConstructorIcon", { link = "LspKindConstructor" })
hi(0, "AerialEnumIcon", { link = "LspKindEnum" })
hi(0, "AerialEnumMemberIcon", { link = "LspKindEnumMember" })
hi(0, "AerialEventIcon", { link = "LspKindEvent" })
hi(0, "AerialFieldIcon", { link = "LspKindField" })
hi(0, "AerialFileIcon", { link = "LspKindFile" })
hi(0, "AerialFolderIcon", { link = "LspKindFolder" })
hi(0, "AerialFunctionIcon", { link = "LspKindFunction" })
hi(0, "AerialGuide", { fg = "#3b4261" })
hi(0, "AerialInterfaceIcon", { link = "LspKindInterface" })
hi(0, "AerialKeyIcon", { link = "LspKindKey" })
hi(0, "AerialKeywordIcon", { link = "LspKindKeyword" })
hi(0, "AerialLine", { link = "LspInlayHint" })
hi(0, "AerialMethodIcon", { link = "LspKindMethod" })
hi(0, "AerialModuleIcon", { link = "LspKindModule" })
hi(0, "AerialNamespaceIcon", { link = "LspKindNamespace" })
hi(0, "AerialNormal", { fg = "#c8d3f5" })
hi(0, "AerialNullIcon", { link = "LspKindNull" })
hi(0, "AerialNumberIcon", { link = "LspKindNumber" })
hi(0, "AerialObjectIcon", { link = "LspKindObject" })
hi(0, "AerialOperatorIcon", { link = "LspKindOperator" })
hi(0, "AerialPackageIcon", { link = "LspKindPackage" })
hi(0, "AerialPropertyIcon", { link = "LspKindProperty" })
hi(0, "AerialReferenceIcon", { link = "LspKindReference" })
hi(0, "AerialSnippetIcon", { link = "LspKindSnippet" })
hi(0, "AerialStringIcon", { link = "LspKindString" })
hi(0, "AerialStructIcon", { link = "LspKindStruct" })
hi(0, "AerialTextIcon", { link = "LspKindText" })
hi(0, "AerialTypeParameterIcon", { link = "LspKindTypeParameter" })
hi(0, "AerialUnitIcon", { link = "LspKindUnit" })
hi(0, "AerialValueIcon", { link = "LspKindValue" })
hi(0, "AerialVariableIcon", { link = "LspKindVariable" })
hi(0, "AlphaButtons", { fg = "#86e1fc" })
hi(0, "AlphaFooter", { fg = "#65bcff" })
hi(0, "AlphaHeader", { fg = "#82aaff" })
hi(0, "AlphaHeaderLabel", { fg = "#ff966c" })
hi(0, "AlphaShortcut", { fg = "#ff966c" })
hi(0, "Bold", { bold = true, fg = "#c8d3f5" })
hi(0, "BufferAlternate", { bg = "#3b4261", fg = "#c8d3f5" })
hi(0, "BufferAlternateERROR", { bg = "#3b4261", fg = "#c53b53" })
hi(0, "BufferAlternateHINT", { bg = "#3b4261", fg = "#4fd6be" })
hi(0, "BufferAlternateINFO", { bg = "#3b4261", fg = "#0db9d7" })
hi(0, "BufferAlternateIndex", { bg = "#3b4261", fg = "#0db9d7" })
hi(0, "BufferAlternateMod", { bg = "#3b4261", fg = "#ffc777" })
hi(0, "BufferAlternateSign", { bg = "#3b4261", fg = "#0db9d7" })
hi(0, "BufferAlternateTarget", { bg = "#3b4261", fg = "#ff757f" })
hi(0, "BufferAlternateWARN", { bg = "#3b4261", fg = "#ffc777" })
hi(0, "BufferCurrent", { bg = "#222436", fg = "#c8d3f5" })
hi(0, "BufferCurrentERROR", { bg = "#222436", fg = "#c53b53" })
hi(0, "BufferCurrentHINT", { bg = "#222436", fg = "#4fd6be" })
hi(0, "BufferCurrentINFO", { bg = "#222436", fg = "#0db9d7" })
hi(0, "BufferCurrentIndex", { bg = "#222436", fg = "#0db9d7" })
hi(0, "BufferCurrentMod", { bg = "#222436", fg = "#ffc777" })
hi(0, "BufferCurrentSign", { bg = "#222436", fg = "#222436" })
hi(0, "BufferCurrentTarget", { bg = "#222436", fg = "#ff757f" })
hi(0, "BufferCurrentWARN", { bg = "#222436", fg = "#ffc777" })
hi(0, "BufferInactive", { bg = "#272a3f", fg = "#63698c" })
hi(0, "BufferInactiveERROR", { bg = "#272a3f", fg = "#a4364d" })
hi(0, "BufferInactiveHINT", { bg = "#272a3f", fg = "#46b2a3" })
hi(0, "BufferInactiveINFO", { bg = "#272a3f", fg = "#119bb7" })
hi(0, "BufferInactiveIndex", { bg = "#272a3f", fg = "#737aa2" })
hi(0, "BufferInactiveMod", { bg = "#272a3f", fg = "#d3a66a" })
hi(0, "BufferInactiveSign", { bg = "#272a3f", fg = "#222436" })
hi(0, "BufferInactiveTarget", { bg = "#272a3f", fg = "#ff757f" })
hi(0, "BufferInactiveWARN", { bg = "#272a3f", fg = "#d3a66a" })
hi(0, "BufferLineIndicatorSelected", { fg = "#6fbcff" })
hi(0, "BufferOffset", { bg = "#1e2030", fg = "#737aa2" })
hi(0, "BufferTabpageFill", { bg = "#2c3048", fg = "#737aa2" })
hi(0, "BufferTabpages", { bg = "#1e2030" })
hi(0, "BufferVisible", { bg = "#1e2030", fg = "#c8d3f5" })
hi(0, "BufferVisibleERROR", { bg = "#1e2030", fg = "#c53b53" })
hi(0, "BufferVisibleHINT", { bg = "#1e2030", fg = "#4fd6be" })
hi(0, "BufferVisibleINFO", { bg = "#1e2030", fg = "#0db9d7" })
hi(0, "BufferVisibleIndex", { bg = "#1e2030", fg = "#0db9d7" })
hi(0, "BufferVisibleMod", { bg = "#1e2030", fg = "#ffc777" })
hi(0, "BufferVisibleSign", { bg = "#1e2030", fg = "#0db9d7" })
hi(0, "BufferVisibleTarget", { bg = "#1e2030", fg = "#ff757f" })
hi(0, "BufferVisibleWARN", { bg = "#1e2030", fg = "#ffc777" })
hi(0, "Character", { fg = "#c3e88d" })
hi(0, "CmpDocumentation", { bg = "#1e2030", fg = "#c8d3f5" })
hi(0, "CmpDocumentationBorder", { bg = "#1e2030", fg = "#589ed7" })
hi(0, "CmpGhostText", { fg = "#444a73" })
hi(0, "CmpItemAbbr", { fg = "#c8d3f5" })
hi(0, "CmpItemAbbrDefault", { fg = "#c8d3f5" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#3b4261", strikethrough = true })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#636da6" })
hi(0, "CmpItemAbbrMatch", { fg = "#65bcff" })
hi(0, "CmpItemAbbrMatchDefault", { fg = "#c8d3f5" })
hi(0, "CmpItemAbbrMatchFuzzy", { fg = "#65bcff" })
hi(0, "CmpItemAbbrMatchFuzzyDefault", { fg = "#c8d3f5" })
hi(0, "CmpItemKind", { fg = "#65bcff" })
hi(0, "CmpItemKindArray", { link = "LspKindArray" })
hi(0, "CmpItemKindBoolean", { link = "LspKindBoolean" })
hi(0, "CmpItemKindClass", { link = "LspKindClass" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindCodeium", { fg = "#4fd6be" })
hi(0, "CmpItemKindColor", { link = "LspKindColor" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstant", { link = "LspKindConstant" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructor", { link = "LspKindConstructor" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindCopilot", { fg = "#4fd6be" })
hi(0, "CmpItemKindDefault", { fg = "#65bcff" })
hi(0, "CmpItemKindEnum", { link = "LspKindEnum" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMember", { link = "LspKindEnumMember" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEvent", { link = "LspKindEvent" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindField", { link = "LspKindField" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFile", { link = "LspKindFile" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolder", { link = "LspKindFolder" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunction", { link = "LspKindFunction" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterface", { link = "LspKindInterface" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKey", { link = "LspKindKey" })
hi(0, "CmpItemKindKeyword", { link = "LspKindKeyword" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethod", { link = "LspKindMethod" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModule", { link = "LspKindModule" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindNamespace", { link = "LspKindNamespace" })
hi(0, "CmpItemKindNull", { link = "LspKindNull" })
hi(0, "CmpItemKindNumber", { link = "LspKindNumber" })
hi(0, "CmpItemKindObject", { link = "LspKindObject" })
hi(0, "CmpItemKindOperator", { link = "LspKindOperator" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindPackage", { link = "LspKindPackage" })
hi(0, "CmpItemKindProperty", { link = "LspKindProperty" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReference", { link = "LspKindReference" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippet", { link = "LspKindSnippet" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindString", { link = "LspKindString" })
hi(0, "CmpItemKindStruct", { link = "LspKindStruct" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTabNine", { fg = "#4fd6be" })
hi(0, "CmpItemKindText", { link = "LspKindText" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameter", { link = "LspKindTypeParameter" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnit", { link = "LspKindUnit" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValue", { link = "LspKindValue" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariable", { link = "LspKindVariable" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "CmpItemMenu", { fg = "#636da6" })
hi(0, "CmpItemMenuDefault", { fg = "#c8d3f5" })
hi(0, "CodeBlock", { bg = "#1e2030" })
hi(0, "ColorColumn", { bg = "#1b1d2b" })
hi(0, "Comment", { fg = "#636da6" })
hi(0, "Conceal", { fg = "#737aa2" })
hi(0, "Constant", { fg = "#ff966c" })
hi(0, "CurSearch", { link = "IncSearch" })
hi(0, "Cursor", { bg = "#c8d3f5", fg = "#222436" })
hi(0, "CursorColumn", { bg = "#2f334d" })
hi(0, "CursorIM", { bg = "#c8d3f5", fg = "#222436" })
hi(0, "CursorLine", { bg = "#2f334d" })
hi(0, "CursorLineNr", { fg = "#737aa2" })
hi(0, "DapStoppedLine", { bg = "#38343d" })
hi(0, "DashboardCenter", { fg = "#c099ff" })
hi(0, "DashboardDesc", { fg = "#86e1fc" })
hi(0, "DashboardFooter", { fg = "#65bcff" })
hi(0, "DashboardHeader", { fg = "#82aaff" })
hi(0, "DashboardIcon", { bold = true, fg = "#86e1fc" })
hi(0, "DashboardKey", { fg = "#ff966c" })
hi(0, "DashboardShortCut", { fg = "#86e1fc" })
hi(0, "Debug", { fg = "#ff966c" })
hi(0, "DefinitionCount", { fg = "#fca7ea" })
hi(0, "DefinitionIcon", { fg = "#82aaff" })
hi(0, "DiagnosticError", { fg = "#c53b53" })
hi(0, "DiagnosticHint", { fg = "#4fd6be" })
hi(0, "DiagnosticInfo", { fg = "#0db9d7" })
hi(0, "DiagnosticInformation", { link = "DiagnosticInfo" })
hi(0, "DiagnosticUnderlineError", { sp = "#c53b53", undercurl = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#4fd6be", undercurl = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#0db9d7", undercurl = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#ffc777", undercurl = true })
hi(0, "DiagnosticUnnecessary", { fg = "#444a73" })
hi(0, "DiagnosticVirtualTextError", { bg = "#322639", fg = "#c53b53" })
hi(0, "DiagnosticVirtualTextHint", { bg = "#273644", fg = "#4fd6be" })
hi(0, "DiagnosticVirtualTextInfo", { bg = "#203346", fg = "#0db9d7" })
hi(0, "DiagnosticVirtualTextWarn", { bg = "#38343d", fg = "#ffc777" })
hi(0, "DiagnosticWarn", { fg = "#ffc777" })
hi(0, "DiagnosticWarning", { link = "DiagnosticWarn" })
hi(0, "DiffAdd", { bg = "#273849" })
hi(0, "DiffChange", { bg = "#252a3f" })
hi(0, "DiffDelete", { bg = "#3a273a" })
hi(0, "DiffText", { bg = "#394b70" })
hi(0, "Directory", { fg = "#82aaff" })
hi(0, "EndOfBuffer", {})
hi(0, "Error", { fg = "#c53b53" })
hi(0, "ErrorMsg", { fg = "#c53b53" })
hi(0, "FernBranchText", { fg = "#82aaff" })
hi(0, "FlashBackdrop", { fg = "#545c7e" })
hi(0, "FlashLabel", { bg = "#ff007c", bold = true, fg = "#c8d3f5" })
hi(0, "FloatBorder", { bg = "#1e2030", fg = "#589ed7" })
hi(0, "FloatTitle", { bg = "#1e2030", fg = "#589ed7" })
hi(0, "FoldColumn", { fg = "#636da6" })
hi(0, "Folded", { bg = "#3b4261", fg = "#82aaff" })
hi(0, "Foo", { bg = "#ff007c", fg = "#c8d3f5" })
hi(0, "Function", { fg = "#82aaff" })
hi(0, "GitGutterAdd", { fg = "#c3e88d" })
hi(0, "GitGutterAddLineNr", { fg = "#c3e88d" })
hi(0, "GitGutterChange", { fg = "#6fbcff" })
hi(0, "GitGutterChangeLineNr", { fg = "#6fbcff" })
hi(0, "GitGutterDelete", { fg = "#ff757f" })
hi(0, "GitGutterDeleteLineNr", { fg = "#ff757f" })
hi(0, "GitSignsAdd", { fg = "#c3e88d" })
hi(0, "GitSignsAddInline", { reverse = true })
hi(0, "GitSignsAddLn", { bg = "#273849" })
hi(0, "GitSignsAddLnInline", { reverse = true })
hi(0, "GitSignsAddNr", { fg = "#c3e88d" })
hi(0, "GitSignsAddPreview", { bg = "#273849" })
hi(0, "GitSignsChange", { fg = "#6fbcff" })
hi(0, "GitSignsChangeInline", { reverse = true })
hi(0, "GitSignsChangeLn", { bg = "#252a3f" })
hi(0, "GitSignsChangeLnInline", { reverse = true })
hi(0, "GitSignsChangeNr", { fg = "#6fbcff" })
hi(0, "GitSignsChangedelete", { fg = "#6fbcff" })
hi(0, "GitSignsChangedeleteLn", { bg = "#252a3f" })
hi(0, "GitSignsChangedeleteNr", { fg = "#6fbcff" })
hi(0, "GitSignsCurrentLineBlame", { fg = "#545c7e" })
hi(0, "GitSignsDelete", { fg = "#ff757f" })
hi(0, "GitSignsDeleteInline", { reverse = true })
hi(0, "GitSignsDeleteLnInline", { reverse = true })
hi(0, "GitSignsDeleteNr", { fg = "#ff757f" })
hi(0, "GitSignsDeletePreview", { bg = "#3a273a" })
hi(0, "GitSignsDeleteVirtLn", { bg = "#3a273a" })
hi(0, "GitSignsDeleteVirtLnInLine", { reverse = true })
hi(0, "GitSignsStagedAdd", { bg = "#00008b" })
hi(0, "GitSignsStagedAddLn", { bg = "#00008b" })
hi(0, "GitSignsStagedAddNr", { bg = "#00008b" })
hi(0, "GitSignsStagedChange", { bg = "#8b008b" })
hi(0, "GitSignsStagedChangeLn", { bg = "#8b008b" })
hi(0, "GitSignsStagedChangeNr", { bg = "#8b008b" })
hi(0, "GitSignsStagedChangedelete", { bg = "#8b008b" })
hi(0, "GitSignsStagedChangedeleteLn", { bg = "#8b008b" })
hi(0, "GitSignsStagedChangedeleteNr", { bg = "#8b008b" })
hi(0, "GitSignsStagedDelete", { bg = "#008b8b", fg = "#00007f" })
hi(0, "GitSignsStagedDeleteNr", { bg = "#008b8b", fg = "#00007f" })
hi(0, "GitSignsStagedTopdelete", { bg = "#008b8b", fg = "#00007f" })
hi(0, "GitSignsStagedTopdeleteNr", { bg = "#008b8b", fg = "#00007f" })
hi(0, "GitSignsTopdelete", { fg = "#ff757f" })
hi(0, "GitSignsTopdeleteNr", { fg = "#ff757f" })
hi(0, "GitSignsUntracked", { fg = "#c3e88d" })
hi(0, "GitSignsUntrackedLn", { bg = "#273849" })
hi(0, "GitSignsUntrackedNr", { fg = "#c3e88d" })
hi(0, "GitSignsVirtLnum", { bg = "#3a273a" })
hi(0, "GlyphPalette1", { fg = "#c53b53" })
hi(0, "GlyphPalette2", { fg = "#c3e88d" })
hi(0, "GlyphPalette3", { fg = "#ffc777" })
hi(0, "GlyphPalette4", { fg = "#82aaff" })
hi(0, "GlyphPalette6", { fg = "#4fd6be" })
hi(0, "GlyphPalette7", { fg = "#c8d3f5" })
hi(0, "GlyphPalette9", { fg = "#ff757f" })
hi(0, "Headline", { link = "Headline1" })
hi(0, "Headline1", { bg = "#272b40" })
hi(0, "Headline2", { bg = "#2d2c39" })
hi(0, "Headline3", { bg = "#2a2e3a" })
hi(0, "Headline4", { bg = "#242d3d" })
hi(0, "Headline5", { bg = "#2a2a40" })
hi(0, "Headline6", { bg = "#2d2b3f" })
hi(0, "Hlargs", { fg = "#ffc777" })
hi(0, "HopNextKey", { bold = true, fg = "#ff007c" })
hi(0, "HopNextKey1", { bold = true, fg = "#0db9d7" })
hi(0, "HopNextKey2", { fg = "#157d97" })
hi(0, "HopUnmatched", { fg = "#545c7e" })
hi(0, "IblIndent", { fg = "#3b4261", nocombine = true })
hi(0, "IblScope", { fg = "#fca7ea", nocombine = true })
hi(0, "Identifier", { fg = "#c099ff" })
hi(0, "IlluminatedWordRead", { bg = "#3b4261" })
hi(0, "IlluminatedWordText", { bg = "#3b4261" })
hi(0, "IlluminatedWordWrite", { bg = "#3b4261" })
hi(0, "IncSearch", { bg = "#ff966c", fg = "#1b1d2b" })
hi(0, "IndentBlanklineChar", { fg = "#3b4261", nocombine = true })
hi(0, "IndentBlanklineContextChar", { fg = "#fca7ea", nocombine = true })
hi(0, "Italic", { fg = "#c8d3f5", italic = true })
hi(0, "Keyword", { fg = "#86e1fc" })
hi(0, "LazyProgressDone", { bold = true, fg = "#ff007c" })
hi(0, "LazyProgressTodo", { bold = true, fg = "#3b4261" })
hi(0, "LeapBackdrop", { fg = "#545c7e" })
hi(0, "LeapLabelPrimary", { bold = true, fg = "#ff007c" })
hi(0, "LeapLabelSecondary", { bold = true, fg = "#4fd6be" })
hi(0, "LeapMatch", { bg = "#ff007c", bold = true, fg = "#c8d3f5" })
hi(0, "LightspeedGreyWash", { fg = "#545c7e" })
hi(0, "LightspeedLabel", { bold = true, fg = "#ff007c", underline = true })
hi(0, "LightspeedLabelDistant", { bold = true, fg = "#4fd6be", underline = true })
hi(0, "LightspeedLabelDistantOverlapped", { fg = "#41a6b5", underline = true })
hi(0, "LightspeedLabelOverlapped", { fg = "#ff007c", underline = true })
hi(0, "LightspeedMaskedChar", { fg = "#ff966c" })
hi(0, "LightspeedOneCharMatch", { bg = "#ff007c", bold = true, fg = "#c8d3f5" })
hi(0, "LightspeedPendingOpArea", { bg = "#ff007c", fg = "#c8d3f5" })
hi(0, "LightspeedShortcut", { bg = "#ff007c", bold = true, fg = "#c8d3f5", underline = true })
hi(0, "LightspeedUnlabeledMatch", { bold = true, fg = "#0db9d7" })
hi(0, "LineNr", { fg = "#828bb8" })
hi(0, "LspCodeLens", { fg = "#636da6" })
hi(0, "LspFloatWinBorder", { fg = "#589ed7" })
hi(0, "LspFloatWinNormal", { bg = "#1e2030" })
hi(0, "LspInfoBorder", { bg = "#1e2030", fg = "#589ed7" })
hi(0, "LspInfoFiletype", { fg = "#65bcff" })
hi(0, "LspInfoList", { fg = "#82aaff" })
hi(0, "LspInfoTip", { fg = "#636da6" })
hi(0, "LspInfoTitle", { bold = true, fg = "#82aaff" })
hi(0, "LspInlayHint", { bg = "#24283c", fg = "#545c7e" })
hi(0, "LspKindArray", { link = "@punctuation.bracket" })
hi(0, "LspKindBoolean", { link = "@boolean" })
hi(0, "LspKindClass", { link = "@type" })
hi(0, "LspKindColor", { link = "Special" })
hi(0, "LspKindConstant", { link = "@constant" })
hi(0, "LspKindConstructor", { link = "@constructor" })
hi(0, "LspKindEnum", { link = "@lsp.type.enum" })
hi(0, "LspKindEnumMember", { link = "@lsp.type.enumMember" })
hi(0, "LspKindEvent", { link = "Special" })
hi(0, "LspKindField", { link = "@variable.member" })
hi(0, "LspKindFile", { link = "Normal" })
hi(0, "LspKindFolder", { link = "Directory" })
hi(0, "LspKindFunction", { link = "@function" })
hi(0, "LspKindInterface", { link = "@lsp.type.interface" })
hi(0, "LspKindKey", { link = "@variable.member" })
hi(0, "LspKindKeyword", { link = "@lsp.type.keyword" })
hi(0, "LspKindMethod", { link = "@function.method" })
hi(0, "LspKindModule", { link = "@module" })
hi(0, "LspKindNamespace", { link = "@module" })
hi(0, "LspKindNull", { link = "@constant.builtin" })
hi(0, "LspKindNumber", { link = "@number" })
hi(0, "LspKindObject", { link = "@constant" })
hi(0, "LspKindOperator", { link = "@operator" })
hi(0, "LspKindPackage", { link = "@module" })
hi(0, "LspKindProperty", { link = "@property" })
hi(0, "LspKindReference", { link = "@markup.link" })
hi(0, "LspKindSnippet", { link = "Conceal" })
hi(0, "LspKindString", { link = "@string" })
hi(0, "LspKindStruct", { link = "@lsp.type.struct" })
hi(0, "LspKindText", { link = "@markup" })
hi(0, "LspKindTypeParameter", { link = "@lsp.type.typeParameter" })
hi(0, "LspKindUnit", { link = "@lsp.type.struct" })
hi(0, "LspKindValue", { link = "@string" })
hi(0, "LspKindVariable", { link = "@variable" })
hi(0, "LspReferenceRead", { bg = "#3b4261" })
hi(0, "LspReferenceText", { bg = "#3b4261" })
hi(0, "LspReferenceWrite", { bg = "#3b4261" })
hi(0, "LspSagaBorderTitle", { fg = "#86e1fc" })
hi(0, "LspSagaCodeActionBorder", { fg = "#82aaff" })
hi(0, "LspSagaCodeActionContent", { fg = "#fca7ea" })
hi(0, "LspSagaCodeActionTitle", { fg = "#65bcff" })
hi(0, "LspSagaDefPreviewBorder", { fg = "#c3e88d" })
hi(0, "LspSagaFinderSelection", { fg = "#2d3f76" })
hi(0, "LspSagaHoverBorder", { fg = "#82aaff" })
hi(0, "LspSagaRenameBorder", { fg = "#c3e88d" })
hi(0, "LspSagaSignatureHelpBorder", { fg = "#ff757f" })
hi(0, "LspSignatureActiveParameter", { bg = "#262f50", bold = true })
hi(0, "MatchParen", { bold = true, fg = "#ff966c" })
hi(0, "MiniCompletionActiveParameter", { underline = true })
hi(0, "MiniCursorword", { bg = "#3b4261" })
hi(0, "MiniCursorwordCurrent", { bg = "#3b4261" })
hi(0, "MiniDiffSignAdd", { fg = "#c3e88d" })
hi(0, "MiniDiffSignChange", { fg = "#6fbcff" })
hi(0, "MiniDiffSignDelete", { fg = "#ff757f" })
hi(0, "MiniHipatternsFixme", { fg = "#c53b53" })
hi(0, "MiniHipatternsHack", { fg = "#ffc777" })
hi(0, "MiniHipatternsNote", { fg = "#4fd6be" })
hi(0, "MiniHipatternsTodo", { fg = "#0db9d7" })
hi(0, "MiniIndentscopePrefix", { nocombine = true })
hi(0, "MiniIndentscopeSymbol", { fg = "#65bcff", nocombine = true })
hi(0, "MiniJump", { bg = "#ff007c", fg = "#ffffff" })
hi(0, "MiniJump2dSpot", { bold = true, fg = "#ff007c", nocombine = true })
hi(0, "MiniStarterCurrent", { nocombine = true })
hi(0, "MiniStarterFooter", { fg = "#ffc777", italic = true })
hi(0, "MiniStarterHeader", { fg = "#82aaff" })
hi(0, "MiniStarterInactive", { fg = "#636da6" })
hi(0, "MiniStarterItem", { fg = "#c8d3f5" })
hi(0, "MiniStarterItemBullet", { fg = "#589ed7" })
hi(0, "MiniStarterItemPrefix", { fg = "#ffc777" })
hi(0, "MiniStarterQuery", { fg = "#0db9d7" })
hi(0, "MiniStarterSection", { fg = "#65bcff" })
hi(0, "MiniStatuslineDevinfo", { bg = "#2f334d", fg = "#828bb8" })
hi(0, "MiniStatuslineFileinfo", { bg = "#2f334d", fg = "#828bb8" })
hi(0, "MiniStatuslineFilename", { bg = "#3b4261", fg = "#828bb8" })
hi(0, "MiniStatuslineInactive", { bg = "#1e2030", fg = "#82aaff" })
hi(0, "MiniStatuslineModeCommand", { bg = "#ffc777", bold = true, fg = "#1b1d2b" })
hi(0, "MiniStatuslineModeInsert", { bg = "#c3e88d", bold = true, fg = "#1b1d2b" })
hi(0, "MiniStatuslineModeNormal", { bg = "#82aaff", bold = true, fg = "#1b1d2b" })
hi(0, "MiniStatuslineModeOther", { bg = "#4fd6be", bold = true, fg = "#1b1d2b" })
hi(0, "MiniStatuslineModeReplace", { bg = "#ff757f", bold = true, fg = "#1b1d2b" })
hi(0, "MiniStatuslineModeVisual", { bg = "#c099ff", bold = true, fg = "#1b1d2b" })
hi(0, "MiniSurround", { bg = "#ff966c", fg = "#1b1d2b" })
hi(0, "MiniTablineCurrent", { bg = "#3b4261", fg = "#c8d3f5" })
hi(0, "MiniTablineFill", { bg = "#1b1d2b" })
hi(0, "MiniTablineHidden", { bg = "#1e2030", fg = "#737aa2" })
hi(0, "MiniTablineModifiedCurrent", { bg = "#3b4261", fg = "#ffc777" })
hi(0, "MiniTablineModifiedHidden", { bg = "#1e2030", fg = "#bd9664" })
hi(0, "MiniTablineModifiedVisible", { bg = "#1e2030", fg = "#ffc777" })
hi(0, "MiniTablineTabpagesection", { bg = "#1e2030" })
hi(0, "MiniTablineVisible", { bg = "#1e2030", fg = "#c8d3f5" })
hi(0, "MiniTestEmphasis", { bold = true })
hi(0, "MiniTestFail", { bold = true, fg = "#ff757f" })
hi(0, "MiniTestPass", { bold = true, fg = "#c3e88d" })
hi(0, "MiniTrailspace", { bg = "#ff757f" })
hi(0, "ModeMsg", { bold = true, fg = "#828bb8" })
hi(0, "MoreMsg", { fg = "#82aaff" })
hi(0, "MsgArea", { fg = "#828bb8" })
hi(0, "NavicIconsArray", { link = "LspKindArray" })
hi(0, "NavicIconsBoolean", { link = "LspKindBoolean" })
hi(0, "NavicIconsClass", { link = "LspKindClass" })
hi(0, "NavicIconsColor", { link = "LspKindColor" })
hi(0, "NavicIconsConstant", { link = "LspKindConstant" })
hi(0, "NavicIconsConstructor", { link = "LspKindConstructor" })
hi(0, "NavicIconsEnum", { link = "LspKindEnum" })
hi(0, "NavicIconsEnumMember", { link = "LspKindEnumMember" })
hi(0, "NavicIconsEvent", { link = "LspKindEvent" })
hi(0, "NavicIconsField", { link = "LspKindField" })
hi(0, "NavicIconsFile", { link = "LspKindFile" })
hi(0, "NavicIconsFolder", { link = "LspKindFolder" })
hi(0, "NavicIconsFunction", { link = "LspKindFunction" })
hi(0, "NavicIconsInterface", { link = "LspKindInterface" })
hi(0, "NavicIconsKey", { link = "LspKindKey" })
hi(0, "NavicIconsKeyword", { link = "LspKindKeyword" })
hi(0, "NavicIconsMethod", { link = "LspKindMethod" })
hi(0, "NavicIconsModule", { link = "LspKindModule" })
hi(0, "NavicIconsNamespace", { link = "LspKindNamespace" })
hi(0, "NavicIconsNull", { link = "LspKindNull" })
hi(0, "NavicIconsNumber", { link = "LspKindNumber" })
hi(0, "NavicIconsObject", { link = "LspKindObject" })
hi(0, "NavicIconsOperator", { link = "LspKindOperator" })
hi(0, "NavicIconsPackage", { link = "LspKindPackage" })
hi(0, "NavicIconsProperty", { link = "LspKindProperty" })
hi(0, "NavicIconsReference", { link = "LspKindReference" })
hi(0, "NavicIconsSnippet", { link = "LspKindSnippet" })
hi(0, "NavicIconsString", { link = "LspKindString" })
hi(0, "NavicIconsStruct", { link = "LspKindStruct" })
hi(0, "NavicIconsText", { link = "LspKindText" })
hi(0, "NavicIconsTypeParameter", { link = "LspKindTypeParameter" })
hi(0, "NavicIconsUnit", { link = "LspKindUnit" })
hi(0, "NavicIconsValue", { link = "LspKindValue" })
hi(0, "NavicIconsVariable", { link = "LspKindVariable" })
hi(0, "NavicSeparator", { fg = "#c8d3f5" })
hi(0, "NavicText", { fg = "#c8d3f5" })
hi(0, "NeoTreeDimText", { fg = "#3b4261" })
hi(0, "NeoTreeNormal", { bg = "#1e2030", fg = "#828bb8" })
hi(0, "NeoTreeNormalNC", { bg = "#1e2030", fg = "#828bb8" })
hi(0, "NeogitBranch", { fg = "#c099ff" })
hi(0, "NeogitDiffAddHighlight", { bg = "#273849", fg = "#c3e88d" })
hi(0, "NeogitDiffContextHighlight", { bg = "#2f334c", fg = "#828bb8" })
hi(0, "NeogitDiffDeleteHighlight", { bg = "#3a273a", fg = "#ff757f" })
hi(0, "NeogitHunkHeader", { bg = "#2f334d", fg = "#c8d3f5" })
hi(0, "NeogitHunkHeaderHighlight", { bg = "#3b4261", fg = "#82aaff" })
hi(0, "NeogitRemote", { fg = "#fca7ea" })
hi(0, "NeotestAdapterName", { bold = true, fg = "#fca7ea" })
hi(0, "NeotestBorder", { fg = "#82aaff" })
hi(0, "NeotestDir", { fg = "#82aaff" })
hi(0, "NeotestExpandMarker", { fg = "#828bb8" })
hi(0, "NeotestFailed", { fg = "#ff757f" })
hi(0, "NeotestFile", { fg = "#4fd6be" })
hi(0, "NeotestFocused", { fg = "#ffc777" })
hi(0, "NeotestIndent", { fg = "#828bb8" })
hi(0, "NeotestMarked", { fg = "#82aaff" })
hi(0, "NeotestNamespace", { fg = "#41a6b5" })
hi(0, "NeotestPassed", { fg = "#c3e88d" })
hi(0, "NeotestRunning", { fg = "#ffc777" })
hi(0, "NeotestSkipped", { fg = "#82aaff" })
hi(0, "NeotestTarget", { fg = "#82aaff" })
hi(0, "NeotestTest", { fg = "#828bb8" })
hi(0, "NeotestWinSelect", { fg = "#82aaff" })
hi(0, "NoiceCompletionItemKindArray", { link = "LspKindArray" })
hi(0, "NoiceCompletionItemKindBoolean", { link = "LspKindBoolean" })
hi(0, "NoiceCompletionItemKindClass", { link = "LspKindClass" })
hi(0, "NoiceCompletionItemKindColor", { link = "LspKindColor" })
hi(0, "NoiceCompletionItemKindConstant", { link = "LspKindConstant" })
hi(0, "NoiceCompletionItemKindConstructor", { link = "LspKindConstructor" })
hi(0, "NoiceCompletionItemKindDefault", { fg = "#828bb8" })
hi(0, "NoiceCompletionItemKindEnum", { link = "LspKindEnum" })
hi(0, "NoiceCompletionItemKindEnumMember", { link = "LspKindEnumMember" })
hi(0, "NoiceCompletionItemKindEvent", { link = "LspKindEvent" })
hi(0, "NoiceCompletionItemKindField", { link = "LspKindField" })
hi(0, "NoiceCompletionItemKindFile", { link = "LspKindFile" })
hi(0, "NoiceCompletionItemKindFolder", { link = "LspKindFolder" })
hi(0, "NoiceCompletionItemKindFunction", { link = "LspKindFunction" })
hi(0, "NoiceCompletionItemKindInterface", { link = "LspKindInterface" })
hi(0, "NoiceCompletionItemKindKey", { link = "LspKindKey" })
hi(0, "NoiceCompletionItemKindKeyword", { link = "LspKindKeyword" })
hi(0, "NoiceCompletionItemKindMethod", { link = "LspKindMethod" })
hi(0, "NoiceCompletionItemKindModule", { link = "LspKindModule" })
hi(0, "NoiceCompletionItemKindNamespace", { link = "LspKindNamespace" })
hi(0, "NoiceCompletionItemKindNull", { link = "LspKindNull" })
hi(0, "NoiceCompletionItemKindNumber", { link = "LspKindNumber" })
hi(0, "NoiceCompletionItemKindObject", { link = "LspKindObject" })
hi(0, "NoiceCompletionItemKindOperator", { link = "LspKindOperator" })
hi(0, "NoiceCompletionItemKindPackage", { link = "LspKindPackage" })
hi(0, "NoiceCompletionItemKindProperty", { link = "LspKindProperty" })
hi(0, "NoiceCompletionItemKindReference", { link = "LspKindReference" })
hi(0, "NoiceCompletionItemKindSnippet", { link = "LspKindSnippet" })
hi(0, "NoiceCompletionItemKindString", { link = "LspKindString" })
hi(0, "NoiceCompletionItemKindStruct", { link = "LspKindStruct" })
hi(0, "NoiceCompletionItemKindText", { link = "LspKindText" })
hi(0, "NoiceCompletionItemKindTypeParameter", { link = "LspKindTypeParameter" })
hi(0, "NoiceCompletionItemKindUnit", { link = "LspKindUnit" })
hi(0, "NoiceCompletionItemKindValue", { link = "LspKindValue" })
hi(0, "NoiceCompletionItemKindVariable", { link = "LspKindVariable" })
hi(0, "NonText", { fg = "#545c7e" })
hi(0, "Normal", { fg = "#c8d3f5" })
hi(0, "NormalFloat", { bg = "#1e2030", fg = "#c8d3f5" })
hi(0, "NormalNC", { fg = "#c8d3f5" })
hi(0, "NormalSB", { bg = "#1e2030", fg = "#828bb8" })
hi(0, "NotifyBackground", { bg = "#222436", fg = "#c8d3f5" })
hi(0, "NotifyDEBUGBody", { fg = "#c8d3f5" })
hi(0, "NotifyDEBUGBorder", { fg = "#363a58" })
hi(0, "NotifyDEBUGIcon", { fg = "#636da6" })
hi(0, "NotifyDEBUGTitle", { fg = "#636da6" })
hi(0, "NotifyERRORBody", { fg = "#c8d3f5" })
hi(0, "NotifyERRORBorder", { fg = "#532b3f" })
hi(0, "NotifyERRORIcon", { fg = "#c53b53" })
hi(0, "NotifyERRORTitle", { fg = "#c53b53" })
hi(0, "NotifyINFOBody", { fg = "#c8d3f5" })
hi(0, "NotifyINFOBorder", { fg = "#1c5166" })
hi(0, "NotifyINFOIcon", { fg = "#0db9d7" })
hi(0, "NotifyINFOTitle", { fg = "#0db9d7" })
hi(0, "NotifyTRACEBody", { fg = "#c8d3f5" })
hi(0, "NotifyTRACEBorder", { fg = "#634b6c" })
hi(0, "NotifyTRACEIcon", { fg = "#fca7ea" })
hi(0, "NotifyTRACETitle", { fg = "#fca7ea" })
hi(0, "NotifyWARNBody", { fg = "#c8d3f5" })
hi(0, "NotifyWARNBorder", { fg = "#64554a" })
hi(0, "NotifyWARNIcon", { fg = "#ffc777" })
hi(0, "NotifyWARNTitle", { fg = "#ffc777" })
hi(0, "NvimTreeFolderIcon", { fg = "#82aaff" })
hi(0, "NvimTreeGitDeleted", { fg = "#ff757f" })
hi(0, "NvimTreeGitDirty", { fg = "#6fbcff" })
hi(0, "NvimTreeGitNew", { fg = "#c3e88d" })
hi(0, "NvimTreeImageFile", { fg = "#828bb8" })
hi(0, "NvimTreeIndentMarker", { fg = "#3b4261" })
hi(0, "NvimTreeNormal", { bg = "#1e2030", fg = "#828bb8" })
hi(0, "NvimTreeNormalNC", { bg = "#1e2030", fg = "#828bb8" })
hi(0, "NvimTreeOpenedFile", { bg = "#2f334d" })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#82aaff" })
hi(0, "NvimTreeSpecialFile", { fg = "#fca7ea", underline = true })
hi(0, "NvimTreeSymlink", { fg = "#82aaff" })
hi(0, "NvimTreeWinSeparator", { bg = "#1e2030", fg = "#1e2030" })
hi(0, "Operator", { fg = "#89ddff" })
hi(0, "Pmenu", { bg = "#1e2030", fg = "#c8d3f5" })
hi(0, "PmenuSbar", { bg = "#292b3a" })
hi(0, "PmenuSel", { bg = "#363c58" })
hi(0, "PmenuThumb", { bg = "#3b4261" })
hi(0, "PounceAccept", { bg = "#de940b", bold = true, ctermbg = 224, ctermfg = 0, fg = "#111111" })
hi(0, "PounceAcceptBest", { bg = "#03cafc", bold = true, ctermbg = 14, ctermfg = 0, fg = "#111111" })
hi(0, "PounceCursor", { bg = "#ff0000", bold = true, ctermbg = 9, ctermfg = 0, fg = "#111111" })
hi(0, "PounceCursorAccept", { bg = "#de940b", bold = true, ctermbg = 224, ctermfg = 0, fg = "#111111" })
hi(0, "PounceCursorAcceptBest", { bg = "#03cafc", bold = true, ctermbg = 14, ctermfg = 0, fg = "#111111" })
hi(0, "PounceCursorGap", { bg = "#aa0000", bold = true, ctermbg = 1, ctermfg = 0, fg = "#111111" })
hi(0, "PounceGap", { bg = "#00aa00", bold = true, ctermbg = 2, ctermfg = 0, fg = "#555555" })
hi(0, "PounceMatch", { bg = "#11dd11", bold = true, ctermbg = 10, ctermfg = 0, fg = "#555555" })
hi(0, "PounceUnmatched", {})
hi(0, "PreProc", { fg = "#86e1fc" })
hi(0, "Question", { fg = "#82aaff" })
hi(0, "QuickFixLine", { bg = "#2d3f76", bold = true })
hi(0, "RainbowDelimiterBlue", { fg = "#82aaff" })
hi(0, "RainbowDelimiterCyan", { fg = "#86e1fc" })
hi(0, "RainbowDelimiterGreen", { fg = "#c3e88d" })
hi(0, "RainbowDelimiterOrange", { fg = "#ff966c" })
hi(0, "RainbowDelimiterRed", { fg = "#ff757f" })
hi(0, "RainbowDelimiterViolet", { fg = "#fca7ea" })
hi(0, "RainbowDelimiterYellow", { fg = "#ffc777" })
hi(0, "ReferencesCount", { fg = "#fca7ea" })
hi(0, "ReferencesIcon", { fg = "#82aaff" })
hi(0, "ScrollbarError", { fg = "#c53b53" })
hi(0, "ScrollbarErrorHandle", { bg = "#2f334d", fg = "#c53b53" })
hi(0, "ScrollbarHandle", { bg = "#2f334d" })
hi(0, "ScrollbarHint", { fg = "#4fd6be" })
hi(0, "ScrollbarHintHandle", { bg = "#2f334d", fg = "#4fd6be" })
hi(0, "ScrollbarInfo", { fg = "#0db9d7" })
hi(0, "ScrollbarInfoHandle", { bg = "#2f334d", fg = "#0db9d7" })
hi(0, "ScrollbarMisc", { fg = "#fca7ea" })
hi(0, "ScrollbarMiscHandle", { bg = "#2f334d", fg = "#fca7ea" })
hi(0, "ScrollbarSearch", { fg = "#ff966c" })
hi(0, "ScrollbarSearchHandle", { bg = "#2f334d", fg = "#ff966c" })
hi(0, "ScrollbarWarn", { fg = "#ffc777" })
hi(0, "ScrollbarWarnHandle", { bg = "#2f334d", fg = "#ffc777" })
hi(0, "Search", { bg = "#3e68d7", fg = "#c8d3f5" })
hi(0, "SignColumn", { fg = "#3b4261" })
hi(0, "SignColumnSB", { bg = "#1e2030", fg = "#3b4261" })
hi(0, "Sneak", { bg = "#c099ff", fg = "#2f334d" })
hi(0, "SneakScope", { bg = "#2d3f76" })
hi(0, "Special", { fg = "#65bcff" })
hi(0, "SpecialKey", { fg = "#545c7e" })
hi(0, "SpellBad", { sp = "#c53b53", undercurl = true })
hi(0, "SpellCap", { sp = "#ffc777", undercurl = true })
hi(0, "SpellLocal", { sp = "#0db9d7", undercurl = true })
hi(0, "SpellRare", { sp = "#4fd6be", undercurl = true })
hi(0, "Statement", { fg = "#c099ff" })
hi(0, "StatusLine", { bg = "#1e2030", fg = "#828bb8" })
hi(0, "StatusLineNC", { bg = "#1e2030", fg = "#3b4261" })
hi(0, "String", { fg = "#c3e88d" })
hi(0, "Substitute", { bg = "#ff757f", fg = "#1b1d2b" })
hi(0, "TSNodeKey", { bold = true, fg = "#ff007c" })
hi(0, "TSNodeUnmatched", { fg = "#545c7e" })
hi(0, "TSRainbowBlue", { fg = "#82aaff" })
hi(0, "TSRainbowCyan", { fg = "#86e1fc" })
hi(0, "TSRainbowGreen", { fg = "#c3e88d" })
hi(0, "TSRainbowOrange", { fg = "#ff966c" })
hi(0, "TSRainbowRed", { fg = "#ff757f" })
hi(0, "TSRainbowViolet", { fg = "#fca7ea" })
hi(0, "TSRainbowYellow", { fg = "#ffc777" })
hi(0, "TabLine", { bg = "#1e2030", fg = "#3b4261" })
hi(0, "TabLineFill", { bg = "#1b1d2b" })
hi(0, "TabLineSel", { bg = "#82aaff", fg = "#1b1d2b" })
hi(0, "TargetWord", { fg = "#86e1fc" })
hi(0, "TelescopeBorder", { bg = "#1e2030", fg = "#589ed7" })
hi(0, "TelescopeMatching", { fg = "#65bcff" })
hi(0, "TelescopeMultiIcon", { fg = "#c099ff" })
hi(0, "TelescopeMultiSelection", { fg = "#65bcff" })
hi(0, "TelescopeNormal", { bg = "#1e2030", fg = "#c8d3f5" })
hi(0, "TelescopePreviewBlock", { fg = "#ff966c" })
hi(0, "TelescopePreviewBorder", { bg = "#1e2030", fg = "#589ed7" })
hi(0, "TelescopePreviewCharDev", { fg = "#ff966c" })
hi(0, "TelescopePreviewDate", { fg = "#82aaff" })
hi(0, "TelescopePreviewDirectory", { fg = "#82aaff" })
hi(0, "TelescopePreviewExecute", { fg = "#c3e88d" })
hi(0, "TelescopePreviewGroup", { fg = "#ff966c" })
hi(0, "TelescopePreviewHyphen", { fg = "#545c7e" })
hi(0, "TelescopePreviewLine", { bg = "#2d3f76" })
hi(0, "TelescopePreviewLink", { fg = "#65bcff" })
hi(0, "TelescopePreviewMatch", { bg = "#3e68d7", fg = "#c8d3f5" })
hi(0, "TelescopePreviewMessage", { bg = "#1e2030", fg = "#c8d3f5" })
hi(0, "TelescopePreviewMessageFillchar", { bg = "#1e2030", fg = "#c8d3f5" })
hi(0, "TelescopePreviewNormal", { bg = "#1e2030", fg = "#c8d3f5" })
hi(0, "TelescopePreviewPipe", { fg = "#ff966c" })
hi(0, "TelescopePreviewRead", { fg = "#ff966c" })
hi(0, "TelescopePreviewSize", { fg = "#c3e88d" })
hi(0, "TelescopePreviewSocket", { fg = "#c099ff" })
hi(0, "TelescopePreviewSticky", { fg = "#86e1fc" })
hi(0, "TelescopePreviewTitle", { bg = "#1e2030", fg = "#589ed7" })
hi(0, "TelescopePreviewUser", { fg = "#ff966c" })
hi(0, "TelescopePreviewWrite", { fg = "#c099ff" })
hi(0, "TelescopePromptBorder", { bg = "#1e2030", fg = "#ff966c" })
hi(0, "TelescopePromptCounter", { fg = "#545c7e" })
hi(0, "TelescopePromptNormal", { bg = "#1e2030", fg = "#c8d3f5" })
hi(0, "TelescopePromptPrefix", { fg = "#c099ff" })
hi(0, "TelescopePromptTitle", { bg = "#1e2030", fg = "#ff966c" })
hi(0, "TelescopeResultsBorder", { bg = "#1e2030", fg = "#589ed7" })
hi(0, "TelescopeResultsClass", { fg = "#82aaff" })
hi(0, "TelescopeResultsComment", { fg = "#636da6" })
hi(0, "TelescopeResultsConstant", { fg = "#ff966c" })
hi(0, "TelescopeResultsDiffAdd", { bg = "#273849" })
hi(0, "TelescopeResultsDiffChange", { bg = "#252a3f" })
hi(0, "TelescopeResultsDiffDelete", { bg = "#3a273a" })
hi(0, "TelescopeResultsDiffUntracked", { fg = "#545c7e" })
hi(0, "TelescopeResultsField", { fg = "#82aaff" })
hi(0, "TelescopeResultsFunction", { fg = "#82aaff" })
hi(0, "TelescopeResultsIdentifier", { fg = "#c099ff" })
hi(0, "TelescopeResultsLineNr", { fg = "#828bb8" })
hi(0, "TelescopeResultsMethod", {})
hi(0, "TelescopeResultsNormal", { bg = "#1e2030", fg = "#c8d3f5" })
hi(0, "TelescopeResultsNumber", { fg = "#ff966c" })
hi(0, "TelescopeResultsOperator", { fg = "#89ddff" })
hi(0, "TelescopeResultsSpecialComment", { fg = "#65bcff" })
hi(0, "TelescopeResultsStruct", {})
hi(0, "TelescopeResultsTitle", { bg = "#1e2030", fg = "#589ed7" })
hi(0, "TelescopeResultsVariable", { fg = "#65bcff" })
hi(0, "TelescopeSelection", { bg = "#2d3f76" })
hi(0, "TelescopeSelectionCaret", { bg = "#2d3f76" })
hi(0, "TelescopeTitle", { bg = "#1e2030", fg = "#589ed7" })
hi(0, "Title", { bold = true, fg = "#82aaff" })
hi(0, "Todo", { bg = "#ffc777", fg = "#222436" })
hi(0, "TreesitterContext", { bg = "#363c58" })
hi(0, "TroubleCount", { bg = "#3b4261", fg = "#c099ff" })
hi(0, "TroubleNormal", { bg = "#1e2030", fg = "#c8d3f5" })
hi(0, "TroubleText", { fg = "#828bb8" })
hi(0, "Type", { fg = "#65bcff" })
hi(0, "Underlined", { underline = true })
hi(0, "VertSplit", { fg = "#1b1d2b" })
hi(0, "Visual", { bg = "#2d3f76" })
hi(0, "VisualNOS", { bg = "#2d3f76" })
hi(0, "WarningMsg", { fg = "#ffc777" })
hi(0, "WhichKey", { fg = "#86e1fc" })
hi(0, "WhichKeyDesc", { fg = "#c099ff" })
hi(0, "WhichKeyFloat", { bg = "#1e2030" })
hi(0, "WhichKeyGroup", { fg = "#82aaff" })
hi(0, "WhichKeySeparator", { fg = "#636da6" })
hi(0, "WhichKeySeperator", { fg = "#636da6" })
hi(0, "WhichKeyValue", { fg = "#737aa2" })
hi(0, "Whitespace", { fg = "#3b4261" })
hi(0, "WildMenu", { bg = "#2d3f76" })
hi(0, "WinBar", { link = "StatusLine" })
hi(0, "WinBarNC", { link = "StatusLineNC" })
hi(0, "WinSeparator", { bold = true, fg = "#1b1d2b" })
hi(0, "YankyPut", { link = "IncSearch" })
hi(0, "YankyYanked", { link = "IncSearch" })
hi(0, "debugBreakpoint", { bg = "#203346", fg = "#0db9d7" })
hi(0, "debugPC", { bg = "#1e2030" })
hi(0, "diffAdded", { fg = "#c3e88d" })
hi(0, "diffChanged", { fg = "#6fbcff" })
hi(0, "diffFile", { fg = "#82aaff" })
hi(0, "diffIndexLine", { fg = "#c099ff" })
hi(0, "diffLine", { fg = "#636da6" })
hi(0, "diffNewFile", { fg = "#ff966c" })
hi(0, "diffOldFile", { fg = "#ffc777" })
hi(0, "diffRemoved", { fg = "#ff757f" })
hi(0, "dosIniLabel", { link = "@property" })
hi(0, "healthError", { fg = "#c53b53" })
hi(0, "healthSuccess", { fg = "#4fd6be" })
hi(0, "healthWarning", { fg = "#ffc777" })
hi(0, "helpCommand", { bg = "#444a73", fg = "#82aaff" })
hi(0, "htmlH1", { bold = true, fg = "#c099ff" })
hi(0, "htmlH2", { bold = true, fg = "#82aaff" })
hi(0, "illuminatedCurWord", { bg = "#3b4261" })
hi(0, "illuminatedWord", { bg = "#3b4261" })
hi(0, "lCursor", { bg = "#c8d3f5", fg = "#222436" })
hi(0, "markdownCode", { fg = "#4fd6be" })
hi(0, "markdownCodeBlock", { fg = "#4fd6be" })
hi(0, "markdownH1", { bold = true, fg = "#c099ff" })
hi(0, "markdownH2", { bold = true, fg = "#82aaff" })
hi(0, "markdownHeadingDelimiter", { bold = true, fg = "#ff966c" })
hi(0, "markdownLinkText", { fg = "#82aaff", underline = true })
hi(0, "mkdCodeDelimiter", { bg = "#444a73", fg = "#c8d3f5" })
hi(0, "mkdCodeEnd", { bold = true, fg = "#4fd6be" })
hi(0, "mkdCodeStart", { bold = true, fg = "#4fd6be" })
hi(0, "qfFileName", { fg = "#82aaff" })
hi(0, "qfLineNr", { fg = "#737aa2" })
hi(0, "rainbowcol1", { fg = "#ff757f" })
hi(0, "rainbowcol2", { fg = "#ffc777" })
hi(0, "rainbowcol3", { fg = "#c3e88d" })
hi(0, "rainbowcol4", { fg = "#4fd6be" })
hi(0, "rainbowcol5", { fg = "#82aaff" })
hi(0, "rainbowcol6", { fg = "#c099ff" })
hi(0, "rainbowcol7", { fg = "#fca7ea" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#1b1d2b"
g.terminal_color_1 = "#ff757f"
g.terminal_color_2 = "#c3e88d"
g.terminal_color_3 = "#ffc777"
g.terminal_color_4 = "#82aaff"
g.terminal_color_5 = "#c099ff"
g.terminal_color_6 = "#86e1fc"
g.terminal_color_7 = "#828bb8"
g.terminal_color_8 = "#444a73"
g.terminal_color_9 = "#ff757f"
g.terminal_color_10 = "#c3e88d"
g.terminal_color_11 = "#ffc777"
g.terminal_color_12 = "#82aaff"
g.terminal_color_13 = "#c099ff"
g.terminal_color_14 = "#86e1fc"
g.terminal_color_15 = "#c8d3f5"
