local colors = {
    fg = "#c7cdd9",
    bg = "#232831",
    black = "#3b4252",
    skyblue = "#81a1c1",
    cyan = "#88c0d0",
    green = "#a3be8c",
    oceanblue = "#668aab",
    magenta = "#b48ead",
    orange = "#c9826b",
    red = "#bf616a",
    violet = "#bf88bc",
    white = "#e5e9f0",
    yellow = "#ebcb8b"
}

local hls = {
    ["AerialGuide"] = { fg = "#5a657d" },
    ["AerialLine"] = { link = "Search" },
    ["Bold"] = { bold = true },
    ["Boolean"] = { link = "Number" },
    ["BufferCurrent"] = { bg = "#7e8188", fg = "#cdcecf" },
    ["BufferCurrentIndex"] = { bg = "#7e8188", fg = "#81a1c1" },
    ["BufferCurrentMod"] = { bg = "#7e8188", fg = "#ebcb8b" },
    ["BufferCurrentSign"] = { bg = "#7e8188", fg = "#81a1c1" },
    ["BufferCurrentTarget"] = { bg = "#7e8188", fg = "#bf616a" },
    ["BufferInactive"] = { bg = "#232831", fg = "#60728a" },
    ["BufferInactiveIndex"] = { bg = "#232831", fg = "#60728a" },
    ["BufferInactiveMod"] = { bg = "#232831", fg = "#54524f" },
    ["BufferInactiveSign"] = { bg = "#232831", fg = "#444c5e" },
    ["BufferInactiveTarget"] = { bg = "#232831", fg = "#bf616a" },
    ["BufferTabpage"] = { bg = "#232831", fg = "#444c5e" },
    ["BufferTabpages"] = { bg = "#232831" },
    ["BufferVisible"] = { bg = "#232831", fg = "#cdcecf" },
    ["BufferVisibleIndex"] = { bg = "#232831", fg = "#81a1c1" },
    ["BufferVisibleMod"] = { bg = "#232831", fg = "#ebcb8b" },
    ["BufferVisibleSign"] = { bg = "#232831", fg = "#81a1c1" },
    ["BufferVisibleTarget"] = { bg = "#232831", fg = "#bf616a" },
    ["Character"] = { link = "String" },
    ["CmpDocumentation"] = { bg = "#232831", fg = "#cdcecf" },
    ["CmpDocumentationBorder"] = { bg = "#232831", fg = "#3e4a5b" },
    ["CmpItemAbbr"] = { fg = "#cdcecf" },
    ["CmpItemAbbrDeprecated"] = { fg = "#7e8188", strikethrough = true },
    ["CmpItemAbbrMatch"] = { fg = "#8cafd2" },
    ["CmpItemAbbrMatchFuzzy"] = { fg = "#8cafd2" },
    ["CmpItemKindClass"] = { link = "Type" },
    ["CmpItemKindConstant"] = { link = "@constant" },
    ["CmpItemKindConstructor"] = { link = "Function" },
    ["CmpItemKindDefault"] = { fg = "#abb1bb" },
    ["CmpItemKindEnum"] = { link = "Constant" },
    ["CmpItemKindEnumMember"] = { link = "@field" },
    ["CmpItemKindEvent"] = { link = "Constant" },
    ["CmpItemKindField"] = { link = "@field" },
    ["CmpItemKindFunction"] = { link = "Function" },
    ["CmpItemKindInterface"] = { link = "Constant" },
    ["CmpItemKindKeyword"] = { link = "Identifier" },
    ["CmpItemKindMethod"] = { link = "Function" },
    ["CmpItemKindModule"] = { link = "@namespace" },
    ["CmpItemKindOperator"] = { link = "Operator" },
    ["CmpItemKindProperty"] = { link = "@property" },
    ["CmpItemKindReference"] = { link = "Keyword" },
    ["CmpItemKindSnippet"] = { fg = "#abb1bb" },
    ["CmpItemKindStruct"] = { link = "Type" },
    ["CmpItemKindTypeParameter"] = { link = "@field" },
    ["CmpItemKindUnit"] = { link = "Constant" },
    ["CmpItemKindValue"] = { link = "Keyword" },
    ["CmpItemKindVariable"] = { link = "@variable" },
    ["CmpItemMenu"] = { link = "Comment" },
    ["ColorColumn"] = { bg = "#39404f" },
    ["Comment"] = { fg = "#60728a" },
    ["Conceal"] = { fg = "#5a657d" },
    ["Conditional"] = { fg = "#c895bf" },
    ["Constant"] = { fg = "#d89079" },
    ["CurSearch"] = { link = "IncSearch" },
    ["Cursor"] = { bg = "#cdcecf", fg = "#2e3440" },
    ["CursorColumn"] = { link = "CursorLine" },
    ["CursorIM"] = { link = "Cursor" },
    ["CursorLine"] = { bg = "#444c5e" },
    ["CursorLineNr"] = { fg = "#ebcb8b" },
    ["DapUIBreakpointsCurrentLine"] = { fg = "#a3be8c" },
    ["DapUIBreakpointsDisabledLine"] = { fg = "#60728a" },
    ["DapUIBreakpointsInfo"] = { fg = "#81a1c1" },
    ["DapUIBreakpointsLine"] = { link = "DapUILineNumber" },
    ["DapUIBreakpointsPath"] = { fg = "#93ccdc" },
    ["DapUIDecoration"] = { fg = "#7e8188" },
    ["DapUIFloatBorder"] = { link = "FloatBorder" },
    ["DapUIFrameName"] = { link = "Normal" },
    ["DapUILineNumber"] = { link = "Number" },
    ["DapUIModifiedValue"] = { fg = "#e5e9f0" },
    ["DapUIScope"] = { fg = "#93ccdc" },
    ["DapUISource"] = { link = "Keyword" },
    ["DapUIStoppedThread"] = { fg = "#93ccdc" },
    ["DapUIThread"] = { link = "String" },
    ["DapUIType"] = { link = "Type" },
    ["DapUIValue"] = { fg = "#e5e9f0" },
    ["DapUIVariable"] = { fg = "#e5e9f0" },
    ["DapUIWatchesEmpty"] = { fg = "#bf616a" },
    ["DapUIWatchesError"] = { fg = "#bf616a" },
    ["DapUIWatchesValue"] = { fg = "#ebcb8b" },
    ["DashboardCenter"] = { link = "String" },
    ["DashboardFooter"] = { fg = "#d89079" },
    ["DashboardHeader"] = { link = "Title" },
    ["DashboardShortCut"] = { link = "Identifier" },
    ["Debug"] = { link = "Special" },
    ["Define"] = { link = "PreProc" },
    ["Delimiter"] = { link = "Special" },
    ["DiagnosticError"] = { fg = "#bf616a" },
    ["DiagnosticHint"] = { fg = "#a3be8c" },
    ["DiagnosticInfo"] = { fg = "#81a1c1" },
    ["DiagnosticSignError"] = { link = "DiagnosticError" },
    ["DiagnosticSignHint"] = { link = "DiagnosticHint" },
    ["DiagnosticSignInfo"] = { link = "DiagnosticInfo" },
    ["DiagnosticSignWarn"] = { link = "DiagnosticWarn" },
    ["DiagnosticUnderlineError"] = { undercurl = true },
    ["DiagnosticUnderlineHint"] = { undercurl = true },
    ["DiagnosticUnderlineInfo"] = { undercurl = true },
    ["DiagnosticUnderlineWarn"] = { undercurl = true },
    ["DiagnosticVirtualTextError"] = { bg = "#4b3d48", fg = "#bf616a" },
    ["DiagnosticVirtualTextHint"] = { bg = "#45504f", fg = "#a3be8c" },
    ["DiagnosticVirtualTextInfo"] = { bg = "#3f4a5a", fg = "#81a1c1" },
    ["DiagnosticVirtualTextWarn"] = { bg = "#54524f", fg = "#ebcb8b" },
    ["DiagnosticWarn"] = { fg = "#ebcb8b" },
    ["DiffAdd"] = { bg = "#3c4548" },
    ["DiffChange"] = { bg = "#364150" },
    ["DiffDelete"] = { bg = "#403843" },
    ["DiffText"] = { bg = "#3d515e" },
    ["Directory"] = { fg = "#8cafd2" },
    ["EndOfBuffer"] = { fg = "#2e3440" },
    ["Error"] = { fg = "#bf616a" },
    ["ErrorMsg"] = { fg = "#bf616a" },
    ["Exception"] = { link = "Keyword" },
    ["FernBranchText"] = { fg = "#81a1c1" },
    ["FidgetTask"] = { link = "LineNr" },
    ["FidgetTitle"] = { link = "Title" },
    ["Float"] = { link = "Number" },
    ["FloatBorder"] = { fg = "#7e8188" },
    ["FocusedSymbol"] = { link = "Search" },
    ["FoldColumn"] = { fg = "#7e8188" },
    ["Folded"] = { bg = "#39404f", fg = "#7e8188" },
    ["Function"] = { fg = "#8cafd2" },
    ["GitGutterAdd"] = { fg = "#a3be8c" },
    ["GitGutterChange"] = { fg = "#ebcb8b" },
    ["GitGutterDelete"] = { fg = "#bf616a" },
    ["GitSignsAdd"] = { fg = "#a3be8c" },
    ["GitSignsChange"] = { fg = "#ebcb8b" },
    ["GitSignsDelete"] = { fg = "#bf616a" },
    ["GlyphPalette0"] = { fg = "#3b4252" },
    ["GlyphPalette1"] = { fg = "#bf616a" },
    ["GlyphPalette10"] = { fg = "#b1d196" },
    ["GlyphPalette11"] = { fg = "#f0d399" },
    ["GlyphPalette12"] = { fg = "#8cafd2" },
    ["GlyphPalette13"] = { fg = "#c895bf" },
    ["GlyphPalette14"] = { fg = "#93ccdc" },
    ["GlyphPalette15"] = { fg = "#e7ecf4" },
    ["GlyphPalette2"] = { fg = "#a3be8c" },
    ["GlyphPalette3"] = { fg = "#ebcb8b" },
    ["GlyphPalette4"] = { fg = "#81a1c1" },
    ["GlyphPalette5"] = { fg = "#b48ead" },
    ["GlyphPalette6"] = { fg = "#88c0d0" },
    ["GlyphPalette7"] = { fg = "#e7ecf4" },
    ["GlyphPalette8"] = { fg = "#465780" },
    ["GlyphPalette9"] = { fg = "#d06f79" },
    ["HopNextKey"] = { fg = "#88c0d0" },
    ["HopNextKey1"] = { fg = "#81a1c1" },
    ["HopNextKey2"] = { fg = "#668aab" },
    ["HopUnmatched"] = { fg = "#60728a" },
    ["Identifier"] = { fg = "#88c0d0" },
    ["IncSearch"] = { bg = "#a3be8c", fg = "#3e4a5b" },
    ["Include"] = { link = "PreProc" },
    ["Italic"] = { italic = true },
    ["Keyword"] = { fg = "#b48ead" },
    ["Label"] = { link = "Conditional" },
    ["LightspeedGreyWash"] = { fg = "#60728a" },
    ["LineNr"] = { fg = "#7e8188" },
    ["LspCodeLens"] = { fg = "#60728a" },
    ["LspCodeLensSeparator"] = { fg = "#7e8188" },
    ["LspFloatWinBorder"] = { fg = "#7e8188" },
    ["LspFloatWinNormal"] = { bg = "#232831" },
    ["LspReferenceRead"] = { bg = "#3e4a5b" },
    ["LspReferenceText"] = { bg = "#3e4a5b" },
    ["LspReferenceWrite"] = { bg = "#3e4a5b" },
    ["LspSagaBorderTitle"] = { link = "Title" },
    ["LspSagaCodeActionBorder"] = { fg = "#7e8188" },
    ["LspSagaCodeActionContent"] = { link = "String" },
    ["LspSagaCodeActionTitle"] = { link = "Title" },
    ["LspSagaDefPreviewBorder"] = { fg = "#7e8188" },
    ["LspSagaFinderSelection"] = { fg = "#3e4a5b" },
    ["LspSagaHoverBorder"] = { fg = "#7e8188" },
    ["LspSagaRenameBorder"] = { fg = "#7e8188" },
    ["LspSagaSignatureHelpBorder"] = { fg = "#bf616a" },
    ["LspSignatureActiveParameter"] = { fg = "#4f6074" },
    ["LspTroubleCount"] = { bg = "#7e8188", fg = "#b48ead" },
    ["LspTroubleNormal"] = { bg = "#232831", fg = "#7e8188" },
    ["LspTroubleText"] = { fg = "#abb1bb" },
    ["Macro"] = { link = "PreProc" },
    ["MatchParen"] = { fg = "#ebcb8b" },
    ["ModeMsg"] = { fg = "#ebcb8b" },
    ["ModesCopy"] = { bg = "#ebcb8b" },
    ["ModesDelete"] = { bg = "#bf616a" },
    ["ModesInsert"] = { bg = "#88c0d0" },
    ["ModesVisual"] = { bg = "#b48ead" },
    ["MoreMsg"] = { fg = "#81a1c1" },
    ["NeoTreeDimText"] = { link = "Conceal" },
    ["NeoTreeDirectoryIcon"] = { fg = "#81a1c1" },
    ["NeoTreeDirectoryName"] = { fg = "#81a1c1" },
    ["NeoTreeDotfile"] = { fg = "#668aab" },
    ["NeoTreeFileName"] = { fg = "#abb1bb" },
    ["NeoTreeFileNameOpened"] = { fg = "#cdcecf" },
    ["NeoTreeGitAdded"] = { fg = "#a3be8c" },
    ["NeoTreeGitConflict"] = { fg = "#c9826b" },
    ["NeoTreeGitDeleted"] = { fg = "#bf616a" },
    ["NeoTreeGitIgnored"] = { fg = "#60728a" },
    ["NeoTreeGitModified"] = { fg = "#ebcb8b" },
    ["NeoTreeGitUntracked"] = { fg = "#9d7495" },
    ["NeoTreeIndentMarker"] = { fg = "#5a657d" },
    ["NeoTreeNormal"] = { bg = "#232831", fg = "#cdcecf" },
    ["NeoTreeNormalNC"] = { link = "NeoTreeNormal" },
    ["NeoTreeRootName"] = { fg = "#c9826b" },
    ["NeoTreeSymbolicLinkTarget"] = { fg = "#a96ca5" },
    ["NeogitBranch"] = { fg = "#ebcb8b" },
    ["NeogitDiffAdd"] = { fg = "#a3be8c" },
    ["NeogitDiffAddHighlight"] = { bg = "#3c4548" },
    ["NeogitDiffContextHighlight"] = { bg = "#364150" },
    ["NeogitDiffDelete"] = { fg = "#bf616a" },
    ["NeogitDiffDeleteHighlight"] = { bg = "#403843" },
    ["NeogitHunkHeader"] = { bg = "#444c5e", fg = "#81a1c1" },
    ["NeogitHunkHeaderHighlight"] = { bg = "#3e4a5b", fg = "#81a1c1" },
    ["NeogitNotificationError"] = { fg = "#bf616a" },
    ["NeogitNotificationInfo"] = { fg = "#81a1c1" },
    ["NeogitNotificationWarning"] = { fg = "#ebcb8b" },
    ["NeogitRemote"] = { fg = "#a3be8c" },
    ["NonText"] = { fg = "#5a657d" },
    ["Normal"] = { fg = "#cdcecf" },
    ["NormalFloat"] = { bg = "#232831", fg = "#cdcecf" },
    ["NormalNC"] = { bg = "#2e3440", fg = "#cdcecf" },
    ["NotifyDEBUGBorder"] = { fg = "#687966" },
    ["NotifyDEBUGIcon"] = { link = "NotifyDEBUGTitle" },
    ["NotifyDEBUGTitle"] = { fg = "#a3be8c" },
    ["NotifyERRORBorder"] = { fg = "#764a55" },
    ["NotifyERRORIcon"] = { link = "NotifyERRORTitle" },
    ["NotifyERRORTitle"] = { fg = "#bf616a" },
    ["NotifyINFOBorder"] = { fg = "#586a80" },
    ["NotifyINFOIcon"] = { link = "NotifyINFOTitle" },
    ["NotifyINFOTitle"] = { fg = "#81a1c1" },
    ["NotifyTRACEBorder"] = { fg = "#5a657d" },
    ["NotifyTRACEIcon"] = { link = "NotifyTRACETitle" },
    ["NotifyTRACETitle"] = { fg = "#60728a" },
    ["NotifyWARNBorder"] = { fg = "#8c7f66" },
    ["NotifyWARNIcon"] = { link = "NotifyWARNTitle" },
    ["NotifyWARNTitle"] = { fg = "#ebcb8b" },
    ["Number"] = { fg = "#c9826b" },
    ["NvimTreeEmptyFolderName"] = { fg = "#7e8188" },
    ["NvimTreeFolderIcon"] = { fg = "#81a1c1" },
    ["NvimTreeFolderName"] = { fg = "#81a1c1" },
    ["NvimTreeGitDeleted"] = { fg = "#bf616a" },
    ["NvimTreeGitDirty"] = { fg = "#ebcb8b" },
    ["NvimTreeGitMerge"] = { fg = "#c9826b" },
    ["NvimTreeGitNew"] = { fg = "#a3be8c" },
    ["NvimTreeGitRenamed"] = { link = "NvimTreeGitDeleted" },
    ["NvimTreeGitStaged"] = { link = "NvimTreeGitStaged" },
    ["NvimTreeImageFile"] = { fg = "#bbc3d4" },
    ["NvimTreeIndentMarker"] = { fg = "#5a657d" },
    ["NvimTreeNormal"] = { bg = "#232831", fg = "#cdcecf" },
    ["NvimTreeOpenedFile"] = { fg = "#d092ce" },
    ["NvimTreeOpenedFolderName"] = { fg = "#8cafd2" },
    ["NvimTreeRootFolder"] = { fg = "#c9826b" },
    ["NvimTreeSpecialFile"] = { fg = "#88c0d0" },
    ["NvimTreeSymlink"] = { fg = "#a96ca5" },
    ["NvimTreeVertSplit"] = { link = "VertSplit" },
    ["Operator"] = { fg = "#abb1bb" },
    ["Pmenu"] = { bg = "#3e4a5b", fg = "#cdcecf" },
    ["PmenuSbar"] = { link = "Pmenu" },
    ["PmenuSel"] = { bg = "#4f6074" },
    ["PmenuThumb"] = { bg = "#4f6074" },
    ["PounceAccept"] = { bg = "#d89079", fg = "#2e3440" },
    ["PounceAcceptBest"] = { bg = "#93ccdc", fg = "#2e3440" },
    ["PounceGap"] = { bg = "#3e4a5b", fg = "#cdcecf" },
    ["PounceMatch"] = { bg = "#4f6074", fg = "#cdcecf" },
    ["PreCondit"] = { link = "PreProc" },
    ["PreProc"] = { fg = "#d092ce" },
    ["Question"] = { link = "MoreMsg" },
    ["QuickFixLine"] = { link = "CursorLine" },
    ["Repeat"] = { link = "Conditional" },
    ["Search"] = { bg = "#4f6074", fg = "#cdcecf" },
    ["SignColumn"] = { fg = "#7e8188" },
    ["SignColumnSB"] = { link = "SignColumn" },
    ["Sneak"] = { bg = "#b48ead", fg = "#232831" },
    ["SneakScope"] = { bg = "#3e4a5b" },
    ["Special"] = { fg = "#8cafd2" },
    ["SpecialChar"] = { link = "Special" },
    ["SpecialComment"] = { link = "Special" },
    ["SpecialKey"] = { link = "NonText" },
    ["SpellBad"] = { undercurl = true },
    ["SpellCap"] = { undercurl = true },
    ["SpellLocal"] = { undercurl = true },
    ["SpellRare"] = { undercurl = true },
    ["Statement"] = { fg = "#b48ead" },
    ["StatusLine"] = { bg = "#232831", fg = "#abb1bb" },
    ["StatusLineNC"] = { bg = "#232831", fg = "#7e8188" },
    ["StorageClass"] = { link = "Type" },
    ["String"] = { fg = "#a3be8c" },
    ["Structure"] = { link = "Type" },
    ["Substitute"] = { bg = "#bf616a", fg = "#2e3440" },
    ["SymbolOutlineConnector"] = { link = "Conceal" },
    ["@attribute"] = { link = "Constant" },
    ["@constant.builtin"] = { fg = "#d89079" },
    ["@constructor"] = { fg = "#b48ead" },
    ["@text.danger"] = { fg = "#bf616a" },
    ["@error"] = { fg = "#bf616a" },
    ["@field"] = { fg = "#81a1c1" },
    ["@function.builtin"] = { fg = "#bf616a" },
    ["@function.macro"] = { fg = "#bf616a" },
    ["@keywordFunction"] = { fg = "#bf616a" },
    ["@keywordOperator"] = { fg = "#abb1bb" },
    ["@namespace"] = { fg = "#93ccdc" },
    ["@text.note"] = { fg = "#81a1c1" },
    ["@operator"] = { fg = "#abb1bb" },
    ["@property"] = { link = "@field" },
    ["@punctuation.bracket"] = { fg = "#abb1bb" },
    ["@punctuation.delimiter"] = { fg = "#abb1bb" },
    ["@punctuation.special"] = { fg = "#abb1bb" },
    ["@stringEscape"] = { fg = "#f0d399" },
    ["@stringRegex"] = { fg = "#f0d399" },
    ["@textReference"] = { fg = "#b48ead" },
    ["@typeBuiltin"] = { fg = "#93ccdc" },
    ["@text.uri"] = { fg = "#88c0d0" },
    ["@variable"] = { fg = "#e5e9f0" },
    ["@variableBuiltin"] = { fg = "#bf616a" },
    ["@text.warning"] = { fg = "#ebcb8b" },
    ["TabLine"] = { bg = "#39404f", fg = "#7e8188" },
    ["TabLineFill"] = { bg = "#232831" },
    ["TabLineSel"] = { bg = "#5a657d", fg = "#abb1bb" },
    ["Tag"] = { link = "Special" },
    ["TelescopeBorder"] = { fg = "#5a657d" },
    ["TelescopeMatching"] = { link = "Search" },
    ["TelescopeSelection"] = { link = "CursorLine" },
    ["TelescopeSelectionCaret"] = { fg = "#a3be8c" },
    ["Title"] = { fg = "#8cafd2" },
    ["Todo"] = { bg = "#81a1c1", fg = "#2e3440" },
    ["Type"] = { fg = "#ebcb8b" },
    ["Typedef"] = { link = "Type" },
    ["Underlined"] = { underline = true },
    ["VertSplit"] = { fg = "#5a657d" },
    ["Visual"] = { bg = "#3e4a5b" },
    ["VisualNOS"] = { link = "visual" },
    ["WarningMsg"] = { fg = "#ebcb8b" },
    ["WhichKey"] = { link = "Identifier" },
    ["WhichKeyDesc"] = { link = "Keyword" },
    ["WhichKeyFloat"] = { bg = "#232831" },
    ["WhichKeyGroup"] = { link = "Function" },
    ["WhichKeySeparator"] = { link = "Comment" },
    ["WhichKeySeperator"] = { link = "Comment" },
    ["WhichKeyValue"] = { link = "Comment" },
    ["Whitespace"] = { fg = "#39404f" },
    ["WildMenu"] = { link = "Pmenu" },
    ["diffAdded"] = { fg = "#a3be8c" },
    ["diffChanged"] = { fg = "#ebcb8b" },
    ["diffFile"] = { fg = "#81a1c1" },
    ["diffIndexLine"] = { fg = "#d092ce" },
    ["diffLine"] = { fg = "#d89079" },
    ["diffNewFile"] = { fg = "#a3be8c" },
    ["diffOldFile"] = { fg = "#ebcb8b" },
    ["diffRemoved"] = { fg = "#bf616a" },
    ["illuminatedCurWord"] = { link = "LspReferenceText" },
    ["illuminatedWord"] = { link = "LspReferenceText" },
    ["lCursor"] = { link = "Cursor" },
    ["qfFileName"] = { link = "Directory" },
    ["qfLineNr"] = { link = "lineNr" },
    ["rainbowcol1"] = { fg = "#bf616a" },
    ["rainbowcol2"] = { fg = "#ebcb8b" },
    ["rainbowcol3"] = { fg = "#a3be8c" },
    ["rainbowcol4"] = { fg = "#81a1c1" },
    ["rainbowcol5"] = { fg = "#88c0d0" },
    ["rainbowcol6"] = { fg = "#b48ead" },
    ["rainbowcol7"] = { fg = "#bf88bc" },
}

return {
    colors = colors,
    hls = hls
}
