#!/usr/bin/dash
cd /mnt/ssd/steam/steamapps/common/Celeste; SDL_AUDIODRIVER=pulse time -p -o /tmp/celeste-time-$$ obs-gamecapture ./Celeste --disable-splash
echo $(date +%F_%T) $(cat /tmp/celeste-time-$$ | awk 'NR==1{print $2}') >> ~/doc/celeste-log
