#!/bin/fish
# color manager script

if test (count $argv) -eq 1
    set -U COLORSCHEME $argv[1]
    echo "set colorscheme to" $COLORSCHEME

    # apply colorscheme changes to fish and kitty
    cp ~/.config/desktop/colors/$COLORSCHEME/kitty.conf ~/.config/kitty/colors.conf
    cp ~/.config/desktop/colors/$COLORSCHEME/fish.fish ~/.config/fish/colors.fish

    # apply colorscheme changes to neovim
    echo "return \"$COLORSCHEME\"" > ~/.config/nvim/lua/theme/scheme.lua

    #cp ~/.config/desktop/colors/$COLORSCHEME/xresources ~/.config/x11/xrdb-colors
    #xrdb -merge ~/.config/x11/xrdb-colors
else
    echo "  colors"
    echo "      current colorscheme:" $COLORSCHEME
    echo \n"  available colors"
    
    for f in (command ls ~/.config/desktop/colors)
        echo "      " $f
    end
end
