#!/bin/fish
# color manager script

if test (count $argv) -eq 1
    set -U COLORSCHEME $argv[1]
    echo "set colorscheme to" $COLORSCHEME

    # apply colorscheme changes
    cp ~/.config/desktop/colors/$COLORSCHEME/kitty.conf ~/.config/kitty/colors.conf
    cp ~/.config/desktop/colors/$COLORSCHEME/fish.fish ~/.config/fish/colors.fish

    # signal color changes
    killall -USR1 kitty
    echo $COLORSCHEME > ~/.config/colorscheme
else
    echo \n"  colors"
    echo "      current colorscheme:" $COLORSCHEME
    echo \n"  available colors"
    
    for f in (command ls ~/.config/desktop/colors)
        echo "      " $f
    end

    echo
end
