#!/usr/bin/dash

STATUS=$(headsetcontrol -b | tail -n 1 | awk '{print $2}')
case $STATUS in
    supported)
        ;;
    BATTERY_UNAVAILABLE)
        ;;
    *)
        exec echo $STATUS
        ;;
esac
