#!/usr/bin/dash

OPTS="celeste\n\
cubiomes\n\
firefox\n\
idea\n\
lonn\n\
minecraft\n\
ncmpcpp\n\
obs\n\
osu\n\
pavucontrol\n\
qcachegrind\n\
r2modman\n\
steam\n\
wayboard\n\
wireshark\n"
if [ $XDG_SESSION_TYPE = wayland ]; then
    RESULT=$(echo $OPTS | fuzzel -d --lines $(echo "$OPTS" | wc -l))
else
    RESULT=$(echo $OPTS | rofi -dmenu -p '')
fi
case $RESULT in
    celeste)
        celeste &
        ;;
    cubiomes)
        cubiomes-viewer &
        ;;
    firefox)
        firefox &
        ;;
    idea)
        idea &
        ;;
    lonn)
        cd ~/clones/lonn/ && love Lonn.love &
        ;;
    minecraft)
        prismlauncher &
        ;;
    ncmpcpp)
        foot ncmpcpp &
        ;;
    obs)
        obs &
        ;;
    osu)
        flatpak run --user sh.ppy.osu &
        ;;
    pavucontrol)
        pavucontrol &
        ;;
    qcachegrind)
        qcachegrind &
        ;;
    r2modman)
        r2modman &
        ;;
    steam)
        flatpak run --user com.valvesoftware.Steam &
        ;;
    wayboard)
        ~/src/wayboard/build/wayboard ~/.config/wayboard.cfg &
        ;;
    wireshark)
        wireshark &
        ;;
esac
