#!/usr/bin/dash

OPTS="firefox\nminecraft\nncmpcpp\nobs\npavucontrol"
case $(echo $OPTS | fuzzel -d) in
    firefox)
        firefox &
        ;;
    minecraft)
        prismlauncher &
        ;;
    ncmpcpp)
        foot ncmpcpp &
        ;;
    obs)
        obs &
        ;;
    pavucontrol)
        pavucontrol &
        ;;
esac
