#!/usr/bin/dash
case "$(cat /etc/hostname)" in
    alpine)
        FZF=$(apk info | fzf)
        if [ -n "$FZF" ]; then
            apk info $FZF
        fi
        ;;
    archbox)
        FZF=$(pacman -Qq | fzf)
        if [ -n "$FZF" ]; then
            pacman -Qi $FZF
        fi
        ;;
esac
