#!/usr/bin/fish

set FFMPEG_ARGS "-f" "x11grab"

if test (count $argv) -eq 1
    set SLOP_RES (slop -f %w,%h,%x,%y\n)
    set RES_VAL (string split ',' $SLOP_RES)

    set FFMPEG_ARGS $FFMPEG_ARGS "-video_size" "$RES_VAL[1]x$RES_VAL[2]"
    set FFMPEG_ARGS $FFMPEG_ARGS "-i" ":0.0+$RES_VAL[3],$RES_VAL[4]"

    # mp4/gif arguments
    switch $argv[1]
        case "-select"
            set ARG_PATH mp4
        case "-gif"
            set ARG_PATH gif
    end
else
    set FFMPEG_ARGS $FFMPEG_ARGS "-video_size" "1920x1080"
    set FFMPEG_ARGS $FFMPEG_ARGS "-i" ":0.0"
end

switch $ARG_PATH
    case gif
        set RECORDING_EXT gif
        set FFMPEG_ARGS $FFMPEG_ARGS "-preset" "ultrafast"
        set FFMPEG_ARGS $FFMPEG_ARGS "-framerate" "15"
    case "*"
        # video (mp4)
        set RECORDING_EXT mp4
        set FFMPEG_ARGS $FFMPEG_ARGS "-preset" "ultrafast"
        set FFMPEG_ARGS $FFMPEG_ARGS "-framerate" "30"
        set FFMPEG_ARGS $FFMPEG_ARGS "-c:v" "libx264"
        set FFMPEG_ARGS $FFMPEG_ARGS "-crf" "18"
end

ffmpeg $FFMPEG_ARGS ~/videos/recordings/(date +%c).$RECORDING_EXT &
set -U __OMNIRUN_FFMPEG_PID $last_pid
