#!/usr/bin/dash

if [ "$1" = "area" ]; then
    grim -g "$(slurp)" - | tee ~/pix/ss/$(date +%m_%d_%y-%H_%M_%S).png | wl-copy --type image/png
else
    grim -o $1 - | tee ~/pix/ss/$(date +%m_%d_%y-%H_%M_%S).png | wl-copy --type image/png
    notify-send "Screenshot taken" -t 500
fi
