#!/usr/bin/dash
case "$1" in
    area)
        grim -g "$(slurp)" - | tee ~/pix/ss/$(date +%m_%d_%y-%H_%M_%S).png | wl-copy --type image/png
        ;;
    output)
        grim -o DP-2 - | tee ~/pix/ss/$(date +%m_%d_%y-%H_%M_%S).png | wl-copy --type image/png
        notify-send "Screenshot taken" -t 500
        ;;
    mega)
        grim -o DP-2 - | tee ~/doc/megalophobia/$(date +%m_%d_%y-%H_%M_%S).png | wl-copy --type image/png
        notify-send "Screenshot taken" -t 500
        ;;
esac
