#!/usr/bin/dash

Xwayland -noreset :10 &
sleep 0.1

export DISPLAY=:10
export XDG_SESSION_TYPE=dwm
unset WAYLAND_DISPLAY
dwm &
sleep 0.1

xrdb -merge ~/.config/x11/xresources
xset r rate 300 40
xsetroot -xcf ~/.local/share/icons/crosshair/cursors/default 32
