alias dotgit="git --git-dir=$HOME/repos/dotfiles/ --work-tree=$HOME"
alias lazydotgit="lazygit --git-dir=$HOME/repos/dotfiles/ --work-tree=$HOME"
alias lock="i3lock -i ~/.config/desktop/backgrounds/7dg-blur.png"
alias ls="exa -l --icons --group-directories-first"
alias startx="startx ~/.config/x11/xinitrc"
