alias dotgit="git --git-dir=$HOME/repos/dotfiles/ --work-tree=$HOME"
alias lazydotgit="lazygit --git-dir=$HOME/repos/dotfiles/ --work-tree=$HOME"
alias lock="i3lock -i ~/.config/desktop/backgrounds/pixel-market.png -t"
alias ls="exa -l --icons --group-directories-first"
alias nvidia-settings="nvidia-settings --config=$HOME/.config/nv-settings"
alias pypy="pypy3"
alias pypy2="command pypy"
alias startx="startx ~/.config/x11/xinitrc"
alias xbindkeys="xbindkeys -f ~/.config/x11/xbindkeys"
