reset_count = "/mnt/hdd/mc/resetcount"
unpause_focus = true
poll_rate = 50
play_res = "1920x1080+0,0"
alt_res = "1920x16384+0,0"

[delay]
wp_pause = 0
idle_pause = 0
unpause = 10
stretch = 0
ghost_pie_fix = 10

[hooks]
normal_res = "xinput --set-prop 8 --type=float 155 1 0 0 0 1 0 0 0 3.16666"
alt_res = "xinput --set-prop 8 --type=float 155 1 0 0 0 1 0 0 0 6"

[keybinds]
"Ctrl-Shift-F"  = ["wall_focus", "ingame_focus"]
"D"             = ["wall_reset_all"]
"S"             = ["wall_play_first_locked"]
"LMB"           = ["wall_lock"]
"Ctrl-Shift-D"  = ["ingame_reset"]
"Insert"        = ["ingame_toggle_res"]

[obs]
enabled = true
port = 4440
password = "password123"

[wall]
enabled = true
confine_pointer = true
goto_locked = false
reset_unlock = true
grace_period = 100
stretch_res = "640x216+0,0"
use_f1 = true
freeze_at = 80
show_at = -1

[wall.moving]
enabled = true
use_gaps = true

[[wall.moving.groups]]
position = "1280x432+0,0"
width = 2
height = 2

[[wall.moving.groups]]
position = "1280x648+0,432"
width = 2
height = 3

[wall.moving.locks]
position = "640x1080+1280,0"
width = 1
height = 5

[wall.performance]
sleepbg_path = "/home/dog/.local/share/home-ext"
affinity = "advanced"

[wall.performance.advanced]
ccx_split = 2
affinity_idle = 2
affinity_low = 4
affinity_mid = 8
affinity_high = 12
affinity_active = 12
burst_length = 0
low_threshold = 25
