unpause_focus = true
poll_rate = 50
alt_res = "1920x16384+0,0"
play_res = "1920x1080+0,0"

[hooks]
normal_res = "xinput --set-prop 8 --type=float 155 1 0 0 0 1 0 0 0 3.16666"
alt_res = "xinput --set-prop 8 --type=float 155 1 0 0 0 1 0 0 0 6"

[keybinds]
"Insert" = ["ingame_toggle_res"]
