[general]
type = "setseed"
count_resets = true
resets_file = "/mnt/hdd/mc/resetcount_ssg"
affinity = "alternate"

[obs]
enabled = true
port = 4440
password = ""

[reset]
set_settings = true
delay = 50
unpause_on_focus = false

[minecraft]
fov = 70
rd = 5
sensitivity = 38

[keybinds]
focus = "Ctrl-Shift-F"
reset = "Ctrl-Shift-D"

[setseed]
seed = "8398967436125155523"
spawn_x = -217.5
spawn_z = 226.5
radius = 20.0
