unpause_focus = true
poll_rate = 50
alt_res = "1920x16384+0,0"
play_res = "300x1000+500,0"

[delay]
wp_pause = 0
idle_pause = 0
unpause = 10
stretch = 0
ghost_pie_fix = 10

[hooks]
normal_res = "xinput --set-prop 8 --type=float 155 1 0 0 0 1 0 0 0 3.16666"
alt_res = "xinput --set-prop 8 --type=float 155 1 0 0 0 1 0 0 0 6"

[keybinds]
"Ctrl-Shift-F"      = ["wall_focus", "ingame_focus"]
"Ctrl-Shift-D"      = ["wall_reset_all", "ingame_reset"]
"LMB"               = ["wall_reset"]
"Shift-LMB"         = ["wall_play"]
"Ctrl-LMB"          = ["wall_lock"]
"Ctrl-Shift-LMB"    = ["wall_reset_others"]
"Insert" = ["ingame_toggle_res"]

[obs]
enabled = true
port = 4440

[wall]
enabled = true
use_f1 = true
stretch_res = "960x360+0,0"
