[general]
type = "wall"
count_resets = true
resets_file = "/mnt/hdd/mc/resetcount"

[obs]
enabled = true
port = 4440
password = "7W7U4YZpoo9L9Ba0"

[reset]
delay = 20
pause_delay = 50
unpause_on_focus = true

[keybinds]
focus = "Ctrl-Shift-F"
reset = "Ctrl-Shift-D"
wall_reset = ""
wall_reset_others = "Ctrl-Shift"
wall_play = "Shift"
wall_lock = "Ctrl"

[wall]
hide_gui = true
stretch_windows = true
stretch_res = "640x216+0,0"
unstretch_res = "1920x1080+0,0"
use_mouse = true
goto_locked = false
sleepbg_lock = true
sleepbg_lock_path = "/home/dog/.local/share/home-ext"
grace_period = 250

[advanced_wall]
affinity = true
ccx_split = true
affinity_idle = 3
affinity_low = 4
affinity_mid = 8
affinity_high = 12
affinity_active = 12
burst_length = 400
low_threshold = 25
