[general]
type = "wall"
count_resets = true
resets_file = "/mnt/hdd/mc/resetcount"

[hooks]
wall_reset = "paplay /mnt/hdd/mc/reset.wav --device=default.remapped"
lock = "paplay /mnt/hdd/mc/lock.wav --device=default.remapped"
unlock = "paplay /mnt/hdd/mc/lock.wav --device=default.remapped"

[obs]
enabled = true
port = 4440
password = ""

[reset]
set_settings = true
delay = 50
unpause_on_focus = true
click_on_focus = false

[keybinds]
focus = "Ctrl-Shift-F"
reset = "Ctrl-Shift-D"
wall_reset = ""
wall_reset_others = "Ctrl-Shift"
wall_play = "Shift"
wall_lock = "Ctrl"

[wall]
stretch_windows = true
stretch_width = 1920
stretch_height = 320
unstretch_width = 1920
unstretch_height = 1080
use_mouse = true
goto_locked = true
no_play_generating = true
sleepbg_lock = true
sleepbg_lock_path = "/home/dog/.local/share/home-ext"

[advanced_wall]
affinity = true
affinity_idle = 1
affinity_low = 4
affinity_mid = 8
affinity_active = 12
low_threshold = 20
