reset_count = "/mnt/hdd/mc/resetcount"
unpause_focus = true
poll_rate = 50

[delay]
wp_pause = 0
idle_pause = 0
unpause = 10
stretch = 0
ghost_pie_fix = 10

[hooks]
# reset = ""
normal_res = "xinput --set-prop 8 --type=float 155 1 0 0 0 1 0 0 0 3.16666"
alt_res = "xinput --set-prop 8 --type=float 155 1 0 0 0 1 0 0 0 6"
# wall_lock = ""
# wall_unlock = ""
# wall_play = ""
# wall_reset = ""

[keybinds]
"Ctrl-Shift-F"  = ["wall_focus", "ingame_focus"]
"D"             = ["wall_reset_all"]
"S"             = ["wall_play_first_locked"]
"LMB"           = ["wall_lock"]
"Ctrl-Shift-D"  = ["ingame_reset"]
"Insert"        = ["ingame_toggle_res"]

[obs]
enabled = true
port = 4440
password = "7W7U4YZpoo9L9Ba0"

[wall]
enabled = true
confine_pointer = true
goto_locked = false
reset_unlock = true
grace_period = 100
stretch_res = "960x400+0,0"
play_res = "1920x1080+0,0"
alt_res = "1920x16384+0,0"
use_f1 = true
freeze_at = 70
show_at = -1

[wall.moving]
enabled = true
use_gaps = true

[[wall.moving.groups]]
position = "1920x800+0,140"
width = 2
height = 2

[[wall.moving.groups]]
position = "640x360+640,360"
width = 2
height = 2
cosmetic = true

[[wall.moving.groups]]
position = "1920x140+0,0"
width = 8
height = 1

[wall.moving.locks]
position = "1920x140+0,940"
width = 8
height = 1

[wall.performance]
sleepbg_path = "/home/dog/.local/share/home-ext"
affinity = "advanced"

[wall.performance.advanced]
ccx_split = 2
affinity_idle = 2
affinity_low = 4
affinity_mid = 8
affinity_high = 12
affinity_active = 12
burst_length = 0
low_threshold = 25
