#!/bin/dash

# Binds
riverctl map normal Super           Delete  spawn "screenshot-clipboard HDMI-A-1"

riverctl map normal None            XF86AudioPlay   spawn "mpc -p 6660 toggle" # the aula F75 has weird
riverctl map normal None            XF86HomePage    spawn "mpc -p 6660 toggle" # function keys

# Input configuration
POINTER_XM2WE="pointer-13159-6497-Endgame_Gear_XM2we_Gaming_Receiver"
POINTER_XM2WE_WIRED="pointer-13159-6496-Endgame_Gear_XM2we_Gaming_Mouse"
POINTER_G305="pointer-1133-16500-Logitech_G305"

for pointer in $POINTER_XM2WE $POINTER_XM2WE_WIRED $POINTER_G305
do
    riverctl input $pointer accel-profile flat
    riverctl input $pointer pointer-accel 0
done

# Minecraft directories/files
mkdir -p /tmp/mc/sq
mkdir -p /tmp/mclog/sq
touch /tmp/mc/sq.txt

# Programs
swaybg -i ~/.config/desktop/backgrounds/pixel-interior.png -m tile &
