#!/bin/dash

# Binds
riverctl map normal Super+Shift     Return  spawn foot
riverctl map normal Super           Return  spawn menu
riverctl map normal Super+Alt       L       spawn "swaylock -i ~/.config/desktop/backgrounds/pixel-starry.png -t"
riverctl map normal Super           Print   spawn "screenshot-clipboard output"
riverctl map normal Super+Shift     Print   spawn "screenshot-clipboard area"
riverctl map normal Super           C       close
riverctl map normal Super+Shift     Q       exit
riverctl map normal Super           F       toggle-fullscreen
riverctl map normal Super           Space   toggle-float
riverctl map normal Super           J       focus-view next
riverctl map normal Super           K       focus-view previous
riverctl map normal Super+Shift     J       swap next
riverctl map normal Super+Shift     K       swap previous
riverctl map normal Super           Period  focus-output next
riverctl map normal Super+Shift     Period  send-to-output -current-tags next
riverctl map normal Super           H       spawn "river-workspace 4 focus left"
riverctl map normal Super           L       spawn "river-workspace 4 focus right"
riverctl map normal Super+Control   Left    spawn "river-workspace 4 focus left"
riverctl map normal Super+Control   Right   spawn "river-workspace 4 focus right"
riverctl map normal Super+Shift     H       spawn "river-workspace 4 window left"
riverctl map normal Super+Shift     L       spawn "river-workspace 4 window right"
riverctl map normal Super+Shift     Left    spawn "river-workspace 4 window left"
riverctl map normal Super+Shift     Right   spawn "river-workspace 4 window right"
riverctl map normal Super+Control   H       send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super+Control   L       send-layout-cmd rivertile "main-ratio +0.05"

riverctl map normal None XF86AudioRaiseVolume spawn "volume 5%+"
riverctl map normal None XF86AudioLowerVolume spawn "volume 5%-"
riverctl map normal None XF86AudioPlay spawn "mpc -p 6660 toggle"

riverctl map-pointer normal Super BTN_LEFT  move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Mode (Passthrough)
riverctl declare-mode passthru
riverctl map normal     Super F11       enter-mode passthru
riverctl map passthru   Super F11       enter-mode normal
riverctl map passthru   Super Period    spawn "sh -c 'riverctl focus-output next; riverctl enter-mode normal'"

# Mode (Resize)
riverctl declare-mode resize
riverctl map normal Super           R       enter-mode resize
riverctl map resize None            Return  enter-mode normal
riverctl map resize None            Escape  enter-mode normal
riverctl map resize None            Left    snap left
riverctl map resize None            Right   snap right
riverctl map resize None            Up      snap up
riverctl map resize None            Down    snap down

# Options
riverctl border-color-focused 0xc3e88d
riverctl border-color-unfocused 0xff757f
riverctl set-repeat 40 300
riverctl default-layout rivertile
riverctl xcursor-theme BreezeX-Dark 32
riverctl allow-tearing disabled

POINTER_XM2WE="pointer-13159-6497-Endgame_Gear_XM2we_Gaming_Receiver"
POINTER_XM2WE_WIRED="pointer-13159-6496-Endgame_Gear_XM2we_Gaming_Mouse"
POINTER_G305="pointer-1133-16500-Logitech_G305"

for pointer in $POINTER_XM2WE $POINTER_XM2WE_WIRED $POINTER_G305
do
    riverctl input $pointer accel-profile flat
    riverctl input $pointer pointer-accel 0
done

riverctl rule-add -app-id '*' ssd
riverctl rule-add -title 'Minecraft*' float

# Minecraft directories/files
mkdir -p /tmp/mc/sq
mkdir -p /tmp/mclog/sq
touch /tmp/mc/sq.txt

# Programs
rivertile -view-padding 6 -outer-padding 6 &
kanshi &
mako &
waybar &
swaybg -i ~/.config/desktop/backgrounds/pixel-interior.png -m tile &
exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river
