local colors = {
    fg = "#c0caf5",
    bg = "#24283b",
    black = "#414868",
    skyblue = "#7aa2f7",
    cyan = "#0bd9d7",
    green = "#9ece6a",
    oceanblue = "#2ac3de",
    magenta = "#bb9af7",
    orange = "#ff9e64",
    red = "#ff768e",
    violet = "#ff007c",
    white = "#a9b1d6",
    yellow = "#e0af68"
}

local hls = {
    ["MiniTablineHidden"] = { bg = "#24283b", fg = "#a9b1d6", },
    ["MiniTablineModifiedCurrent"] = { bg = "#7aa2f7", fg = "#1D202F", },
    ["MiniTablineModifiedVisible"] = { bg = "#24283b", fg = "#c0caf5", },
    ["MiniTablineVisible"] = { bg = "#24283b", fg = "#a9b1d6", },
    ["ModeMsg"] = { fg = "#a9b1d6", },
    ["MoreMsg"] = { fg = "#7aa2f7", },
    ["MsgArea"] = { fg = "#a9b1d6", },
    ["NonText"] = { fg = "#545c7e", },
    ["Normal"] = { fg = "#c0caf5", },
    ["NormalFloat"] = { bg = "#1f2335", fg = "#c0caf5", },
    ["NormalNC"] = { fg = "#c0caf5", },
    ["NormalSB"] = { bg = "#1f2335", fg = "#a9b1d6", },
    ["NvimTreeGitDeleted"] = { fg = "#914c54", },
    ["Visual"] = { bg = "#2B3E71", },
    ["NvimTreeGitDirty"] = { fg = "#6183bb", },
    ["WarningMsg"] = { fg = "#e0af68", },
    ["NvimTreeGitNew"] = { fg = "#449dab", },
    ["WhichKeyDesc"] = { fg = "#bb9af7", },
    ["NvimTreeImageFile"] = { fg = "#a9b1d6", },
    ["NvimTreeIndentMarker"] = { fg = "#3b4261", },
    ["WhichKeySeparator"] = { fg = "#9d7cd8", },
    ["WhichKeySeperator"] = { fg = "#9d7cd8", },
    ["WhichKeyValue"] = { fg = "#737aa2", },
    ["Whitespace"] = { fg = "#3b4261", },
    ["WildMenu"] = { bg = "#2B3E71", },
    ["lCursor"] = { bg = "#c0caf5", fg = "#24283b", },
    ["qfFileName"] = { fg = "#7aa2f7", },
    ["qfLineNr"] = { fg = "#737aa2", },
    ["WhichKeyGroup"] = { fg = "#7aa2f7", },
    ["WhichKeyFloat"] = { bg = "#1f2335", },
    ["WhichKey"] = { fg = "#7dcfff", },
    ["VisualNOS"] = { bg = "#2B3E71", },
    ["VertSplit"] = { fg = "#1D202F", },
    ["Underlined"] = { underline = true, },
    ["Type"] = { fg = "#2ac3de", },
    ["Todo"] = { bg = "#e0af68", fg = "#24283b", },
    ["Title"] = { fg = "#7aa2f7", },
    ["TelescopeNormal"] = { bg = "#1f2335", fg = "#c0caf5", },
    ["TelescopeBorder"] = { bg = "#1f2335", fg = "#9d7cd8", },
    ["TabLineSel"] = { bg = "#7aa2f7", fg = "#1D202F", },
    ["TabLineFill"] = { bg = "#1D202F", },
    ["TabLine"] = { bg = "#1f2335", fg = "#3b4261", },
    ["@text.warning"] = { bg = "#e0af68", fg = "#24283b", },
    ["@variableBuiltin"] = { fg = "#f7768e", },
    ["@variable"] = {},
    ["@textReference"] = { fg = "#1abc9c", },
    ["@stringRegex"] = { fg = "#B4F9F8", },
    ["@stringEscape"] = { fg = "#bb9af7", },
    ["@punctuation.special"] = { fg = "#89ddff", },
    ["@punctuation.delimiter"] = { fg = "#89ddff", },
    ["@punctuation.bracket"] = { fg = "#a9b1d6", },
    ["@property"] = { fg = "#73daca", },
    ["@parameter"] = { fg = "#e0af68", },
    ["@operator"] = { fg = "#89ddff", },
    ["@text.note"] = { bg = "#0db9d7", fg = "#24283b", },
    ["@label"] = { fg = "#7aa2f7", },
    ["@keywordFunction"] = { fg = "#bb9af7", },
    ["@keyword"] = { italic = true, fg = "#9d7cd8", },
    ["@field"] = { fg = "#73daca", },
    ["GitSignsAdd"] = { fg = "#164846", },
    ["@constructor"] = { fg = "#bb9af7", },
    ["Substitute"] = { bg = "#f7768e", fg = "#1D202F", },
    ["Identifier"] = { fg = "#bb9af7", },
    ["StatusLineNC"] = { bg = "#1f2335", fg = "#3b4261", },
    ["StatusLine"] = { bg = "#1f2335", fg = "#a9b1d6", },
    ["Keyword"] = { italic = true, fg = "#7dcfff", },
    ["SpellRare"] = { sp = "#1abc9c", undercurl = true, },
    ["Italic"] = { italic = true, },
    ["CmpItemKindDefault"] = { fg = "#a9b1d6", },
    ["DiagnosticWarn"] = { fg = "#e0af68", },
    ["CmpItemKindConstructor"] = { fg = "#7aa2f7", },
    ["DiffChange"] = { bg = "#090B11", },
    ["CmpItemKindEnum"] = { fg = "#ff9e64", },
    ["CmpItemKindEnumMember"] = { fg = "#73daca", },
    ["CmpItemKindConstant"] = { fg = "#bb9af7", },
    ["CmpItemKindEvent"] = { fg = "#ff9e64", },
    ["CmpItemKindField"] = { fg = "#73daca", },
    ["CmpItemKindFunction"] = { fg = "#7aa2f7", },
    ["CmpItemKindInterface"] = { fg = "#ff9e64", },
    ["CmpItemKindKeyword"] = { fg = "#7dcfff", },
    ["DiffAdd"] = { bg = "#0A191B", },
    ["CmpItemKindMethod"] = { fg = "#7aa2f7", },
    ["CmpItemKindModule"] = { fg = "#e0af68", },
    ["CmpItemKindClass"] = { fg = "#ff9e64", },
    ["CmpItemKindOperator"] = { fg = "#73daca", },
    ["CmpItemKindProperty"] = { fg = "#73daca", },
    ["CmpItemKindReference"] = { fg = "#bb9af7", },
    ["CmpItemKindSnippet"] = { fg = "#737aa2", },
    ["CmpItemAbbrMatchFuzzy"] = { fg = "#2ac3de", },
    ["CmpItemKindStruct"] = { fg = "#ff9e64", },
    ["CmpItemKindTypeParameter"] = { fg = "#73daca", },
    ["CmpItemKindUnit"] = { fg = "#ff9e64", },
    ["CmpItemKindValue"] = { fg = "#bb9af7", },
    ["CmpItemKindVariable"] = { fg = "#bb9af7", },
    ["CmpItemMenu"] = { fg = "#9d7cd8", },
    ["ColorColumn"] = { bg = "#1D202F", },
    ["ErrorMsg"] = { fg = "#db4b4b", },
    ["Comment"] = { italic = true, fg = "#9d7cd8", },
    ["CmpItemAbbrMatch"] = { fg = "#2ac3de", },
    ["Conceal"] = { fg = "#737aa2", },
    ["Constant"] = { fg = "#ff9e64", },
    ["Cursor"] = { bg = "#c0caf5", fg = "#24283b", },
    ["FoldColumn"] = { bg = "#24283b", fg = "#9d7cd8", },
    ["CursorColumn"] = { bg = "#292e42", },
    ["Folded"] = { bg = "#3b4261", fg = "#7aa2f7", },
    ["CursorIM"] = { bg = "#c0caf5", fg = "#24283b", },
    ["CursorLine"] = { bg = "#292e42", },
    ["CursorLineNr"] = { fg = "#a9b1d6", },
    ["DiagnosticError"] = { fg = "#db4b4b", },
    ["CmpItemAbbrDeprecated"] = { fg = "#3b4261", strikethrough = true, },
    ["DiagnosticHint"] = { fg = "#1abc9c", },
    ["CmpItemAbbr"] = { fg = "#c0caf5", },
    ["DiagnosticInfo"] = { fg = "#0db9d7", },
    ["FloatBorder"] = { bg = "#1f2335", fg = "#9d7cd8", },
    ["DiagnosticUnderlineError"] = { sp = "#db4b4b", undercurl = true, },
    ["DiffDelete"] = { bg = "#210B0B", },
    ["GitSignsChange"] = { fg = "#394b70", },
    ["DiagnosticUnderlineHint"] = { sp = "#1abc9c", undercurl = true, },
    ["DiagnosticUnderlineInfo"] = { sp = "#0db9d7", undercurl = true, },
    ["DiagnosticUnderlineWarn"] = { sp = "#e0af68", undercurl = true, },
    ["DiagnosticVirtualTextError"] = { bg = "#160808", fg = "#db4b4b", },
    ["GitSignsDelete"] = { fg = "#823c41", },
    ["DiagnosticVirtualTextHint"] = { bg = "#031310", fg = "#1abc9c", },
    ["EndOfBuffer"] = { fg = "#24283b", },
    ["DiagnosticVirtualTextInfo"] = { bg = "#011316", fg = "#0db9d7", },
    ["IncSearch"] = { bg = "#ff9e64", fg = "#1D202F", },
    ["DiagnosticVirtualTextWarn"] = { bg = "#16120A", fg = "#e0af68", },
    ["Bold"] = { },
    ["NvimTreeNormal"] = { bg = "#1f2335", fg = "#a9b1d6", },
    ["NvimTreeNormalNC"] = { bg = "#1f2335", fg = "#a9b1d6", },
    ["NvimTreeRootFolder"] = { fg = "#7aa2f7", },
    ["NvimTreeSpecialFile"] = { underline = true, fg = "#9d7cd8", },
    ["NvimTreeSymlink"] = { fg = "#7aa2f7", },
    ["Operator"] = { fg = "#89ddff", },
    ["DiffText"] = { bg = "#394b70", },
    ["Pmenu"] = { bg = "#1f2335", fg = "#c0caf5", },
    ["PmenuSbar"] = { bg = "#2A2E3F", },
    ["Directory"] = { fg = "#7aa2f7", },
    ["PmenuSel"] = { bg = "#2F354E", },
    ["Error"] = { fg = "#db4b4b", },
    ["PmenuThumb"] = { bg = "#3b4261", },
    ["PreProc"] = { fg = "#7dcfff", },
    ["Question"] = { fg = "#7aa2f7", },
    ["QuickFixLine"] = { bg = "#2B3E71", },
    ["Function"] = { fg = "#7aa2f7", },
    ["Search"] = { bg = "#3d59a1", fg = "#c0caf5", },
    ["Character"] = { fg = "#9ece6a", },
    ["SignColumn"] = { fg = "#3b4261", },
    ["SignColumnSB"] = { bg = "#1f2335", fg = "#3b4261", },
    ["Special"] = { fg = "#2ac3de", },
    ["SpecialKey"] = { fg = "#545c7e", },
    ["SpellBad"] = { sp = "#db4b4b", undercurl = true, },
    ["SpellCap"] = { sp = "#e0af68", undercurl = true, },
    ["SpellLocal"] = { sp = "#0db9d7", undercurl = true, },
    ["LightspeedGreyWash"] = { fg = "#545c7e", },
    ["Statement"] = { fg = "#bb9af7", },
    ["LightspeedLabel"] = { underline = true, fg = "#ff007c", },
    ["CmpDocumentation"] = { bg = "#1f2335", fg = "#c0caf5", },
    ["String"] = { fg = "#9ece6a", },
    ["LightspeedLabelDistant"] = { underline = true, fg = "#73daca", },
    ["LightspeedLabelDistantOverlapped"] = { underline = true, fg = "#41a6b5", },
    ["CmpDocumentationBorder"] = { bg = "#1f2335", fg = "#9d7cd8", },
    ["@text.danger"] = { bg = "#db4b4b", fg = "#24283b", },
    ["LightspeedLabelOverlapped"] = { underline = true, fg = "#ff007c", },
    ["LightspeedMaskedChar"] = { fg = "#ff9e64", },
    ["LightspeedOneCharMatch"] = { bg = "#ff007c", fg = "#c0caf5", },
    ["LightspeedPendingOpArea"] = { bg = "#ff007c", fg = "#c0caf5", },
    ["LightspeedShortcut"] = { underline = true, fg = "#c0caf5", bg = "#ff007c", },
    ["LightspeedUnlabeledMatch"] = { fg = "#0db9d7", },
    ["LineNr"] = { fg = "#737aa2", },
    ["LspCodeLens"] = { fg = "#9d7cd8", },
    ["LspReferenceRead"] = { bg = "#3b4261", },
    ["LspReferenceText"] = { bg = "#3b4261", },
    ["LspReferenceWrite"] = { bg = "#3b4261", },
    ["LspSignatureActiveParameter"] = { fg = "#ff9e64", },
    ["MatchParen"] = { fg = "#ff9e64", },
}

return {
    colors = colors,
    hls = hls
}
