#!/bin/sh
# run xinitrc.d scripts
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# xresources
xrdb -merge ~/.config/x11/xresources

# start
picom --xrender-sync-fence --experimental-backends &
sct 3500 &
exec awesome
