#!/bin/sh

# run xinitrc.d scripts
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# xresources
xrdb -merge ~/.config/x11/xresources

# start software
picom --xrender-sync-fence --unredir-if-possible &
~/.local/share/go/bin/dwmbar &
feh --bg-scale --no-fehbg ~/.config/desktop/backgrounds/pixel-market.png

# setup monitors with xrandr
xrandr --output DP-0 --auto --output HDMI-0 --primary --left-of DP-0
xrandr --output HDMI-0 --mode 1920x1080 -r 120.00

exec dwm

# vim:ft=bash
