local colors = {
    fg = "#eaeeee",
    bg = "#0f1c1e",
    black = "#2f3239",
    skyblue = "#73a3b7",
    cyan = "#a1cdd8",
    green = "#7aa4a1",
    oceanblue = "#4d7d90",
    magenta = "#ad5c7c",
    orange = "#ff8349",
    red = "#e85c51",
    violet = "#cb7985",
    white = "#ebebeb",
    yellow = "#fda47f"
}

local hls = {
    ["AerialGuide"] = { fg = "#2d4f56" },
    ["AerialLine"] = { link = "Search" },
    ["Bold"] = { bold = true },
    ["Boolean"] = { link = "Number" },
    ["BufferCurrent"] = { bg = "#587b7b", fg = "#e6eaea" },
    ["BufferCurrentIndex"] = { bg = "#587b7b", fg = "#5a93aa" },
    ["BufferCurrentMod"] = { bg = "#587b7b", fg = "#fda47f" },
    ["BufferCurrentSign"] = { bg = "#587b7b", fg = "#5a93aa" },
    ["BufferCurrentTarget"] = { bg = "#587b7b", fg = "#e85c51" },
    ["BufferInactive"] = { bg = "#0f1c1e", fg = "#6d7f8b" },
    ["BufferInactiveIndex"] = { bg = "#0f1c1e", fg = "#6d7f8b" },
    ["BufferInactiveMod"] = { bg = "#0f1c1e", fg = "#383835" },
    ["BufferInactiveSign"] = { bg = "#0f1c1e", fg = "#254147" },
    ["BufferInactiveTarget"] = { bg = "#0f1c1e", fg = "#e85c51" },
    ["BufferTabpage"] = { bg = "#0f1c1e", fg = "#254147" },
    ["BufferTabpages"] = { bg = "#0f1c1e" },
    ["BufferVisible"] = { bg = "#0f1c1e", fg = "#e6eaea" },
    ["BufferVisibleIndex"] = { bg = "#0f1c1e", fg = "#5a93aa" },
    ["BufferVisibleMod"] = { bg = "#0f1c1e", fg = "#fda47f" },
    ["BufferVisibleSign"] = { bg = "#0f1c1e", fg = "#5a93aa" },
    ["BufferVisibleTarget"] = { bg = "#0f1c1e", fg = "#e85c51" },
    ["Character"] = { link = "String" },
    ["CmpDocumentation"] = { bg = "#0f1c1e", fg = "#e6eaea" },
    ["CmpDocumentationBorder"] = { bg = "#0f1c1e", fg = "#293e40" },
    ["CmpItemAbbr"] = { fg = "#e6eaea" },
    ["CmpItemAbbrDeprecated"] = { fg = "#587b7b", strikethrough = true },
    ["CmpItemAbbrMatch"] = { fg = "#73a3b7" },
    ["CmpItemAbbrMatchFuzzy"] = { fg = "#73a3b7" },
    ["CmpItemKindClass"] = { link = "Type" },
    ["CmpItemKindConstant"] = { link = "@constant" },
    ["CmpItemKindConstructor"] = { link = "Function" },
    ["CmpItemKindDefault"] = { fg = "#cbd9d8" },
    ["CmpItemKindEnum"] = { link = "Constant" },
    ["CmpItemKindEnumMember"] = { link = "@field" },
    ["CmpItemKindEvent"] = { link = "Constant" },
    ["CmpItemKindField"] = { link = "@field" },
    ["CmpItemKindFunction"] = { link = "Function" },
    ["CmpItemKindInterface"] = { link = "Constant" },
    ["CmpItemKindKeyword"] = { link = "Identifier" },
    ["CmpItemKindMethod"] = { link = "Function" },
    ["CmpItemKindModule"] = { link = "@namespace" },
    ["CmpItemKindOperator"] = { link = "Operator" },
    ["CmpItemKindProperty"] = { link = "@property" },
    ["CmpItemKindReference"] = { link = "Keyword" },
    ["CmpItemKindSnippet"] = { fg = "#cbd9d8" },
    ["CmpItemKindStruct"] = { link = "Type" },
    ["CmpItemKindTypeParameter"] = { link = "@field" },
    ["CmpItemKindUnit"] = { link = "Constant" },
    ["CmpItemKindValue"] = { link = "Keyword" },
    ["CmpItemKindVariable"] = { link = "@variable" },
    ["CmpItemMenu"] = { link = "Comment" },
    ["ColorColumn"] = { bg = "#1d3337" },
    ["Comment"] = { fg = "#6d7f8b" },
    ["Conceal"] = { fg = "#2d4f56" },
    ["Conditional"] = { fg = "#b97490" },
    ["Constant"] = { fg = "#ff9664" },
    ["CurSearch"] = { link = "IncSearch" },
    ["Cursor"] = { bg = "#e6eaea", fg = "#152528" },
    ["CursorColumn"] = { link = "CursorLine" },
    ["CursorIM"] = { link = "Cursor" },
    ["CursorLine"] = { bg = "#254147" },
    ["CursorLineNr"] = { fg = "#fda47f" },
    ["DapUIBreakpointsCurrentLine"] = { fg = "#7aa4a1" },
    ["DapUIBreakpointsDisabledLine"] = { fg = "#6d7f8b" },
    ["DapUIBreakpointsInfo"] = { fg = "#5a93aa" },
    ["DapUIBreakpointsLine"] = { link = "DapUILineNumber" },
    ["DapUIBreakpointsPath"] = { fg = "#afd4de" },
    ["DapUIDecoration"] = { fg = "#587b7b" },
    ["DapUIFloatBorder"] = { link = "FloatBorder" },
    ["DapUIFrameName"] = { link = "Normal" },
    ["DapUILineNumber"] = { link = "Number" },
    ["DapUIModifiedValue"] = { fg = "#ebebeb" },
    ["DapUIScope"] = { fg = "#afd4de" },
    ["DapUISource"] = { link = "Keyword" },
    ["DapUIStoppedThread"] = { fg = "#afd4de" },
    ["DapUIThread"] = { link = "String" },
    ["DapUIType"] = { link = "Type" },
    ["DapUIValue"] = { fg = "#ebebeb" },
    ["DapUIVariable"] = { fg = "#ebebeb" },
    ["DapUIWatchesEmpty"] = { fg = "#e85c51" },
    ["DapUIWatchesError"] = { fg = "#e85c51" },
    ["DapUIWatchesValue"] = { fg = "#fda47f" },
    ["DashboardCenter"] = { link = "String" },
    ["DashboardFooter"] = { fg = "#ff9664" },
    ["DashboardHeader"] = { link = "Title" },
    ["DashboardShortCut"] = { link = "Identifier" },
    ["Debug"] = { link = "Special" },
    ["Define"] = { link = "PreProc" },
    ["Delimiter"] = { link = "Special" },
    ["DiagnosticError"] = { fg = "#e85c51" },
    ["DiagnosticHint"] = { fg = "#7aa4a1" },
    ["DiagnosticInfo"] = { fg = "#5a93aa" },
    ["DiagnosticSignError"] = { link = "DiagnosticError" },
    ["DiagnosticSignHint"] = { link = "DiagnosticHint" },
    ["DiagnosticSignInfo"] = { link = "DiagnosticInfo" },
    ["DiagnosticSignWarn"] = { link = "DiagnosticWarn" },
    ["DiagnosticUnderlineError"] = { undercurl = true },
    ["DiagnosticUnderlineHint"] = { undercurl = true },
    ["DiagnosticUnderlineInfo"] = { undercurl = true },
    ["DiagnosticUnderlineWarn"] = { undercurl = true },
    ["DiagnosticVirtualTextError"] = { bg = "#352d2e", fg = "#e85c51" },
    ["DiagnosticVirtualTextHint"] = { bg = "#24383a", fg = "#7aa4a1" },
    ["DiagnosticVirtualTextInfo"] = { bg = "#1f353c", fg = "#5a93aa" },
    ["DiagnosticVirtualTextWarn"] = { bg = "#383835", fg = "#fda47f" },
    ["DiagnosticWarn"] = { fg = "#fda47f" },
    ["DiffAdd"] = { bg = "#293e40" },
    ["DiffChange"] = { bg = "#31474b" },
    ["DiffDelete"] = { bg = "#4a3332" },
    ["DiffText"] = { bg = "#466066" },
    ["Directory"] = { fg = "#73a3b7" },
    ["EndOfBuffer"] = { fg = "#152528" },
    ["Error"] = { fg = "#e85c51" },
    ["ErrorMsg"] = { fg = "#e85c51" },
    ["Exception"] = { link = "Keyword" },
    ["FernBranchText"] = { fg = "#5a93aa" },
    ["FidgetTask"] = { link = "LineNr" },
    ["FidgetTitle"] = { link = "Title" },
    ["Float"] = { link = "Number" },
    ["FloatBorder"] = { fg = "#587b7b" },
    ["FocusedSymbol"] = { link = "Search" },
    ["FoldColumn"] = { fg = "#587b7b" },
    ["Folded"] = { bg = "#1d3337", fg = "#587b7b" },
    ["Function"] = { fg = "#73a3b7" },
    ["GitGutterAdd"] = { fg = "#7aa4a1" },
    ["GitGutterChange"] = { fg = "#fda47f" },
    ["GitGutterDelete"] = { fg = "#e85c51" },
    ["GitSignsAdd"] = { fg = "#7aa4a1" },
    ["GitSignsChange"] = { fg = "#fda47f" },
    ["GitSignsDelete"] = { fg = "#e85c51" },
    ["GlyphPalette0"] = { fg = "#2f3239" },
    ["GlyphPalette1"] = { fg = "#e85c51" },
    ["GlyphPalette10"] = { fg = "#8eb2af" },
    ["GlyphPalette11"] = { fg = "#fdb292" },
    ["GlyphPalette12"] = { fg = "#73a3b7" },
    ["GlyphPalette13"] = { fg = "#b97490" },
    ["GlyphPalette14"] = { fg = "#afd4de" },
    ["GlyphPalette15"] = { fg = "#eeeeee" },
    ["GlyphPalette2"] = { fg = "#7aa4a1" },
    ["GlyphPalette3"] = { fg = "#fda47f" },
    ["GlyphPalette4"] = { fg = "#5a93aa" },
    ["GlyphPalette5"] = { fg = "#ad5c7c" },
    ["GlyphPalette6"] = { fg = "#a1cdd8" },
    ["GlyphPalette7"] = { fg = "#eeeeee" },
    ["GlyphPalette8"] = { fg = "#4e5157" },
    ["GlyphPalette9"] = { fg = "#eb746b" },
    ["HopNextKey"] = { fg = "#a1cdd8" },
    ["HopNextKey1"] = { fg = "#5a93aa" },
    ["HopNextKey2"] = { fg = "#4d7d90" },
    ["HopUnmatched"] = { fg = "#6d7f8b" },
    ["Identifier"] = { fg = "#a1cdd8" },
    ["IncSearch"] = { bg = "#7aa4a1", fg = "#293e40" },
    ["Include"] = { link = "PreProc" },
    ["Italic"] = { italic = true },
    ["Keyword"] = { fg = "#ad5c7c" },
    ["Label"] = { link = "Conditional" },
    ["LightspeedGreyWash"] = { fg = "#6d7f8b" },
    ["LineNr"] = { fg = "#587b7b" },
    ["LspCodeLens"] = { fg = "#6d7f8b" },
    ["LspCodeLensSeparator"] = { fg = "#587b7b" },
    ["LspFloatWinBorder"] = { fg = "#587b7b" },
    ["LspFloatWinNormal"] = { bg = "#0f1c1e" },
    ["LspReferenceRead"] = { bg = "#293e40" },
    ["LspReferenceText"] = { bg = "#293e40" },
    ["LspReferenceWrite"] = { bg = "#293e40" },
    ["LspSagaBorderTitle"] = { link = "Title" },
    ["LspSagaCodeActionBorder"] = { fg = "#587b7b" },
    ["LspSagaCodeActionContent"] = { link = "String" },
    ["LspSagaCodeActionTitle"] = { link = "Title" },
    ["LspSagaDefPreviewBorder"] = { fg = "#587b7b" },
    ["LspSagaFinderSelection"] = { fg = "#293e40" },
    ["LspSagaHoverBorder"] = { fg = "#587b7b" },
    ["LspSagaRenameBorder"] = { fg = "#587b7b" },
    ["LspSagaSignatureHelpBorder"] = { fg = "#e85c51" },
    ["LspSignatureActiveParameter"] = { fg = "#425e5e" },
    ["LspTroubleCount"] = { bg = "#587b7b", fg = "#ad5c7c" },
    ["LspTroubleNormal"] = { bg = "#0f1c1e", fg = "#587b7b" },
    ["LspTroubleText"] = { fg = "#cbd9d8" },
    ["Macro"] = { link = "PreProc" },
    ["MatchParen"] = { fg = "#fda47f" },
    ["ModeMsg"] = { fg = "#fda47f" },
    ["ModesCopy"] = { bg = "#fda47f" },
    ["ModesDelete"] = { bg = "#e85c51" },
    ["ModesInsert"] = { bg = "#a1cdd8" },
    ["ModesVisual"] = { bg = "#ad5c7c" },
    ["MoreMsg"] = { fg = "#5a93aa" },
    ["NeoTreeDimText"] = { link = "Conceal" },
    ["NeoTreeDirectoryIcon"] = { fg = "#5a93aa" },
    ["NeoTreeDirectoryName"] = { fg = "#5a93aa" },
    ["NeoTreeDotfile"] = { fg = "#4d7d90" },
    ["NeoTreeFileName"] = { fg = "#cbd9d8" },
    ["NeoTreeFileNameOpened"] = { fg = "#e6eaea" },
    ["NeoTreeGitAdded"] = { fg = "#7aa4a1" },
    ["NeoTreeGitConflict"] = { fg = "#ff8349" },
    ["NeoTreeGitDeleted"] = { fg = "#e85c51" },
    ["NeoTreeGitIgnored"] = { fg = "#6d7f8b" },
    ["NeoTreeGitModified"] = { fg = "#fda47f" },
    ["NeoTreeGitUntracked"] = { fg = "#934e69" },
    ["NeoTreeIndentMarker"] = { fg = "#2d4f56" },
    ["NeoTreeNormal"] = { bg = "#0f1c1e", fg = "#e6eaea" },
    ["NeoTreeNormalNC"] = { link = "NeoTreeNormal" },
    ["NeoTreeRootName"] = { fg = "#ff8349" },
    ["NeoTreeSymbolicLinkTarget"] = { fg = "#ad6771" },
    ["NeogitBranch"] = { fg = "#fda47f" },
    ["NeogitDiffAdd"] = { fg = "#7aa4a1" },
    ["NeogitDiffAddHighlight"] = { bg = "#293e40" },
    ["NeogitDiffContextHighlight"] = { bg = "#31474b" },
    ["NeogitDiffDelete"] = { fg = "#e85c51" },
    ["NeogitDiffDeleteHighlight"] = { bg = "#4a3332" },
    ["NeogitHunkHeader"] = { bg = "#254147", fg = "#5a93aa" },
    ["NeogitHunkHeaderHighlight"] = { bg = "#293e40", fg = "#5a93aa" },
    ["NeogitNotificationError"] = { fg = "#e85c51" },
    ["NeogitNotificationInfo"] = { fg = "#5a93aa" },
    ["NeogitNotificationWarning"] = { fg = "#fda47f" },
    ["NeogitRemote"] = { fg = "#7aa4a1" },
    ["NonText"] = { fg = "#2d4f56" },
    ["Normal"] = { fg = "#e6eaea" },
    ["NormalFloat"] = { bg = "#0f1c1e", fg = "#e6eaea" },
    ["NormalNC"] = { bg = "#152528", fg = "#e6eaea" },
    ["NotifyDEBUGBorder"] = { fg = "#486564" },
    ["NotifyDEBUGIcon"] = { link = "NotifyDEBUGTitle" },
    ["NotifyDEBUGTitle"] = { fg = "#7aa4a1" },
    ["NotifyERRORBorder"] = { fg = "#7e403c" },
    ["NotifyERRORIcon"] = { link = "NotifyERRORTitle" },
    ["NotifyERRORTitle"] = { fg = "#e85c51" },
    ["NotifyINFOBorder"] = { fg = "#385c69" },
    ["NotifyINFOIcon"] = { link = "NotifyINFOTitle" },
    ["NotifyINFOTitle"] = { fg = "#5a93aa" },
    ["NotifyTRACEBorder"] = { fg = "#2d4f56" },
    ["NotifyTRACEIcon"] = { link = "NotifyTRACETitle" },
    ["NotifyTRACETitle"] = { fg = "#6d7f8b" },
    ["NotifyWARNBorder"] = { fg = "#896554" },
    ["NotifyWARNIcon"] = { link = "NotifyWARNTitle" },
    ["NotifyWARNTitle"] = { fg = "#fda47f" },
    ["Number"] = { fg = "#ff8349" },
    ["NvimTreeEmptyFolderName"] = { fg = "#587b7b" },
    ["NvimTreeFolderIcon"] = { fg = "#5a93aa" },
    ["NvimTreeFolderName"] = { fg = "#5a93aa" },
    ["NvimTreeGitDeleted"] = { fg = "#e85c51" },
    ["NvimTreeGitDirty"] = { fg = "#fda47f" },
    ["NvimTreeGitMerge"] = { fg = "#ff8349" },
    ["NvimTreeGitNew"] = { fg = "#7aa4a1" },
    ["NvimTreeGitRenamed"] = { link = "NvimTreeGitDeleted" },
    ["NvimTreeGitStaged"] = { link = "NvimTreeGitStaged" },
    ["NvimTreeImageFile"] = { fg = "#c8c8c8" },
    ["NvimTreeIndentMarker"] = { fg = "#2d4f56" },
    ["NvimTreeNormal"] = { bg = "#0f1c1e", fg = "#e6eaea" },
    ["NvimTreeOpenedFile"] = { fg = "#d38d97" },
    ["NvimTreeOpenedFolderName"] = { fg = "#73a3b7" },
    ["NvimTreeRootFolder"] = { fg = "#ff8349" },
    ["NvimTreeSpecialFile"] = { fg = "#a1cdd8" },
    ["NvimTreeSymlink"] = { fg = "#ad6771" },
    ["NvimTreeVertSplit"] = { link = "VertSplit" },
    ["Operator"] = { fg = "#cbd9d8" },
    ["Pmenu"] = { bg = "#293e40", fg = "#e6eaea" },
    ["PmenuSbar"] = { link = "Pmenu" },
    ["PmenuSel"] = { bg = "#425e5e" },
    ["PmenuThumb"] = { bg = "#425e5e" },
    ["PounceAccept"] = { bg = "#ff9664", fg = "#152528" },
    ["PounceAcceptBest"] = { bg = "#afd4de", fg = "#152528" },
    ["PounceGap"] = { bg = "#293e40", fg = "#e6eaea" },
    ["PounceMatch"] = { bg = "#425e5e", fg = "#e6eaea" },
    ["PreCondit"] = { link = "PreProc" },
    ["PreProc"] = { fg = "#d38d97" },
    ["Question"] = { link = "MoreMsg" },
    ["QuickFixLine"] = { link = "CursorLine" },
    ["Repeat"] = { link = "Conditional" },
    ["Search"] = { bg = "#425e5e", fg = "#e6eaea" },
    ["SignColumn"] = { fg = "#587b7b" },
    ["SignColumnSB"] = { link = "SignColumn" },
    ["Sneak"] = { bg = "#ad5c7c", fg = "#0f1c1e" },
    ["SneakScope"] = { bg = "#293e40" },
    ["Special"] = { fg = "#73a3b7" },
    ["SpecialChar"] = { link = "Special" },
    ["SpecialComment"] = { link = "Special" },
    ["SpecialKey"] = { link = "NonText" },
    ["SpellBad"] = { undercurl = true },
    ["SpellCap"] = { undercurl = true },
    ["SpellLocal"] = { undercurl = true },
    ["SpellRare"] = { undercurl = true },
    ["Statement"] = { fg = "#ad5c7c" },
    ["StatusLine"] = { bg = "#0f1c1e", fg = "#cbd9d8" },
    ["StatusLineNC"] = { bg = "#0f1c1e", fg = "#587b7b" },
    ["StorageClass"] = { link = "Type" },
    ["String"] = { fg = "#7aa4a1" },
    ["Structure"] = { link = "Type" },
    ["Substitute"] = { bg = "#e85c51", fg = "#152528" },
    ["SymbolOutlineConnector"] = { link = "Conceal" },
    ["@attribute"] = { link = "Constant" },
    ["@constant.builtin"] = { fg = "#ff9664" },
    ["@constructor"] = { fg = "#ad5c7c" },
    ["@text.danger"] = { fg = "#e85c51" },
    ["@error"] = { fg = "#e85c51" },
    ["@field"] = { fg = "#5a93aa" },
    ["@function.builtin"] = { fg = "#e85c51" },
    ["@function.macro"] = { fg = "#e85c51" },
    ["@keywordFunction"] = { fg = "#e85c51" },
    ["@keywordOperator"] = { fg = "#cbd9d8" },
    ["@namespace"] = { fg = "#afd4de" },
    ["@text.note"] = { fg = "#5a93aa" },
    ["@operator"] = { fg = "#cbd9d8" },
    ["@property"] = { link = "@field" },
    ["@punctuation.bracket"] = { fg = "#cbd9d8" },
    ["@punctuation.delimiter"] = { fg = "#cbd9d8" },
    ["@punctuation.special"] = { fg = "#cbd9d8" },
    ["@stringEscape"] = { fg = "#fdb292" },
    ["@stringRegex"] = { fg = "#fdb292" },
    ["@textReference"] = { fg = "#ad5c7c" },
    ["@typeBuiltin"] = { fg = "#afd4de" },
    ["@text.uri"] = { fg = "#a1cdd8" },
    ["@variable"] = { fg = "#ebebeb" },
    ["@variableBuiltin"] = { fg = "#e85c51" },
    ["@text.warning"] = { fg = "#fda47f" },
    ["TabLine"] = { bg = "#1d3337", fg = "#587b7b" },
    ["TabLineFill"] = { bg = "#0f1c1e" },
    ["TabLineSel"] = { bg = "#2d4f56", fg = "#cbd9d8" },
    ["Tag"] = { link = "Special" },
    ["TelescopeBorder"] = { fg = "#2d4f56" },
    ["TelescopeMatching"] = { link = "Search" },
    ["TelescopeSelection"] = { link = "CursorLine" },
    ["TelescopeSelectionCaret"] = { fg = "#7aa4a1" },
    ["Title"] = { fg = "#73a3b7" },
    ["Todo"] = { bg = "#5a93aa", fg = "#152528" },
    ["Type"] = { fg = "#fda47f" },
    ["Typedef"] = { link = "Type" },
    ["Underlined"] = { underline = true },
    ["VertSplit"] = { fg = "#2d4f56" },
    ["Visual"] = { bg = "#293e40" },
    ["VisualNOS"] = { link = "visual" },
    ["WarningMsg"] = { fg = "#fda47f" },
    ["WhichKey"] = { link = "Identifier" },
    ["WhichKeyDesc"] = { link = "Keyword" },
    ["WhichKeyFloat"] = { bg = "#0f1c1e" },
    ["WhichKeyGroup"] = { link = "Function" },
    ["WhichKeySeparator"] = { link = "Comment" },
    ["WhichKeySeperator"] = { link = "Comment" },
    ["WhichKeyValue"] = { link = "Comment" },
    ["Whitespace"] = { fg = "#1d3337" },
    ["WildMenu"] = { link = "Pmenu" },
    ["diffAdded"] = { fg = "#7aa4a1" },
    ["diffChanged"] = { fg = "#fda47f" },
    ["diffFile"] = { fg = "#5a93aa" },
    ["diffIndexLine"] = { fg = "#d38d97" },
    ["diffLine"] = { fg = "#ff9664" },
    ["diffNewFile"] = { fg = "#7aa4a1" },
    ["diffOldFile"] = { fg = "#fda47f" },
    ["diffRemoved"] = { fg = "#e85c51" },
    ["illuminatedCurWord"] = { link = "LspReferenceText" },
    ["illuminatedWord"] = { link = "LspReferenceText" },
    ["lCursor"] = { link = "Cursor" },
    ["qfFileName"] = { link = "Directory" },
    ["qfLineNr"] = { link = "lineNr" },
    ["rainbowcol1"] = { fg = "#e85c51" },
    ["rainbowcol2"] = { fg = "#fda47f" },
    ["rainbowcol3"] = { fg = "#7aa4a1" },
    ["rainbowcol4"] = { fg = "#5a93aa" },
    ["rainbowcol5"] = { fg = "#a1cdd8" },
    ["rainbowcol6"] = { fg = "#ad5c7c" },
    ["rainbowcol7"] = { fg = "#cb7985" },
}

return {
    colors = colors,
    hls = hls
}
