local waywall = require("waywall")
local helpers = require("waywall.helpers")

local keyboard = require("keyboard")
local mirrors = require("mirrors")
local util = require("util")

-- Adding libjemalloc to LD_PRELOAD causes ASAN to complain, since the initial
-- execution of waywall before the environment is reset has jemalloc loaded.
os.setenv("LD_PRELOAD", "/usr/lib/libjemalloc.so")

local config = {
    input = {
        repeat_rate = 50,
        repeat_delay = 180,

        sensitivity = 3.1701,
        confine_pointer = true,
    },
    theme = {
        background = "#2d0707",
        ninb_anchor = "right",
        ninb_opacity = 0.8,

        cursor_icon = "yellow_pink",
        cursor_theme = "crosshair",
    },
    shaders = {
        ["pie_chart"] = {
            vertex = util.read_file("pie_chart.vert"),
            fragment = util.read_file("pie_chart.frag"),
        },
    },

    experimental = {
        jit = true,
        tearing = false,
    }
}

local resolutions = { --            width    height  sens    ingame  blockf3
    thin            = util.make_res(320,     900,    0,      true,   true),
    eye             = util.make_res(320,     16384,  0.1,    false,  false),
    tall            = util.make_res(320,     16384,  0,      true,   false),
    wide            = util.make_res(1880,    320,    0,      true,   false),
}

-- Actions
local atum_reset = function()
    waywall.press_key("F12")
    waywall.set_resolution(0, 0)
end

local exec_ninb = function()
    waywall.exec("ninb")
end

config.actions = {
    -- Resolutions
    ["*-T"]             = resolutions.thin,
    ["*-Ctrl-G"]        = resolutions.eye,
    ["*-B"]             = resolutions.wide,
    ["*-G"]             = resolutions.tall,
    ["*-Grave"]         = helpers.ingame_only(keyboard.toggle_remaps),

    -- Ninjabrain Bot
    ["*-H"]             = helpers.ingame_only(helpers.toggle_floating),
    ["*-Alt-H"]         = helpers.toggle_floating,
    ["Ctrl-Shift-N"]    = exec_ninb,

    -- Miscellaneous
    ["Ctrl-Shift-D"]    = atum_reset,
}

for key, func in pairs(config.actions) do
    config.actions[key] = function()
        return keyboard.do_keybinds() and func() or false
    end
end

config.actions["*-F11"] = keyboard.toggle_layout

return config
-- This configuration file was auto-generated by waywall. Refer to the
-- documentation for more information on how to configure waywall!
--
-- To remove the auto-generated notice, delete the 'config.autogen = true'
-- line at the bottom of the file.

local waywall = require("waywall")
local helpers = require("waywall.helpers")

local config = {
    theme = {
        background = "#303030ff",
    },
}

config.actions = {}

config.autogen = true -- Delete me to remove the auto-generated notice

return config
