local colors = {
    fg = "#d6d6d7",
    bg = "#131a24",
    black = "#393b44",
    skyblue = "#719cd6",
    cyan = "#63cdcf",
    green = "#81b29a",
    oceanblue = "#577cad",
    magenta = "#9d79d6",
    orange = "#f4a261",
    red = "#c94f6d",
    violet = "#d67ad2",
    white = "#dfdfe0",
    yellow = "#dbc074"
}

local hls = {
    ["AerialGuide"] = { fg = "#415166" },
    ["AerialLine"] = { link = "Search" },
    ["Bold"] = { bold = true },
    ["Boolean"] = { link = "Number" },
    ["BufferCurrent"] = { bg = "#71839b", fg = "#cdcecf" },
    ["BufferCurrentIndex"] = { bg = "#71839b", fg = "#719cd6" },
    ["BufferCurrentMod"] = { bg = "#71839b", fg = "#dbc074" },
    ["BufferCurrentSign"] = { bg = "#71839b", fg = "#719cd6" },
    ["BufferCurrentTarget"] = { bg = "#71839b", fg = "#c94f6d" },
    ["BufferInactive"] = { bg = "#131a24", fg = "#526176" },
    ["BufferInactiveIndex"] = { bg = "#131a24", fg = "#526176" },
    ["BufferInactiveMod"] = { bg = "#131a24", fg = "#40423e" },
    ["BufferInactiveSign"] = { bg = "#131a24", fg = "#29394e" },
    ["BufferInactiveTarget"] = { bg = "#131a24", fg = "#c94f6d" },
    ["BufferTabpage"] = { bg = "#131a24", fg = "#29394e" },
    ["BufferTabpages"] = { bg = "#131a24" },
    ["BufferVisible"] = { bg = "#131a24", fg = "#cdcecf" },
    ["BufferVisibleIndex"] = { bg = "#131a24", fg = "#719cd6" },
    ["BufferVisibleMod"] = { bg = "#131a24", fg = "#dbc074" },
    ["BufferVisibleSign"] = { bg = "#131a24", fg = "#719cd6" },
    ["BufferVisibleTarget"] = { bg = "#131a24", fg = "#c94f6d" },
    ["Character"] = { link = "String" },
    ["CmpDocumentation"] = { bg = "#131a24", fg = "#cdcecf" },
    ["CmpDocumentationBorder"] = { bg = "#131a24", fg = "#223249" },
    ["CmpItemAbbr"] = { fg = "#cdcecf" },
    ["CmpItemAbbrDeprecated"] = { fg = "#71839b", strikethrough = true },
    ["CmpItemAbbrMatch"] = { fg = "#86abdc" },
    ["CmpItemAbbrMatchFuzzy"] = { fg = "#86abdc" },
    ["CmpItemKindClass"] = { link = "Type" },
    ["CmpItemKindConstant"] = { link = "TSConstant" },
    ["CmpItemKindConstructor"] = { link = "Function" },
    ["CmpItemKindDefault"] = { fg = "#aeafb0" },
    ["CmpItemKindEnum"] = { link = "Constant" },
    ["CmpItemKindEnumMember"] = { link = "TSField" },
    ["CmpItemKindEvent"] = { link = "Constant" },
    ["CmpItemKindField"] = { link = "TSField" },
    ["CmpItemKindFunction"] = { link = "Function" },
    ["CmpItemKindInterface"] = { link = "Constant" },
    ["CmpItemKindKeyword"] = { link = "Identifier" },
    ["CmpItemKindMethod"] = { link = "Function" },
    ["CmpItemKindModule"] = { link = "TSNamespace" },
    ["CmpItemKindOperator"] = { link = "Operator" },
    ["CmpItemKindProperty"] = { link = "TSProperty" },
    ["CmpItemKindReference"] = { link = "Keyword" },
    ["CmpItemKindSnippet"] = { fg = "#aeafb0" },
    ["CmpItemKindStruct"] = { link = "Type" },
    ["CmpItemKindTypeParameter"] = { link = "TSField" },
    ["CmpItemKindUnit"] = { link = "Constant" },
    ["CmpItemKindValue"] = { link = "Keyword" },
    ["CmpItemKindVariable"] = { link = "TSVariable" },
    ["CmpItemMenu"] = { link = "Comment" },
    ["ColorColumn"] = { bg = "#212e3f" },
    ["Comment"] = { fg = "#aeafb0" },
    ["Conceal"] = { fg = "#415166" },
    ["Conditional"] = { fg = "#baa1e2" },
    ["Constant"] = { fg = "#f6b079" },
    ["CurSearch"] = { link = "IncSearch" },
    ["Cursor"] = { bg = "#cdcecf", fg = "#192330" },
    ["CursorColumn"] = { link = "CursorLine" },
    ["CursorIM"] = { link = "Cursor" },
    ["CursorLine"] = { bg = "#29394e" },
    ["CursorLineNr"] = { bold = true, fg = "#dbc074" },
    ["DapUIBreakpointsCurrentLine"] = { bold = true, fg = "#81b29a" },
    ["DapUIBreakpointsDisabledLine"] = { fg = "#526176" },
    ["DapUIBreakpointsInfo"] = { fg = "#719cd6" },
    ["DapUIBreakpointsLine"] = { link = "DapUILineNumber" },
    ["DapUIBreakpointsPath"] = { fg = "#7ad4d6" },
    ["DapUIDecoration"] = { fg = "#71839b" },
    ["DapUIFloatBorder"] = { link = "FloatBorder" },
    ["DapUIFrameName"] = { link = "Normal" },
    ["DapUILineNumber"] = { link = "Number" },
    ["DapUIModifiedValue"] = { bold = true, fg = "#dfdfe0" },
    ["DapUIScope"] = { fg = "#7ad4d6" },
    ["DapUISource"] = { link = "Keyword" },
    ["DapUIStoppedThread"] = { fg = "#7ad4d6" },
    ["DapUIThread"] = { link = "String" },
    ["DapUIType"] = { link = "Type" },
    ["DapUIValue"] = { fg = "#dfdfe0" },
    ["DapUIVariable"] = { fg = "#dfdfe0" },
    ["DapUIWatchesEmpty"] = { fg = "#c94f6d" },
    ["DapUIWatchesError"] = { fg = "#c94f6d" },
    ["DapUIWatchesValue"] = { fg = "#dbc074" },
    ["DashboardCenter"] = { link = "String" },
    ["DashboardFooter"] = { fg = "#f6b079", italic = true },
    ["DashboardHeader"] = { link = "Title" },
    ["DashboardShortCut"] = { link = "Identifier" },
    ["Debug"] = { link = "Special" },
    ["Define"] = { link = "PreProc" },
    ["Delimiter"] = { link = "Special" },
    ["DiagnosticError"] = { fg = "#c94f6d" },
    ["DiagnosticHint"] = { fg = "#81b29a" },
    ["DiagnosticInfo"] = { fg = "#719cd6" },
    ["DiagnosticSignError"] = { link = "DiagnosticError" },
    ["DiagnosticSignHint"] = { link = "DiagnosticHint" },
    ["DiagnosticSignInfo"] = { link = "DiagnosticInfo" },
    ["DiagnosticSignWarn"] = { link = "DiagnosticWarn" },
    ["DiagnosticUnderlineError"] = { undercurl = true },
    ["DiagnosticUnderlineHint"] = { undercurl = true },
    ["DiagnosticUnderlineInfo"] = { undercurl = true },
    ["DiagnosticUnderlineWarn"] = { undercurl = true },
    ["DiagnosticVirtualTextError"] = { bg = "#3c2c3c", fg = "#c94f6d" },
    ["DiagnosticVirtualTextHint"] = { bg = "#2e4045", fg = "#81b29a" },
    ["DiagnosticVirtualTextInfo"] = { bg = "#2b3b51", fg = "#719cd6" },
    ["DiagnosticVirtualTextWarn"] = { bg = "#40423e", fg = "#dbc074" },
    ["DiagnosticWarn"] = { fg = "#dbc074" },
    ["DiffAdd"] = { bg = "#26343c" },
    ["DiffChange"] = { bg = "#243244" },
    ["DiffDelete"] = { bg = "#2f2837" },
    ["DiffText"] = { bg = "#253f4a" },
    ["Directory"] = { fg = "#86abdc" },
    ["EndOfBuffer"] = { fg = "#192330" },
    ["Error"] = { fg = "#c94f6d" },
    ["ErrorMsg"] = { fg = "#c94f6d" },
    ["Exception"] = { link = "Keyword" },
    ["FernBranchText"] = { fg = "#719cd6" },
    ["FidgetTask"] = { link = "LineNr" },
    ["FidgetTitle"] = { link = "Title" },
    ["Float"] = { link = "Number" },
    ["FloatBorder"] = { fg = "#71839b" },
    ["FocusedSymbol"] = { link = "Search" },
    ["FoldColumn"] = { fg = "#71839b" },
    ["Folded"] = { bg = "#212e3f", fg = "#71839b" },
    ["Function"] = { fg = "#86abdc" },
    ["GitGutterAdd"] = { fg = "#81b29a" },
    ["GitGutterChange"] = { fg = "#dbc074" },
    ["GitGutterDelete"] = { fg = "#c94f6d" },
    ["GitSignsAdd"] = { fg = "#81b29a" },
    ["GitSignsChange"] = { fg = "#dbc074" },
    ["GitSignsDelete"] = { fg = "#c94f6d" },
    ["GlyphPalette0"] = { fg = "#393b44" },
    ["GlyphPalette1"] = { fg = "#c94f6d" },
    ["GlyphPalette10"] = { fg = "#8ebaa4" },
    ["GlyphPalette11"] = { fg = "#e0c989" },
    ["GlyphPalette12"] = { fg = "#86abdc" },
    ["GlyphPalette13"] = { fg = "#baa1e2" },
    ["GlyphPalette14"] = { fg = "#7ad4d6" },
    ["GlyphPalette15"] = { fg = "#e4e4e5" },
    ["GlyphPalette2"] = { fg = "#81b29a" },
    ["GlyphPalette3"] = { fg = "#dbc074" },
    ["GlyphPalette4"] = { fg = "#719cd6" },
    ["GlyphPalette5"] = { fg = "#9d79d6" },
    ["GlyphPalette6"] = { fg = "#63cdcf" },
    ["GlyphPalette7"] = { fg = "#e4e4e5" },
    ["GlyphPalette8"] = { fg = "#575860" },
    ["GlyphPalette9"] = { fg = "#d16983" },
    ["HopNextKey"] = { bold = true, fg = "#63cdcf" },
    ["HopNextKey1"] = { bold = true, fg = "#719cd6" },
    ["HopNextKey2"] = { fg = "#6085b6" },
    ["HopUnmatched"] = { fg = "#526176" },
    ["Identifier"] = { fg = "#63cdcf" },
    ["IncSearch"] = { bg = "#81b29a", fg = "#223249" },
    ["Include"] = { link = "PreProc" },
    ["Italic"] = { italic = true },
    ["Keyword"] = { fg = "#9d79d6" },
    ["Label"] = { link = "Conditional" },
    ["LightspeedGreyWash"] = { fg = "#526176" },
    ["LineNr"] = { fg = "#71839b" },
    ["LspCodeLens"] = { fg = "#526176" },
    ["LspCodeLensSeparator"] = { fg = "#71839b" },
    ["LspFloatWinBorder"] = { fg = "#71839b" },
    ["LspFloatWinNormal"] = { bg = "#131a24" },
    ["LspReferenceRead"] = { bg = "#223249" },
    ["LspReferenceText"] = { bg = "#223249" },
    ["LspReferenceWrite"] = { bg = "#223249" },
    ["LspSagaBorderTitle"] = { link = "Title" },
    ["LspSagaCodeActionBorder"] = { fg = "#71839b" },
    ["LspSagaCodeActionContent"] = { link = "String" },
    ["LspSagaCodeActionTitle"] = { link = "Title" },
    ["LspSagaDefPreviewBorder"] = { fg = "#71839b" },
    ["LspSagaFinderSelection"] = { fg = "#223249" },
    ["LspSagaHoverBorder"] = { fg = "#71839b" },
    ["LspSagaRenameBorder"] = { fg = "#71839b" },
    ["LspSagaSignatureHelpBorder"] = { fg = "#c94f6d" },
    ["LspSignatureActiveParameter"] = { fg = "#3a567d" },
    ["LspTroubleCount"] = { bg = "#71839b", fg = "#9d79d6" },
    ["LspTroubleNormal"] = { bg = "#131a24", fg = "#71839b" },
    ["LspTroubleText"] = { fg = "#aeafb0" },
    ["Macro"] = { link = "PreProc" },
    ["MatchParen"] = { bold = true, fg = "#dbc074" },
    ["ModeMsg"] = { bold = true, fg = "#dbc074" },
    ["ModesCopy"] = { bg = "#dbc074" },
    ["ModesDelete"] = { bg = "#c94f6d" },
    ["ModesInsert"] = { bg = "#63cdcf" },
    ["ModesVisual"] = { bg = "#9d79d6" },
    ["MoreMsg"] = { bold = true, fg = "#719cd6" },
    ["NeoTreeDimText"] = { link = "Conceal" },
    ["NeoTreeDirectoryIcon"] = { fg = "#719cd6" },
    ["NeoTreeDirectoryName"] = { fg = "#719cd6" },
    ["NeoTreeDotfile"] = { fg = "#6085b6" },
    ["NeoTreeFileName"] = { fg = "#aeafb0" },
    ["NeoTreeFileNameOpened"] = { fg = "#cdcecf" },
    ["NeoTreeGitAdded"] = { fg = "#81b29a" },
    ["NeoTreeGitConflict"] = { fg = "#f4a261", italic = true },
    ["NeoTreeGitDeleted"] = { fg = "#c94f6d" },
    ["NeoTreeGitIgnored"] = { fg = "#526176" },
    ["NeoTreeGitModified"] = { fg = "#dbc074" },
    ["NeoTreeGitUntracked"] = { fg = "#8567b6" },
    ["NeoTreeIndentMarker"] = { fg = "#415166" },
    ["NeoTreeNormal"] = { bg = "#131a24", fg = "#cdcecf" },
    ["NeoTreeNormalNC"] = { link = "NeoTreeNormal" },
    ["NeoTreeRootName"] = { bold = true, fg = "#f4a261" },
    ["NeoTreeSymbolicLinkTarget"] = { fg = "#b668b2" },
    ["NeogitBranch"] = { fg = "#dbc074" },
    ["NeogitDiffAdd"] = { fg = "#81b29a" },
    ["NeogitDiffAddHighlight"] = { bg = "#26343c" },
    ["NeogitDiffContextHighlight"] = { bg = "#243244" },
    ["NeogitDiffDelete"] = { fg = "#c94f6d" },
    ["NeogitDiffDeleteHighlight"] = { bg = "#2f2837" },
    ["NeogitHunkHeader"] = { bg = "#29394e", fg = "#719cd6" },
    ["NeogitHunkHeaderHighlight"] = { bg = "#223249", fg = "#719cd6" },
    ["NeogitNotificationError"] = { fg = "#c94f6d" },
    ["NeogitNotificationInfo"] = { fg = "#719cd6" },
    ["NeogitNotificationWarning"] = { fg = "#dbc074" },
    ["NeogitRemote"] = { fg = "#81b29a" },
    ["NonText"] = { fg = "#415166" },
    ["Normal"] = { fg = "#cdcecf" },
    ["NormalFloat"] = { bg = "#131a24", fg = "#cdcecf" },
    ["NormalNC"] = { bg = "#192330", fg = "#cdcecf" },
    ["NotifyDEBUGBorder"] = { fg = "#4d6a65" },
    ["NotifyDEBUGIcon"] = { link = "NotifyDEBUGTitle" },
    ["NotifyDEBUGTitle"] = { fg = "#81b29a" },
    ["NotifyERRORBorder"] = { fg = "#71394e" },
    ["NotifyERRORIcon"] = { link = "NotifyERRORTitle" },
    ["NotifyERRORTitle"] = { fg = "#c94f6d" },
    ["NotifyINFOBorder"] = { fg = "#456083" },
    ["NotifyINFOIcon"] = { link = "NotifyINFOTitle" },
    ["NotifyINFOTitle"] = { fg = "#719cd6" },
    ["NotifyTRACEBorder"] = { fg = "#415166" },
    ["NotifyTRACEIcon"] = { link = "NotifyTRACETitle" },
    ["NotifyTRACETitle"] = { fg = "#526176" },
    ["NotifyWARNBorder"] = { fg = "#7a7252" },
    ["NotifyWARNIcon"] = { link = "NotifyWARNTitle" },
    ["NotifyWARNTitle"] = { fg = "#dbc074" },
    ["Number"] = { fg = "#f4a261" },
    ["NvimTreeEmptyFolderName"] = { fg = "#71839b" },
    ["NvimTreeFolderIcon"] = { fg = "#719cd6" },
    ["NvimTreeFolderName"] = { fg = "#719cd6" },
    ["NvimTreeGitDeleted"] = { fg = "#c94f6d" },
    ["NvimTreeGitDirty"] = { fg = "#dbc074" },
    ["NvimTreeGitMerge"] = { fg = "#f4a261" },
    ["NvimTreeGitNew"] = { fg = "#81b29a" },
    ["NvimTreeGitRenamed"] = { link = "NvimTreeGitDeleted" },
    ["NvimTreeGitStaged"] = { link = "NvimTreeGitStaged" },
    ["NvimTreeImageFile"] = { fg = "#bebebe" },
    ["NvimTreeIndentMarker"] = { fg = "#415166" },
    ["NvimTreeNormal"] = { bg = "#131a24", fg = "#cdcecf" },
    ["NvimTreeOpenedFile"] = { fg = "#dc8ed9" },
    ["NvimTreeOpenedFolderName"] = { fg = "#86abdc" },
    ["NvimTreeRootFolder"] = { bold = true, fg = "#f4a261" },
    ["NvimTreeSpecialFile"] = { fg = "#63cdcf" },
    ["NvimTreeSymlink"] = { fg = "#b668b2" },
    ["NvimTreeVertSplit"] = { link = "VertSplit" },
    ["Operator"] = { fg = "#aeafb0" },
    ["Pmenu"] = { bg = "#223249", fg = "#cdcecf" },
    ["PmenuSbar"] = { link = "Pmenu" },
    ["PmenuSel"] = { bg = "#3a567d" },
    ["PmenuThumb"] = { bg = "#3a567d" },
    ["PounceAccept"] = { bg = "#f6b079", fg = "#192330" },
    ["PounceAcceptBest"] = { bg = "#7ad4d6", fg = "#192330" },
    ["PounceGap"] = { bg = "#223249", fg = "#cdcecf" },
    ["PounceMatch"] = { bg = "#3a567d", fg = "#cdcecf" },
    ["PreCondit"] = { link = "PreProc" },
    ["PreProc"] = { fg = "#dc8ed9" },
    ["Question"] = { link = "MoreMsg" },
    ["QuickFixLine"] = { link = "CursorLine" },
    ["Repeat"] = { link = "Conditional" },
    ["Search"] = { bg = "#3a567d", fg = "#cdcecf" },
    ["SignColumn"] = { fg = "#71839b" },
    ["SignColumnSB"] = { link = "SignColumn" },
    ["Sneak"] = { bg = "#9d79d6", fg = "#131a24" },
    ["SneakScope"] = { bg = "#223249" },
    ["Special"] = { fg = "#86abdc" },
    ["SpecialChar"] = { link = "Special" },
    ["SpecialComment"] = { link = "Special" },
    ["SpecialKey"] = { link = "NonText" },
    ["SpellBad"] = { undercurl = true },
    ["SpellCap"] = { undercurl = true },
    ["SpellLocal"] = { undercurl = true },
    ["SpellRare"] = { undercurl = true },
    ["Statement"] = { fg = "#9d79d6" },
    ["StatusLine"] = { bg = "#131a24", fg = "#aeafb0" },
    ["StatusLineNC"] = { bg = "#131a24", fg = "#71839b" },
    ["StorageClass"] = { link = "Type" },
    ["String"] = { fg = "#81b29a" },
    ["Structure"] = { link = "Type" },
    ["Substitute"] = { bg = "#c94f6d", fg = "#192330" },
    ["SymbolOutlineConnector"] = { link = "Conceal" },
    ["TSAttribute"] = { link = "Constant" },
    ["TSConstBuiltin"] = { fg = "#f6b079" },
    ["TSConstructor"] = { fg = "#9d79d6" },
    ["TSDanger"] = { fg = "#c94f6d" },
    ["TSError"] = { fg = "#c94f6d" },
    ["TSField"] = { fg = "#719cd6" },
    ["TSFuncBuiltin"] = { fg = "#c94f6d" },
    ["TSFuncMacro"] = { fg = "#c94f6d" },
    ["TSKeywordFunction"] = { fg = "#c94f6d" },
    ["TSKeywordOperator"] = { bold = true, fg = "#aeafb0" },
    ["TSNamespace"] = { fg = "#7ad4d6" },
    ["TSNote"] = { fg = "#719cd6" },
    ["TSOperator"] = { fg = "#aeafb0" },
    ["TSProperty"] = { link = "TSField" },
    ["TSPunctBracket"] = { fg = "#aeafb0" },
    ["TSPunctDelimiter"] = { fg = "#aeafb0" },
    ["TSPunctSpecial"] = { fg = "#aeafb0" },
    ["TSStringEscape"] = { bold = true, fg = "#e0c989" },
    ["TSStringRegex"] = { fg = "#e0c989" },
    ["TSTextReference"] = { fg = "#9d79d6" },
    ["TSTypeBuiltin"] = { fg = "#7ad4d6" },
    ["TSURI"] = { bold = true, fg = "#63cdcf" },
    ["TSVariable"] = { fg = "#dfdfe0" },
    ["TSVariableBuiltin"] = { fg = "#c94f6d" },
    ["TSWarning"] = { fg = "#dbc074" },
    ["TabLine"] = { bg = "#212e3f", fg = "#71839b" },
    ["TabLineFill"] = { bg = "#131a24" },
    ["TabLineSel"] = { bg = "#415166", fg = "#aeafb0" },
    ["Tag"] = { link = "Special" },
    ["TelescopeBorder"] = { fg = "#415166" },
    ["TelescopeMatching"] = { link = "Search" },
    ["TelescopeSelection"] = { link = "CursorLine" },
    ["TelescopeSelectionCaret"] = { fg = "#81b29a" },
    ["Title"] = { fg = "#86abdc" },
    ["Todo"] = { bg = "#719cd6", fg = "#192330" },
    ["Type"] = { fg = "#dbc074" },
    ["Typedef"] = { link = "Type" },
    ["Underlined"] = { underline = true },
    ["VertSplit"] = { fg = "#415166" },
    ["Visual"] = { bg = "#223249" },
    ["VisualNOS"] = { link = "visual" },
    ["WarningMsg"] = { fg = "#dbc074" },
    ["WhichKey"] = { link = "Identifier" },
    ["WhichKeyDesc"] = { link = "Keyword" },
    ["WhichKeyFloat"] = { bg = "#131a24" },
    ["WhichKeyGroup"] = { link = "Function" },
    ["WhichKeySeparator"] = { link = "Comment" },
    ["WhichKeySeperator"] = { link = "Comment" },
    ["WhichKeyValue"] = { link = "Comment" },
    ["Whitespace"] = { fg = "#212e3f" },
    ["WildMenu"] = { link = "Pmenu" },
    ["diffAdded"] = { fg = "#81b29a" },
    ["diffChanged"] = { fg = "#dbc074" },
    ["diffFile"] = { fg = "#719cd6" },
    ["diffIndexLine"] = { fg = "#dc8ed9" },
    ["diffLine"] = { fg = "#f6b079" },
    ["diffNewFile"] = { fg = "#81b29a" },
    ["diffOldFile"] = { fg = "#dbc074" },
    ["diffRemoved"] = { fg = "#c94f6d" },
    ["illuminatedCurWord"] = { link = "LspReferenceText" },
    ["illuminatedWord"] = { link = "LspReferenceText" },
    ["lCursor"] = { link = "Cursor" },
    ["qfFileName"] = { link = "Directory" },
    ["qfLineNr"] = { link = "lineNr" },
    ["rainbowcol1"] = { fg = "#c94f6d" },
    ["rainbowcol2"] = { fg = "#dbc074" },
    ["rainbowcol3"] = { fg = "#81b29a" },
    ["rainbowcol4"] = { fg = "#719cd6" },
    ["rainbowcol5"] = { fg = "#63cdcf" },
    ["rainbowcol6"] = { fg = "#9d79d6" },
    ["rainbowcol7"] = { fg = "#d67ad2" },
    ["rustTSField"] = { fg = "#aeafb0" },
}

return {
    colors = colors,
    hls = hls
}
