local colors = {
    fg = "#c6d0f5", -- text
    bg = "#303446", -- base
    black = "#292c3c", -- mantle
    skyblue = "#99d1db", -- sky
    cyan = "#8caaee", -- blue
    green = "#a6d189", -- green
    oceanblue = "#85c1dc", -- sapphire
    magenta = "#f4b8e4", -- pink
    orange = "#eebebe", -- flamingo
    red = "#e78284", -- red
    violet = "#ca9ee6", -- mauve
    white = "#b5bfe2", -- subtext1
    yellow = "#e5c890" -- yellow
}

local hls = {
    ["WhichKeyGroup"] = { fg = "#8CAAEE" },
    ["WhichKeyFloat"] = { bg = "#232634" },
    ["mkdCodeDelimiter"] = { bg = "#303446", fg = "#c6d0f5" },
    ["WhichKeyDesc"] = { fg = "#F4B8E4" },
    ["htmlH1"] = { fg = "#F4B8E4" },
    ["Visual"] = { bg = "#51576d" },
    ["Underlined"] = { underline = true },
    ["Typedef"] = { fg = "#E5C890" },
    ["Todo"] = { bg = "#E5C890", fg = "#303446" },
    ["CmpItemKindField"] = { fg = "#A6D189" },
    ["CmpItemKindEvent"] = { fg = "#8CAAEE" },
    ["CmpItemKindEnumMember"] = { fg = "#E78284" },
    ["TelescopeSelectionCaret"] = { fg = "#EEBEBE" },
    ["TelescopeSelection"] = { bg = "#414559", fg = "#c6d0f5" },
    ["TelescopeMatching"] = { fg = "#8CAAEE" },
    ["CmpItemKindConstant"] = { fg = "#EF9F76" },
    ["Tag"] = { link = "Special" },
    ["CmpItemKindClass"] = { fg = "#E5C890" },
    ["TabLine"] = { bg = "#292C3C", fg = "#51576d" },
    ["TSWarning"] = { bg = "#E5C890", fg = "#303446" },
    ["TSVariableBuiltin"] = { fg = "#E78284" },
    ["TSVariable"] = { fg = "#c6d0f5" },
    ["IndentBlanklineContextChar"] = { fg = "#c6d0f5" },
    ["TSURI"] = { fg = "#F2D5CF", underline = true },
    ["TSTypeBuiltin"] = { fg = "#E5C890" },
    ["TSTextReference"] = { fg = "#BABBF1" },
    ["TSStringRegex"] = { fg = "#EF9F76" },
    ["WinBar"] = { fg = "#F2D5CF" },
    ["TSStringEscape"] = { fg = "#F4B8E4" },
    ["TSPunctSpecial"] = { fg = "#99D1DB" },
    ["TSPunctDelimiter"] = { fg = "#949cbb" },
    ["TSPunctBracket"] = { fg = "#949cbb" },
    ["TSProperty"] = { fg = "#81C8BE" },
    ["TSField"] = { fg = "#81C8BE" },
    ["TSOperator"] = { fg = "#99D1DB" },
    ["TSNote"] = { bg = "#8CAAEE", fg = "#303446" },
    ["TSNamespace"] = { fg = "#8CAAEE" },
    ["TSKeywordOperator"] = { fg = "#CA9EE6" },
    ["TSKeywordFunction"] = { fg = "#CA9EE6" },
    ["TSFuncMacro"] = { fg = "#81C8BE" },
    ["TSFuncBuiltin"] = { fg = "#EF9F76" },
    ["TSDanger"] = { bg = "#E78284", fg = "#303446" },
    ["TSConstructor"] = { fg = "#85C1DC" },
    ["TSConstBuiltin"] = { fg = "#EF9F76" },
    ["Conceal"] = { fg = "#838ba7" },
    ["Substitute"] = { bg = "#51576d", fg = "#F4B8E4" },
    ["Structure"] = { fg = "#E5C890" },
    ["StorageClass"] = { fg = "#E5C890" },
    ["SpellRare"] = { sp = "#A6D189", undercurl = true },
    ["SpellLocal"] = { sp = "#8CAAEE", undercurl = true },
    ["SpellCap"] = { sp = "#E5C890", undercurl = true },
    ["SpellBad"] = { sp = "#E78284", undercurl = true },
    ["SpecialKey"] = { fg = "#c6d0f5" },
    ["SpecialComment"] = { link = "Special" },
    ["SpecialChar"] = { link = "Special" },
    ["SignColumnSB"] = { bg = "#232634", fg = "#51576d" },
    ["Repeat"] = { fg = "#E78284" },
    ["QuickFixLine"] = { bg = "#51576d" },
    ["Question"] = { fg = "#8CAAEE" },
    ["MoreMsg"] = { fg = "#8CAAEE" },
    ["PreCondit"] = { link = "PreProc" },
    ["NvimTreeFolderName"] = { fg = "#8CAAEE" },
    ["LeapMatch"] = { fg = "#b5e395", nocombine = true, underline = true },
    ["PmenuThumb"] = { bg = "#737994" },
    ["LeapLabelPrimary"] = { bg = "#b5e395", fg = "#303446", nocombine = true },
    ["LeapLabelSecondary"] = { bg = "#99D1DB", fg = "#303446", nocombine = true },
    ["NvimTreeRootFolder"] = { fg = "#8CAAEE" },
    ["NotifyWARNTitle"] = { fg = "#E5C890" },
    ["TSTagAttribute"] = { fg = "#81C8BE" },
    ["NotifyWARNBorder"] = { fg = "#E5C890" },
    ["TSTag"] = { fg = "#CA9EE6" },
    ["NotifyTRACETitle"] = { fg = "#F2D5CF" },
    ["TSLiteral"] = { fg = "#81C8BE" },
    ["TSTitle"] = { fg = "#8CAAEE" },
    ["NotifyTRACEBorder"] = { fg = "#F2D5CF" },
    ["NotifyINFOTitle"] = { fg = "#8CAAEE" },
    ["NotifyINFOIcon"] = { fg = "#8CAAEE" },
    ["NotifyINFOBorder"] = { fg = "#8CAAEE" },
    ["LspReferenceWrite"] = { bg = "#51576d" },
    ["LspReferenceRead"] = { bg = "#51576d" },
    ["LspReferenceText"] = { bg = "#51576d" },
    ["NotifyDEBUGTitle"] = { fg = "#EF9F76" },
    ["NotifyDEBUGIcon"] = { fg = "#EF9F76" },
    ["NotifyDEBUGBorder"] = { fg = "#EF9F76" },
    ["NvimTreeGitNew"] = { fg = "#8CAAEE" },
    ["Delimiter"] = { link = "Special" },
    ["Debug"] = { link = "Special" },
    ["DashboardShortCut"] = { fg = "#F4B8E4" },
    ["DashboardHeader"] = { fg = "#8CAAEE" },
    ["DashboardFooter"] = { fg = "#E5C890" },
    ["DashboardCenter"] = { fg = "#A6D189" },
    ["PmenuSel"] = { bg = "#51576d", fg = "#c6d0f5" },
    ["NormalFloat"] = { bg = "#292C3C", fg = "#c6d0f5" },
    ["CursorIM"] = { bg = "#c6d0f5", fg = "#303446" },
    ["CurSearch"] = { bg = "#E78284", fg = "#292C3C" },
    ["ColorColumn"] = { bg = "#414559" },
    ["CmpItemKindVariable"] = { fg = "#EEBEBE" },
    ["CmpItemKindValue"] = { fg = "#EF9F76" },
    ["CmpItemKindUnit"] = { fg = "#A6D189" },
    ["Macro"] = { link = "PreProc" },
    ["Operator"] = { fg = "#99D1DB" },
    ["LspTroubleNormal"] = { bg = "#232634", fg = "#c6d0f5" },
    ["Function"] = { fg = "#8CAAEE" },
    ["Constant"] = { fg = "#EF9F76" },
    ["CmpItemKindOperator"] = { fg = "#8CAAEE" },
    ["Type"] = { fg = "#8CAAEE" },
    ["CmpItemKindMethod"] = { fg = "#8CAAEE" },
    ["Boolean"] = { fg = "#EF9F76" },
    ["Number"] = { fg = "#EF9F76" },
    ["NvimTreeEmptyFolderName"] = { fg = "#8CAAEE" },
    ["NvimTreeOpenedFolderName"] = { fg = "#8CAAEE" },
    ["NvimTreeFolderIcon"] = { fg = "#8CAAEE" },
    ["Label"] = { fg = "#EF9F76" },
    ["Italic"] = { italic = true },
    ["NvimTreeSymlink"] = { fg = "#F4B8E4" },
    ["NvimTreeOpenedFile"] = { fg = "#F4B8E4" },
    ["NvimTreeImageFile"] = { fg = "#c6d0f5" },
    ["GlyphPalette9"] = { fg = "#E78284" },
    ["NvimTreeSpecialFile"] = { fg = "#EEBEBE" },
    ["CmpItemKind"] = { fg = "#8CAAEE" },
    ["GlyphPalette7"] = { fg = "#c6d0f5" },
    ["CmpItemAbbrDeprecated"] = { fg = "#737994", strikethrough = true },
    ["GlyphPalette6"] = { fg = "#81C8BE" },
    ["GlyphPalette4"] = { fg = "#8CAAEE" },
    ["GlyphPalette3"] = { fg = "#E5C890" },
    ["GlyphPalette2"] = { fg = "#81C8BE" },
    ["TSException"] = { fg = "#CA9EE6" },
    ["TSKeywordReturn"] = { fg = "#CA9EE6" },
    ["TSKeyword"] = { fg = "#CA9EE6" },
    ["luaTSConstructor"] = { fg = "#BABBF1" },
    ["TSRepeat"] = { fg = "#CA9EE6" },
    ["TSConditional"] = { fg = "#CA9EE6" },
    ["Folded"] = { bg = "#51576d", fg = "#8CAAEE" },
    ["FoldColumn"] = { fg = "#737994" },
    ["TSMethod"] = { fg = "#8CAAEE" },
    ["FloatBorder"] = { fg = "#8CAAEE" },
    ["TSParameter"] = { fg = "#EA999C" },
    ["TSFunction"] = { fg = "#8CAAEE" },
    ["TSFloat"] = { fg = "#EF9F76" },
    ["TSBoolean"] = { fg = "#EF9F76" },
    ["TSNumber"] = { fg = "#EF9F76" },
    ["MiniStarterFooter"] = { fg = "#E5C890" },
    ["MiniStarterHeader"] = { fg = "#8CAAEE" },
    ["TSConstMacro"] = { fg = "#CA9EE6" },
    ["MiniStarterItem"] = { fg = "#c6d0f5" },
    ["MiniStarterSection"] = { fg = "#EEBEBE" },
    ["MiniStarterItemPrefix"] = { fg = "#F4B8E4" },
    ["MiniTrailspace"] = { bg = "#E78284" },
    ["GitSignsAdd"] = { fg = "#A6D189" },
    ["Bold"] = { bold = true },
    ["CmpItemAbbrMatch"] = { fg = "#c6d0f5" },
    ["CmpItemAbbrMatchFuzzy"] = { fg = "#c6d0f5" },
    ["MiniStarterInactive"] = { fg = "#626880" },
    ["MiniStarterQuery"] = { fg = "#A6D189" },
    ["MiniStarterCurrent"] = {},
    ["DiagnosticVirtualTextError"] = { bg = "NONE", fg = "#E78284" },
    ["LspSignatureActiveParameter"] = { fg = "#EF9F76" },
    ["Include"] = { fg = "#F4B8E4" },
    ["DiagnosticVirtualTextInfo"] = { bg = "NONE", fg = "#99D1DB" },
    ["DiagnosticUnderlineHint"] = { sp = "#81C8BE", underline = true },
    ["DiagnosticUnderlineError"] = { sp = "#E78284", underline = true },
    ["DiagnosticUnderlineWarn"] = { sp = "#E5C890", underline = true },
    ["DiagnosticUnderlineInfo"] = { sp = "#99D1DB", underline = true },
    ["Character"] = { fg = "#81C8BE" },
    ["DiagnosticError"] = { bg = "NONE", fg = "#E78284" },
    ["Comment"] = { fg = "#626880" },
    ["DiagnosticWarn"] = { bg = "NONE", fg = "#E5C890" },
    ["WarningMsg"] = { fg = "#E5C890" },
    ["DiagnosticInfo"] = { bg = "NONE", fg = "#99D1DB" },
    ["DiagnosticHint"] = { bg = "NONE", fg = "#81C8BE" },
    ["MiniStatuslineModeCommand"] = { bg = "#EF9F76", fg = "#303446" },
    ["MiniStatuslineInactive"] = { bg = "#292C3C", fg = "#8CAAEE" },
    ["MiniStatuslineFilename"] = { bg = "#292C3C", fg = "#c6d0f5" },
    ["MiniStatuslineFileinfo"] = { bg = "#51576d", fg = "#b5bfe2" },
    ["MiniStatuslineDevinfo"] = { bg = "#51576d", fg = "#b5bfe2" },
    ["MiniJump2dSpot"] = { bg = "#303446", fg = "#EF9F76", underline = true },
    ["MiniJump"] = { bg = "#F4B8E4", fg = "#949cbb" },
    ["MiniIndentscopePrefix"] = { nocombine = true },
    ["MiniIndentscopeSymbol"] = { fg = "#c6d0f5" },
    ["WhichKeyBorder"] = { fg = "#8CAAEE" },
    ["MiniCursorword"] = { underline = true },
    ["MiniCompletionActiveParameter"] = { underline = true },
    ["SignColumn"] = { fg = "#51576d" },
    ["NvimTreeNormal"] = { bg = "NONE", fg = "#c6d0f5" },
    ["CursorLine"] = { bg = "NONE" },
    ["VertSplit"] = { fg = "NONE" },
    ["StatusLine"] = { bg = "#292C3C", fg = "#c6d0f5" },
    ["StatusLineNC"] = { bg = "#292C3C", fg = "#51576d" },
    ["CursorColumn"] = { bg = "#292C3C" },
    ["NormalNC"] = { bg = "NONE", fg = "#c6d0f5" },
    ["MiniTestPass"] = { fg = "#A6D189" },
    ["NvimTreeStatuslineNc"] = { bg = "#292C3C", fg = "#292C3C" },
    ["MiniTestEmphasis"] = { bold = true },
    ["MiniTablineVisible"] = { bg = "#51576d", fg = "#b5bfe2" },
    ["MiniTablineTabpagesection"] = { bg = "#303446", fg = "#51576d" },
    ["MiniTablineModifiedVisible"] = { bg = "#b5bfe2", fg = "#51576d" },
    ["MiniTablineModifiedHidden"] = { bg = "#c6d0f5", fg = "NONE" },
    ["MiniTablineModifiedCurrent"] = { bg = "#c6d0f5", fg = "#303446" },
    ["MiniTablineHidden"] = { bg = "NONE", fg = "#c6d0f5" },
    ["MiniTablineFill"] = { bg = "NONE" },
    ["MiniTablineCurrent"] = { bg = "#303446", fg = "#c6d0f5" },
    ["yamlTSField"] = { fg = "#8CAAEE" },
    ["MiniStatuslineModeVisual"] = { bg = "#CA9EE6", fg = "#303446" },
    ["MiniStatuslineModeReplace"] = { bg = "#E78284", fg = "#303446" },
    ["MiniStatuslineModeOther"] = { bg = "#81C8BE", fg = "#303446" },
    ["MiniStatuslineModeNormal"] = { bg = "#8CAAEE", fg = "#292C3C" },
    ["MiniStatuslineModeInsert"] = { bg = "#A6D189", fg = "#303446" },
    ["tomlTSProperty"] = { fg = "#8CAAEE" },
    ["diffRemoved"] = { fg = "#E78284" },
    ["diffChanged"] = { fg = "#8CAAEE" },
    ["diffAdded"] = { fg = "#A6D189" },
    ["LspCodeLens"] = { fg = "#737994" },
    ["GitSignsChange"] = { fg = "#E5C890" },
    ["ModeMsg"] = { fg = "#c6d0f5" },
    ["Pmenu"] = { bg = "#414559", fg = "#949cbb" },
    ["GitSignsDelete"] = { fg = "#E78284" },
    ["EndOfBuffer"] = { fg = "#303446" },
    ["NonText"] = { fg = "#737994" },
    ["CmpItemKindStruct"] = { fg = "#8CAAEE" },
    ["CmpItemKindReference"] = { fg = "#E78284" },
    ["MsgArea"] = { fg = "#c6d0f5" },
    ["TabLineFill"] = {},
    ["Title"] = { fg = "#8CAAEE" },
    ["VisualNOS"] = { bg = "#51576d" },
    ["Whitespace"] = { fg = "#51576d" },
    ["ErrorMsg"] = { fg = "#E78284" },
    ["MsgSeparator"] = {},
    ["NormalSB"] = { bg = "#232634", fg = "#c6d0f5" },
    ["IncSearch"] = { bg = "#8FC1CC", fg = "#292C3C" },
    ["illuminatedCurWord"] = { bg = "#51576d" },
    ["WildMenu"] = { bg = "#737994" },
    ["Special"] = { fg = "#F4B8E4" },
    ["Keyword"] = { fg = "#F4B8E4" },
    ["diffFile"] = { fg = "#8CAAEE" },
    ["healthWarning"] = { fg = "#E5C890" },
    ["healthSuccess"] = { fg = "#81C8BE" },
    ["MatchParen"] = { fg = "#EF9F76" },
    ["PmenuSbar"] = { bg = "#51576d" },
    ["debugPC"] = { bg = "#232634" },
    ["debugBreakpoint"] = { bg = "#303446", fg = "#737994" },
    ["healthError"] = { fg = "#E78284" },
    ["CursorLineNr"] = { fg = "#BABBF1" },
    ["Directory"] = { fg = "#8CAAEE" },
    ["String"] = { fg = "#A6D189" },
    ["TSText"] = { fg = "#c6d0f5" },
    ["Normal"] = { bg = "NONE", fg = "#c6d0f5" },
    ["LineNr"] = { fg = "#51576d" },
    ["diffIndexLine"] = { fg = "#81C8BE" },
    ["TabLineSel"] = { bg = "#51576d", fg = "#A6D189" },
    ["diffLine"] = { fg = "#737994" },
    ["diffNewFile"] = { fg = "#EF9F76" },
    ["diffOldFile"] = { fg = "#E5C890" },
    ["Search"] = { bg = "#506373", fg = "#c6d0f5" },
    ["illuminatedWord"] = { bg = "#51576d" },
    ["PreProc"] = { fg = "#F4B8E4" },
    ["Define"] = { link = "PreProc" },
    ["IndentBlanklineContextStart"] = { sp = "#c6d0f5", underline = true },
    ["NvimTreeVertSplit"] = { bg = "NONE", fg = "#303446" },
    ["DiffChange"] = { bg = "#363C52" },
    ["DiffAdd"] = { bg = "#455052" },
    ["DiffDelete"] = { bg = "#514251" },
    ["DiffText"] = { bg = "#414964" },
    ["Float"] = { fg = "#EF9F76" },
    ["GlyphPalette1"] = { fg = "#E78284" },
    ["TelescopeBorder"] = { fg = "#8CAAEE" },
    ["DiagnosticVirtualTextHint"] = { bg = "NONE", fg = "#81C8BE" },
    ["WhichKeySeperator"] = { fg = "#737994" },
    ["WhichKeyValue"] = { fg = "#737994" },
    ["htmlH2"] = { fg = "#8CAAEE" },
    ["mkdCodeStart"] = { fg = "#EEBEBE" },
    ["mkdCodeEnd"] = { fg = "#EEBEBE" },
    ["TSConstant"] = { fg = "#EF9F76" },
    ["Error"] = { fg = "#E78284" },
    ["Conditional"] = { fg = "#E78284" },
    ["NotifyERRORTitle"] = { fg = "#E78284" },
    ["NotifyERRORIcon"] = { fg = "#E78284" },
    ["Identifier"] = { fg = "#EEBEBE" },
    ["CmpItemKindConstructor"] = { fg = "#8CAAEE" },
    ["Statement"] = { fg = "#CA9EE6" },
    ["TSEmphasis"] = { fg = "#EA999C" },
    ["TSStrong"] = { fg = "#EA999C" },
    ["MiniCursorwordCurrent"] = { underline = true },
    ["MiniSurround"] = { bg = "#F4B8E4", fg = "#51576d" },
    ["cppTSProperty"] = { fg = "#F2D5CF" },
    ["LspTroubleCount"] = { bg = "#51576d", fg = "#F4B8E4" },
    ["CmpItemKindProperty"] = { fg = "#A6D189" },
    ["CmpItemKindModule"] = { fg = "#8CAAEE" },
    ["CmpItemKindKeyword"] = { fg = "#E78284" },
    ["CmpItemKindInterface"] = { fg = "#E5C890" },
    ["CmpItemKindFunction"] = { fg = "#8CAAEE" },
    ["DiagnosticVirtualTextWarn"] = { bg = "NONE", fg = "#E5C890" },
    ["MiniStarterItemBullet"] = { fg = "#8CAAEE" },
    ["NvimTreeGitDirty"] = { fg = "#E5C890" },
    ["CmpItemKindFile"] = { fg = "#8CAAEE" },
    ["CmpItemMenu"] = { fg = "#c6d0f5" },
    ["NotifyTRACEIcon"] = { fg = "#F2D5CF" },
    ["NotifyWARNIcon"] = { fg = "#E5C890" },
    ["CmpItemKindCopilot"] = { fg = "#81C8BE" },
    ["CmpItemKindFolder"] = { fg = "#8CAAEE" },
    ["tsxTSTagAttribute"] = { fg = "#CA9EE6" },
    ["NvimTreeGitDeleted"] = { fg = "#E78284" },
    ["CmpItemKindText"] = { fg = "#81C8BE" },
    ["typescriptTSConstructor"] = { fg = "#BABBF1" },
    ["tsxTSConstructor"] = { fg = "#BABBF1" },
    ["CmpItemKindColor"] = { fg = "#E78284" },
    ["TSTagDelimiter"] = { fg = "#99D1DB" },
    ["jsonTSLabel"] = { fg = "#8CAAEE" },
    ["TSString"] = { fg = "#A6D189" },
    ["MiniTestFail"] = { fg = "#E78284" },
    ["CmpItemKindEnum"] = { fg = "#A6D189" },
    ["NotifyERRORBorder"] = { fg = "#E78284" },
    ["TSLabel"] = { fg = "#85C1DC" },
    ["TSType"] = { fg = "#E5C890" },
    ["TSInclude"] = { fg = "#CA9EE6" },
    ["CmpItemAbbr"] = { fg = "#949cbb" },
    ["NvimTreeIndentMarker"] = { fg = "#737994" },
    ["markdownH6"] = { fg = "#81C8BE" },
    ["markdownH5"] = { fg = "#F4B8E4" },
    ["markdownH4"] = { fg = "#E5C890" },
    ["markdownH3"] = { fg = "#A6D189" },
    ["markdownH2"] = { fg = "#CA9EE6" },
    ["markdownH1"] = { fg = "#BABBF1" },
    ["markdownLinkText"] = { fg = "#8CAAEE", underline = true },
    ["markdownCodeBlock"] = { fg = "#EEBEBE" },
    ["markdownCode"] = { fg = "#EEBEBE" },
    ["markdownHeadingDelimiter"] = { fg = "#EF9F76" },
    ["CmpItemKindSnippet"] = { fg = "#CA9EE6" },
    ["WhichKey"] = { fg = "#EEBEBE" },
    ["LspTroubleText"] = { fg = "#A6D189" },
    ["CmpItemKindTypeParameter"] = { fg = "#8CAAEE" },
    ["IndentBlanklineChar"] = { fg = "#414559" },
    ["qfLineNr"] = { fg = "#E5C890" },
    ["qfFileName"] = { fg = "#8CAAEE" },
    ["lCursor"] = { bg = "#c6d0f5", fg = "#303446" },
    ["Cursor"] = { bg = "#c6d0f5", fg = "#303446" },
    ["LspDiagnosticsUnderlineHint"] = { sp = "#81C8BE", underline = true },
    ["LspDiagnosticsUnderlineInformation"] = { sp = "#99D1DB", underline = true },
    ["LspDiagnosticsUnderlineWarning"] = { sp = "#E5C890", underline = true },
    ["LspDiagnosticsUnderlineError"] = { sp = "#E78284", underline = true },
    ["LspDiagnosticsVirtualTextHint"] = { fg = "#81C8BE" },
    ["LspDiagnosticsVirtualTextInformation"] = { fg = "#99D1DB" },
    ["LspDiagnosticsVirtualTextWarning"] = { fg = "#E5C890" },
    ["LspDiagnosticsVirtualTextError"] = { fg = "#E78284" },
    ["LspDiagnosticsHint"] = { fg = "#81C8BE" },
    ["LspDiagnosticsInformation"] = { fg = "#99D1DB" },
    ["LspDiagnosticsWarning"] = { fg = "#E5C890" },
    ["LspDiagnosticsError"] = { fg = "#E78284" },
    ["LspDiagnosticsDefaultHint"] = { fg = "#81C8BE" },
    ["LspDiagnosticsDefaultInformation"] = { fg = "#99D1DB" },
    ["LspDiagnosticsDefaultWarning"] = { fg = "#E5C890" },
    ["LspDiagnosticsDefaultError"] = { fg = "#E78284" },
}

return {
    colors = colors,
    hls = hls
}
