local colors = {
    fg = "#c0caf5",
    bg = "#24283b",
    black = "#414868",
    skyblue = "#7aa2f7",
    cyan = "#0bd9d7",
    green = "#9ece6a",
    oceanblue = "#2ac3de",
    magenta = "#bb9af7",
    orange = "#ff9e64",
    red = "#ff768e",
    violet = "#ff007c",
    white = "#a9b1d6",
    yellow = "#e0af68"
}

local hls = {
    ["Conceal"] = { fg = "#737aa2", },
    ["Constant"] = { fg = "#ff9e64", },
    ["Cursor"] = { fg = "#1a1b26", bg = "#c0caf5", },
    ["TSDanger"] = { fg = "#1a1b26", bg = "#db4b4b", },
    ["CursorColumn"] = { bg = "#292e42", },
    ["TSKeyword"] = { fg = "#9d7cd8", },
    ["CursorIM"] = { fg = "#1a1b26", bg = "#c0caf5", },
    ["CursorLine"] = { bg = "#292e42", },
    ["CursorLineNr"] = { fg = "#a9b1d6", },
    ["DiagnosticError"] = { fg = "#db4b4b", },
    ["TSParameter"] = { fg = "#e0af68", },
    ["DiagnosticHint"] = { fg = "#1abc9c", },
    ["TSPunctBracket"] = { fg = "#a9b1d6", },
    ["DiagnosticInfo"] = { fg = "#0db9d7", },
    ["TSPunctSpecial"] = { fg = "#89ddff", },
    ["DiagnosticUnderlineError"] = { sp = "#db4b4b", undercurl = true, },
    ["TSStringRegex"] = { fg = "#B4F9F8", },
    ["DiagnosticUnderlineHint"] = { sp = "#1abc9c", undercurl = true, },
    ["DiagnosticUnderlineInfo"] = { sp = "#0db9d7", undercurl = true, },
    ["DiagnosticUnderlineWarn"] = { sp = "#e0af68", undercurl = true, },
    ["DiagnosticVirtualTextError"] = { fg = "#db4b4b", bg = "#160808", },
    ["TabLine"] = { fg = "#3b4261", bg = "#1f2335", },
    ["DiagnosticVirtualTextHint"] = { fg = "#1abc9c", bg = "#031310", },
    ["DiagnosticVirtualTextInfo"] = { fg = "#0db9d7", bg = "#011316", },
    ["DiagnosticVirtualTextWarn"] = { fg = "#e0af68", bg = "#16120A", },
    ["DiagnosticWarn"] = { fg = "#e0af68", },
    ["DiffAdd"] = { bg = "#0A191B", },
    ["DiffChange"] = { bg = "#090B11", },
    ["DiffDelete"] = { bg = "#210B0B", },
    ["DiffText"] = { bg = "#394b70", },
    ["Directory"] = { fg = "#7aa2f7", },
    ["EndOfBuffer"] = { fg = "#1a1b26", },
    ["Error"] = { fg = "#db4b4b", },
    ["ErrorMsg"] = { fg = "#db4b4b", },
    ["FloatBorder"] = { fg = "#9d7cd8", bg = "#1f2335", },
    ["FoldColumn"] = { fg = "#9d7cd8", bg = "#1a1b26", },
    ["Folded"] = { fg = "#7aa2f7", bg = "#3b4261", },
    ["Function"] = { fg = "#7aa2f7", },
    ["GitSignsAdd"] = { fg = "#164846", },
    ["GitSignsChange"] = { fg = "#394b70", },
    ["GitSignsDelete"] = { fg = "#823c41", },
    ["Identifier"] = { fg = "#bb9af7", },
    ["IncSearch"] = { fg = "#1D202F", bg = "#ff9e64", },
    ["Italic"] = { italic = true, },
    ["Keyword"] = { fg = "#7dcfff", },
    ["LightspeedGreyWash"] = { fg = "#545c7e", },
    ["LightspeedLabel"] = { fg = "#ff007c", underline = true, },
    ["LightspeedLabelDistant"] = { fg = "#73daca", underline = true, },
    ["LightspeedLabelDistantOverlapped"] = { fg = "#41a6b5", underline = true, },
    ["LightspeedLabelOverlapped"] = { fg = "#ff007c", underline = true, },
    ["LightspeedMaskedChar"] = { fg = "#ff9e64", },
    ["LightspeedOneCharMatch"] = { bg = "#ff007c", fg = "#c0caf5", },
    ["LightspeedPendingOpArea"] = { fg = "#c0caf5", bg = "#ff007c", },
    ["LightspeedShortcut"] = { bg = "#ff007c", underline = true, fg = "#c0caf5", },
    ["LightspeedUnlabeledMatch"] = { fg = "#0db9d7", },
    ["LineNr"] = { fg = "#737aa2", },
    ["LspCodeLens"] = { fg = "#9d7cd8", },
    ["LspReferenceRead"] = { bg = "#3b4261", },
    ["LspReferenceText"] = { bg = "#3b4261", },
    ["LspReferenceWrite"] = { bg = "#3b4261", },
    ["LspSignatureActiveParameter"] = { fg = "#ff9e64", },
    ["MatchParen"] = { fg = "#ff9e64", },
    ["MiniTablineCurrent"] = { fg = "#1D202F", bg = "#7aa2f7", },
    ["MiniTablineFill"] = {},
    ["MiniTablineHidden"] = { fg = "#a9b1d6", bg = "#1a1b26", },
    ["MiniTablineModifiedCurrent"] = { fg = "#1D202F", bg = "#7aa2f7", },
    ["MiniTablineModifiedVisible"] = { fg = "#c0caf5", bg = "#1a1b26", },
    ["MiniTablineVisible"] = { fg = "#a9b1d6", bg = "#1a1b26", },
    ["ModeMsg"] = { fg = "#a9b1d6", },
    ["MoreMsg"] = { fg = "#7aa2f7", },
    ["MsgArea"] = { fg = "#a9b1d6", },
    ["NonText"] = { fg = "#545c7e", },
    ["Normal"] = { fg = "#c0caf5", },
    ["Whitespace"] = { fg = "#3b4261", },
    ["WildMenu"] = { bg = "#2B3E71", },
    ["lCursor"] = { fg = "#1a1b26", bg = "#c0caf5", },
    ["qfFileName"] = { fg = "#7aa2f7", },
    ["qfLineNr"] = { fg = "#737aa2", },
    ["WhichKeyValue"] = { fg = "#737aa2", },
    ["WhichKeySeperator"] = { fg = "#9d7cd8", },
    ["WhichKeySeparator"] = { fg = "#9d7cd8", },
    ["WhichKeyGroup"] = { fg = "#7aa2f7", },
    ["WhichKeyFloat"] = { bg = "#1f2335", },
    ["WhichKeyDesc"] = { fg = "#bb9af7", },
    ["WhichKey"] = { fg = "#7dcfff", },
    ["WarningMsg"] = { fg = "#e0af68", },
    ["VisualNOS"] = { bg = "#2B3E71", },
    ["Visual"] = { bg = "#2B3E71", },
    ["VertSplit"] = { fg = "#1D202F", },
    ["Underlined"] = { underline = true, },
    ["Type"] = { fg = "#2ac3de", },
    ["Todo"] = { fg = "#1a1b26", bg = "#e0af68", },
    ["Title"] = { fg = "#7aa2f7", },
    ["TelescopeNormal"] = { fg = "#c0caf5", bg = "#1f2335", },
    ["TelescopeBorder"] = { fg = "#9d7cd8", bg = "#1f2335", },
    ["TabLineSel"] = { fg = "#1D202F", bg = "#7aa2f7", },
    ["TabLineFill"] = { bg = "#1D202F", },
    ["TSWarning"] = { fg = "#1a1b26", bg = "#e0af68", },
    ["TSVariableBuiltin"] = { fg = "#f7768e", },
    ["TSVariable"] = {},
    ["TSTextReference"] = { fg = "#1abc9c", },
    ["TSStringEscape"] = { fg = "#bb9af7", },
    ["TSPunctDelimiter"] = { fg = "#89ddff", },
    ["TSProperty"] = { fg = "#73daca", },
    ["TSOperator"] = { fg = "#89ddff", },
    ["TSNote"] = { fg = "#1a1b26", bg = "#0db9d7", },
    ["TSLabel"] = { fg = "#7aa2f7", },
    ["TSKeywordFunction"] = { fg = "#bb9af7", },
    ["TSField"] = { fg = "#73daca", },
    ["TSConstructor"] = { fg = "#bb9af7", },
    ["Substitute"] = { fg = "#1D202F", bg = "#f7768e", },
    ["CmpItemAbbrDeprecated"] = { strikethrough = true, fg = "#3b4261", },
    ["StatusLineNC"] = { fg = "#3b4261", bg = "#1f2335", },
    ["CmpItemKindClass"] = { fg = "#ff9e64", },
    ["Statement"] = { fg = "#bb9af7", },
    ["SpellRare"] = { sp = "#1abc9c", undercurl = true, },
    ["CmpItemAbbr"] = { fg = "#c0caf5", },
    ["CmpItemKindConstant"] = { fg = "#bb9af7", },
    ["CmpItemKindConstructor"] = { fg = "#7aa2f7", },
    ["CmpItemKindVariable"] = { fg = "#bb9af7", },
    ["CmpItemKindValue"] = { fg = "#bb9af7", },
    ["CmpItemKindUnit"] = { fg = "#ff9e64", },
    ["CmpItemKindTypeParameter"] = { fg = "#73daca", },
    ["CmpItemKindStruct"] = { fg = "#ff9e64", },
    ["CmpItemKindSnippet"] = { fg = "#737aa2", },
    ["Bold"] = { },
    ["CmpItemKindDefault"] = { fg = "#a9b1d6", },
    ["Character"] = { fg = "#9ece6a", },
    ["CmpItemKindProperty"] = { fg = "#73daca", },
    ["CmpItemKindEnum"] = { fg = "#ff9e64", },
    ["CmpDocumentation"] = { fg = "#c0caf5", bg = "#1f2335", },
    ["CmpItemKindModule"] = { fg = "#e0af68", },
    ["CmpItemKindMethod"] = { fg = "#7aa2f7", },
    ["CmpItemKindEnumMember"] = { fg = "#73daca", },
    ["CmpDocumentationBorder"] = { fg = "#9d7cd8", bg = "#1f2335", },
    ["CmpItemKindInterface"] = { fg = "#ff9e64", },
    ["NormalFloat"] = { fg = "#c0caf5", bg = "#1f2335", },
    ["NormalNC"] = { fg = "#c0caf5", },
    ["NormalSB"] = { fg = "#a9b1d6", bg = "#1f2335", },
    ["NvimTreeGitDeleted"] = { fg = "#914c54", },
    ["CmpItemAbbrMatch"] = { fg = "#2ac3de", },
    ["NvimTreeGitDirty"] = { fg = "#6183bb", },
    ["CmpItemAbbrMatchFuzzy"] = { fg = "#2ac3de", },
    ["NvimTreeGitNew"] = { fg = "#449dab", },
    ["CmpItemKindEvent"] = { fg = "#ff9e64", },
    ["NvimTreeImageFile"] = { fg = "#a9b1d6", },
    ["NvimTreeIndentMarker"] = { fg = "#3b4261", },
    ["NvimTreeNormal"] = { fg = "#a9b1d6", bg = "#1f2335", },
    ["NvimTreeNormalNC"] = { fg = "#a9b1d6", bg = "#1f2335", },
    ["NvimTreeRootFolder"] = { fg = "#7aa2f7", },
    ["NvimTreeSpecialFile"] = { fg = "#9d7cd8", underline = true, },
    ["NvimTreeSymlink"] = { fg = "#7aa2f7", },
    ["Operator"] = { fg = "#89ddff", },
    ["CmpItemKindField"] = { fg = "#73daca", },
    ["Pmenu"] = { fg = "#c0caf5", bg = "#1f2335", },
    ["PmenuSbar"] = { bg = "#2A2E3F", },
    ["CmpItemKindFunction"] = { fg = "#7aa2f7", },
    ["PmenuSel"] = { bg = "#2F354E", },
    ["CmpItemKindKeyword"] = { fg = "#7dcfff", },
    ["PmenuThumb"] = { bg = "#3b4261", },
    ["PreProc"] = { fg = "#7dcfff", },
    ["Question"] = { fg = "#7aa2f7", },
    ["QuickFixLine"] = { bg = "#2B3E71", },
    ["CmpItemKindOperator"] = { fg = "#73daca", },
    ["Search"] = { fg = "#c0caf5", bg = "#3d59a1", },
    ["CmpItemKindReference"] = { fg = "#bb9af7", },
    ["SignColumn"] = { fg = "#3b4261", },
    ["SignColumnSB"] = { fg = "#3b4261", bg = "#1f2335", },
    ["Special"] = { fg = "#2ac3de", },
    ["SpecialKey"] = { fg = "#545c7e", },
    ["SpellBad"] = { sp = "#db4b4b", undercurl = true, },
    ["SpellCap"] = { sp = "#e0af68", undercurl = true, },
    ["SpellLocal"] = { sp = "#0db9d7", undercurl = true, },
    ["CmpItemMenu"] = { fg = "#9d7cd8", },
    ["ColorColumn"] = { bg = "#1D202F", },
    ["StatusLine"] = { fg = "#a9b1d6", bg = "#1f2335", },
    ["Comment"] = { fg = "#9d7cd8", },
    ["String"] = { fg = "#9ece6a", },
}

return {
    colors = colors,
    hls = hls
}
